scoreboard players random @s random 1 47
execute at @s[scores={random=1}] run give @s arrow 1 6
execute at @s[scores={random=2}] run give @s arrow 1 7
execute at @s[scores={random=3}] run give @s arrow 1 8
execute at @s[scores={random=4}] run give @s arrow 1 9
execute at @s[scores={random=5}] run give @s arrow 1 10
execute at @s[scores={random=6}] run give @s arrow 1 11
execute at @s[scores={random=7}] run give @s arrow 1 12
execute at @s[scores={random=8}] run give @s arrow 1 13
execute at @s[scores={random=9}] run give @s arrow 1 14
execute at @s[scores={random=10}] run give @s arrow 1 15
execute at @s[scores={random=11}] run give @s arrow 1 16
execute at @s[scores={random=12}] run give @s arrow 1 17
execute at @s[scores={random=13}] run give @s arrow 1 18
execute at @s[scores={random=14}] run give @s arrow 1 19
execute at @s[scores={random=15}] run give @s arrow 1 20
execute at @s[scores={random=16}] run give @s arrow 1 21
execute at @s[scores={random=17}] run give @s arrow 1 22
execute at @s[scores={random=18}] run give @s arrow 1 23
execute at @s[scores={random=19}] run give @s arrow 1 24
execute at @s[scores={random=20}] run give @s arrow 1 25
execute at @s[scores={random=21}] run give @s arrow 1 26
execute at @s[scores={random=22}] run give @s arrow 1 27
execute at @s[scores={random=23}] run give @s arrow 1 28
execute at @s[scores={random=24}] run give @s arrow 1 29
execute at @s[scores={random=25}] run give @s arrow 1 30
execute at @s[scores={random=26}] run give @s arrow 1 31
execute at @s[scores={random=27}] run give @s arrow 1 32
execute at @s[scores={random=28}] run give @s arrow 1 33
execute at @s[scores={random=29}] run give @s arrow 1 34
execute at @s[scores={random=30}] run give @s arrow 1 35
execute at @s[scores={random=31}] run give @s arrow 1 36
execute at @s[scores={random=32}] run give @s arrow 1 37
execute at @s[scores={random=33}] run give @s arrow 1 38
execute at @s[scores={random=34}] run give @s arrow 1 39
execute at @s[scores={random=35}] run give @s arrow 1 40
execute at @s[scores={random=36}] run give @s arrow 1 41
execute at @s[scores={random=37}] run give @s arrow 1 42
execute at @s[scores={random=38}] run give @s arrow 1 43
execute at @s[scores={random=39}] run give @s arrow 1 44
execute at @s[scores={random=40}] run give @s arrow 1 45
execute at @s[scores={random=41}] run give @s arrow 1 46
execute at @s[scores={random=42}] run give @s arrow 1 47
function randomize