scoreboard players random @s random 1 70
execute at @s[scores={random=1}] run give @s waxed_weathered_cut_copper_stairs
execute at @s[scores={random=2}] run give @s waxed_weathered_cut_copper_slab
execute at @s[scores={random=3}] run give @s waxed_weathered_cut_copper
execute at @s[scores={random=4}] run give @s waxed_weathered_copper_trapdoor
execute at @s[scores={random=5}] run give @s waxed_weathered_copper_grate
execute at @s[scores={random=6}] run give @s waxed_weathered_copper_door
execute at @s[scores={random=7}] run give @s waxed_weathered_copper_bulb
execute at @s[scores={random=8}] run give @s waxed_weathered_copper
execute at @s[scores={random=9}] run give @s waxed_weathered_chiseled_copper
execute at @s[scores={random=10}] run give @s waxed_oxidized_cut_copper_stairs
execute at @s[scores={random=11}] run give @s waxed_oxidized_cut_copper_slab
execute at @s[scores={random=12}] run give @s waxed_oxidized_cut_copper
execute at @s[scores={random=13}] run give @s waxed_oxidized_copper_trapdoor
execute at @s[scores={random=14}] run give @s waxed_oxidized_copper_grate
execute at @s[scores={random=15}] run give @s waxed_oxidized_copper_door
execute at @s[scores={random=16}] run give @s waxed_oxidized_copper_bulb
execute at @s[scores={random=17}] run give @s waxed_oxidized_copper
execute at @s[scores={random=18}] run give @s waxed_oxidized_chiseled_copper
execute at @s[scores={random=19}] run give @s waxed_exposed_cut_copper_stairs
execute at @s[scores={random=20}] run give @s waxed_exposed_cut_copper_slab
execute at @s[scores={random=21}] run give @s waxed_exposed_cut_copper
execute at @s[scores={random=22}] run give @s waxed_exposed_copper_trapdoor
execute at @s[scores={random=23}] run give @s waxed_exposed_copper_grate
execute at @s[scores={random=24}] run give @s waxed_exposed_copper_door
execute at @s[scores={random=25}] run give @s waxed_exposed_copper_bulb
execute at @s[scores={random=26}] run give @s waxed_exposed_copper
execute at @s[scores={random=27}] run give @s waxed_exposed_chiseled_copper
execute at @s[scores={random=28}] run give @s waxed_cut_copper_stairs
execute at @s[scores={random=29}] run give @s waxed_cut_copper_slab
execute at @s[scores={random=30}] run give @s waxed_cut_copper
execute at @s[scores={random=31}] run give @s waxed_copper_trapdoor
execute at @s[scores={random=32}] run give @s waxed_copper_grate
execute at @s[scores={random=33}] run give @s waxed_copper_door
execute at @s[scores={random=34}] run give @s waxed_copper_bulb
execute at @s[scores={random=35}] run give @s waxed_copper
execute at @s[scores={random=36}] run give @s waxed_chiseled_copper
execute at @s[scores={random=37}] run give @s weathered_cut_copper_stairs
execute at @s[scores={random=38}] run give @s weathered_cut_copper_slab
execute at @s[scores={random=39}] run give @s weathered_cut_copper
execute at @s[scores={random=40}] run give @s weathered_copper_trapdoor
execute at @s[scores={random=41}] run give @s weathered_copper_grate
execute at @s[scores={random=42}] run give @s weathered_copper_door
execute at @s[scores={random=43}] run give @s weathered_copper_bulb
execute at @s[scores={random=44}] run give @s weathered_copper
execute at @s[scores={random=45}] run give @s weathered_chiseled_copper
execute at @s[scores={random=46}] run give @s oxidized_cut_copper_stairs
execute at @s[scores={random=47}] run give @s oxidized_cut_copper_slab
execute at @s[scores={random=48}] run give @s oxidized_cut_copper
execute at @s[scores={random=49}] run give @s oxidized_copper_trapdoor
execute at @s[scores={random=50}] run give @s oxidized_copper_grate
execute at @s[scores={random=51}] run give @s oxidized_copper_door
execute at @s[scores={random=52}] run give @s oxidized_copper_bulb
execute at @s[scores={random=53}] run give @s oxidized_copper
execute at @s[scores={random=54}] run give @s oxidized_chiseled_copper
execute at @s[scores={random=55}] run give @s exposed_chiseled_copper
execute at @s[scores={random=56}] run give @s exposed_copper
execute at @s[scores={random=57}] run give @s exposed_copper_bulb
execute at @s[scores={random=58}] run give @s exposed_copper_door
execute at @s[scores={random=59}] run give @s exposed_copper_grate
execute at @s[scores={random=60}] run give @s exposed_copper_trapdoor
execute at @s[scores={random=61}] run give @s exposed_cut_copper
execute at @s[scores={random=62}] run give @s exposed_cut_copper_slab
execute at @s[scores={random=63}] run give @s exposed_cut_copper_stairs
execute at @s[scores={random=64}] run give @s deepslate_copper_ore
execute at @s[scores={random=65}] run give @s copper_block
execute at @s[scores={random=66}] run give @s copper_bulb
execute at @s[scores={random=67}] run give @s copper_door
execute at @s[scores={random=68}] run give @s copper_grate
execute at @s[scores={random=69}] run give @s copper_trapdoor
execute at @s[scores={random=70}] run give @s chiseled_copper
function randomize