scoreboard players random @s random 1 79
execute at @s[scores={random=1}] run give @s allay_spawn_egg
execute at @s[scores={random=2}] run give @s armadillo_spawn_egg
execute at @s[scores={random=3}] run give @s axolotl_spawn_egg
execute at @s[scores={random=4}] run give @s bat_spawn_egg
execute at @s[scores={random=5}] run give @s bee_spawn_egg
execute at @s[scores={random=6}] run give @s blaze_spawn_egg
execute at @s[scores={random=7}] run give @s bogged_spawn_egg
execute at @s[scores={random=8}] run give @s breeze_spawn_egg
execute at @s[scores={random=9}] run give @s camel_spawn_egg
execute at @s[scores={random=10}] run give @s cat_spawn_egg
execute at @s[scores={random=11}] run give @s cave_spider_spawn_egg
execute at @s[scores={random=12}] run give @s chicken_spawn_egg
execute at @s[scores={random=13}] run give @s cod_spawn_egg
execute at @s[scores={random=14}] run give @s cow_spawn_egg
execute at @s[scores={random=15}] run give @s dolphin_spawn_egg
execute at @s[scores={random=16}] run give @s donkey_spawn_egg
execute at @s[scores={random=17}] run give @s drowned_spawn_egg
execute at @s[scores={random=18}] run give @s elder_guardian_spawn_egg
execute at @s[scores={random=19}] run give @s ender_dragon_spawn_egg
execute at @s[scores={random=20}] run give @s enderman_spawn_egg
execute at @s[scores={random=21}] run give @s endermite_spawn_egg
execute at @s[scores={random=22}] run give @s evoker_spawn_egg
execute at @s[scores={random=23}] run give @s fox_spawn_egg
execute at @s[scores={random=24}] run give @s frog_spawn_egg
execute at @s[scores={random=25}] run give @s ghast_spawn_egg
execute at @s[scores={random=26}] run give @s glow_squid_spawn_egg
execute at @s[scores={random=27}] run give @s goat_spawn_egg
execute at @s[scores={random=28}] run give @s guardian_spawn_egg
execute at @s[scores={random=29}] run give @s hoglin_spawn_egg
execute at @s[scores={random=30}] run give @s horse_spawn_egg
execute at @s[scores={random=31}] run give @s husk_spawn_egg
execute at @s[scores={random=32}] run give @s iron_golem_spawn_egg
execute at @s[scores={random=33}] run give @s llama_spawn_egg
execute at @s[scores={random=34}] run give @s magma_cube_spawn_egg
execute at @s[scores={random=35}] run give @s mooshroom_spawn_egg
execute at @s[scores={random=36}] run give @s ocelot_spawn_egg
execute at @s[scores={random=37}] run give @s mule_spawn_egg
execute at @s[scores={random=38}] run give @s pufferfish_spawn_egg
execute at @s[scores={random=39}] run give @s polar_bear_spawn_egg
execute at @s[scores={random=40}] run give @s pillager_spawn_egg
execute at @s[scores={random=41}] run give @s piglin_spawn_egg
execute at @s[scores={random=42}] run give @s piglin_brute_spawn_egg
execute at @s[scores={random=43}] run give @s pig_spawn_egg
execute at @s[scores={random=44}] run give @s phantom_spawn_egg
execute at @s[scores={random=45}] run give @s parrot_spawn_egg
execute at @s[scores={random=46}] run give @s panda_spawn_egg
execute at @s[scores={random=47}] run give @s ravager_spawn_egg
execute at @s[scores={random=48}] run give @s rabbit_spawn_egg
execute at @s[scores={random=49}] run give @s strider_spawn_egg
execute at @s[scores={random=50}] run give @s stray_spawn_egg
execute at @s[scores={random=51}] run give @s squid_spawn_egg
execute at @s[scores={random=52}] run give @s spider_spawn_egg
execute at @s[scores={random=53}] run give @s snow_golem_spawn_egg
execute at @s[scores={random=54}] run give @s sniffer_spawn_egg
execute at @s[scores={random=55}] run give @s slime_spawn_egg
execute at @s[scores={random=56}] run give @s skeleton_spawn_egg
execute at @s[scores={random=57}] run give @s skeleton_horse_spawn_egg
execute at @s[scores={random=58}] run give @s silverfish_spawn_egg
execute at @s[scores={random=59}] run give @s shulker_spawn_egg
execute at @s[scores={random=60}] run give @s sheep_spawn_egg
execute at @s[scores={random=61}] run give @s salmon_spawn_egg
execute at @s[scores={random=62}] run give @s turtle_spawn_egg
execute at @s[scores={random=63}] run give @s tropical_fish_spawn_egg
execute at @s[scores={random=64}] run give @s trader_llama_spawn_egg
execute at @s[scores={random=65}] run give @s tadpole_spawn_egg
execute at @s[scores={random=66}] run give @s vindicator_spawn_egg
execute at @s[scores={random=67}] run give @s villager_spawn_egg
execute at @s[scores={random=68}] run give @s vex_spawn_egg
execute at @s[scores={random=69}] run give @s wolf_spawn_egg
execute at @s[scores={random=70}] run give @s wither_spawn_egg
execute at @s[scores={random=71}] run give @s wither_skeleton_spawn_egg
execute at @s[scores={random=72}] run give @s witch_spawn_egg
execute at @s[scores={random=73}] run give @s warden_spawn_egg
execute at @s[scores={random=74}] run give @s wandering_trader_spawn_egg
execute at @s[scores={random=75}] run give @s zombie_villager_spawn_egg
execute at @s[scores={random=76}] run give @s zombie_spawn_egg
execute at @s[scores={random=77}] run give @s zombie_pigman_spawn_egg
execute at @s[scores={random=78}] run give @s zombie_horse_spawn_egg
execute at @s[scores={random=79}] run give @s zoglin_spawn_egg
execute at @s[scores={random=80}] run give @s creaking_spawn_egg
function randomize