function randomize
execute at @s[scores={random=itemnumber}] run give @s acacia_boat
execute at @s[scores={random=itemnumber}] run give @s acacia_button
execute at @s[scores={random=itemnumber}] run give @s acacia_chest_boat
execute at @s[scores={random=itemnumber}] run give @s acacia_door
execute at @s[scores={random=itemnumber}] run give @s acacia_fence
execute at @s[scores={random=itemnumber}] run give @s acacia_fence_gate
execute at @s[scores={random=itemnumber}] run give @s acacia_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s acacia_leaves
execute at @s[scores={random=itemnumber}] run give @s acacia_log
execute at @s[scores={random=itemnumber}] run give @s acacia_planks
execute at @s[scores={random=itemnumber}] run give @s acacia_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s acacia_sapling
execute at @s[scores={random=itemnumber}] run give @s acacia_sign
execute at @s[scores={random=itemnumber}] run give @s acacia_slab
execute at @s[scores={random=itemnumber}] run give @s acacia_stairs
execute at @s[scores={random=itemnumber}] run give @s acacia_trapdoor
execute at @s[scores={random=itemnumber}] run give @s acacia_wood
execute at @s[scores={random=itemnumber}] run give @s activator_rail
execute at @s[scores={random=itemnumber}] run give @s air
execute at @s[scores={random=itemnumber}] run give @s allium
execute at @s[scores={random=itemnumber}] run give @s amethyst_block
execute at @s[scores={random=itemnumber}] run give @s amethyst_cluster
execute at @s[scores={random=itemnumber}] run give @s amethyst_shard
execute at @s[scores={random=itemnumber}] run give @s ancient_debris
execute at @s[scores={random=itemnumber}] run give @s andesite
execute at @s[scores={random=itemnumber}] run give @s andesite_stairs
execute at @s[scores={random=itemnumber}] run give @s angler_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s anvil
execute at @s[scores={random=itemnumber}] run give @s apple
execute at @s[scores={random=itemnumber}] run give @s archer_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s armadillo_scute
execute at @s[scores={random=itemnumber}] run give @s armor_stand
execute at @s[scores={random=itemnumber}] run give @s arms_up_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s arrow
execute at @s[scores={random=itemnumber}] run give @s axolotl_bucket
execute at @s[scores={random=itemnumber}] run give @s azalea
execute at @s[scores={random=itemnumber}] run give @s azalea_leaves
execute at @s[scores={random=itemnumber}] run give @s azalea_leaves_flowered
execute at @s[scores={random=itemnumber}] run give @s azure_bluet
execute at @s[scores={random=itemnumber}] run give @s baked_potato
execute at @s[scores={random=itemnumber}] run give @s bamboo
execute at @s[scores={random=itemnumber}] run give @s bamboo_block
execute at @s[scores={random=itemnumber}] run give @s bamboo_button
execute at @s[scores={random=itemnumber}] run give @s bamboo_chest_raft
execute at @s[scores={random=itemnumber}] run give @s bamboo_door
execute at @s[scores={random=itemnumber}] run give @s bamboo_fence
execute at @s[scores={random=itemnumber}] run give @s bamboo_fence_gate
execute at @s[scores={random=itemnumber}] run give @s bamboo_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s bamboo_mosaic
execute at @s[scores={random=itemnumber}] run give @s bamboo_mosaic_slab
execute at @s[scores={random=itemnumber}] run give @s bamboo_mosaic_stairs
execute at @s[scores={random=itemnumber}] run give @s bamboo_planks
execute at @s[scores={random=itemnumber}] run give @s bamboo_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s bamboo_raft
execute at @s[scores={random=itemnumber}] run give @s bamboo_sign
execute at @s[scores={random=itemnumber}] run give @s bamboo_slab
execute at @s[scores={random=itemnumber}] run give @s bamboo_stairs
execute at @s[scores={random=itemnumber}] run give @s bamboo_trapdoor
execute at @s[scores={random=itemnumber}] run give @s banner
execute at @s[scores={random=itemnumber}] run give @s barrel
execute at @s[scores={random=itemnumber}] run give @s basalt
execute at @s[scores={random=itemnumber}] run give @s beacon
execute at @s[scores={random=itemnumber}] run give @s bed
execute at @s[scores={random=itemnumber}] run give @s bee_nest
execute at @s[scores={random=itemnumber}] run give @s beef
execute at @s[scores={random=itemnumber}] run give @s beehive
execute at @s[scores={random=itemnumber}] run give @s beetroot
execute at @s[scores={random=itemnumber}] run give @s beetroot_seeds
execute at @s[scores={random=itemnumber}] run give @s beetroot_soup
execute at @s[scores={random=itemnumber}] run give @s bell
execute at @s[scores={random=itemnumber}] run give @s big_dripleaf
execute at @s[scores={random=itemnumber}] run give @s birch_boat
execute at @s[scores={random=itemnumber}] run give @s birch_button
execute at @s[scores={random=itemnumber}] run give @s birch_chest_boat
execute at @s[scores={random=itemnumber}] run give @s birch_door
execute at @s[scores={random=itemnumber}] run give @s birch_fence
execute at @s[scores={random=itemnumber}] run give @s birch_fence_gate
execute at @s[scores={random=itemnumber}] run give @s birch_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s birch_leaves
execute at @s[scores={random=itemnumber}] run give @s birch_log
execute at @s[scores={random=itemnumber}] run give @s birch_planks
execute at @s[scores={random=itemnumber}] run give @s birch_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s birch_sapling
execute at @s[scores={random=itemnumber}] run give @s birch_sign
execute at @s[scores={random=itemnumber}] run give @s birch_slab
execute at @s[scores={random=itemnumber}] run give @s birch_stairs
execute at @s[scores={random=itemnumber}] run give @s birch_trapdoor
execute at @s[scores={random=itemnumber}] run give @s birch_wood
execute at @s[scores={random=itemnumber}] run give @s black_candle
execute at @s[scores={random=itemnumber}] run give @s black_carpet
execute at @s[scores={random=itemnumber}] run give @s black_concrete
execute at @s[scores={random=itemnumber}] run give @s black_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s black_dye
execute at @s[scores={random=itemnumber}] run give @s black_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s black_shulker_box
execute at @s[scores={random=itemnumber}] run give @s black_stained_glass
execute at @s[scores={random=itemnumber}] run give @s black_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s black_terracotta
execute at @s[scores={random=itemnumber}] run give @s black_wool
execute at @s[scores={random=itemnumber}] run give @s blackstone
execute at @s[scores={random=itemnumber}] run give @s blackstone_slab
execute at @s[scores={random=itemnumber}] run give @s blackstone_stairs
execute at @s[scores={random=itemnumber}] run give @s blackstone_wall
execute at @s[scores={random=itemnumber}] run give @s blade_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s blast_furnace
execute at @s[scores={random=itemnumber}] run give @s blaze_powder
execute at @s[scores={random=itemnumber}] run give @s blaze_rod
execute at @s[scores={random=itemnumber}] run give @s blue_candle
execute at @s[scores={random=itemnumber}] run give @s blue_carpet
execute at @s[scores={random=itemnumber}] run give @s blue_concrete
execute at @s[scores={random=itemnumber}] run give @s blue_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s blue_dye
execute at @s[scores={random=itemnumber}] run give @s blue_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s blue_ice
execute at @s[scores={random=itemnumber}] run give @s blue_orchid
execute at @s[scores={random=itemnumber}] run give @s blue_shulker_box
execute at @s[scores={random=itemnumber}] run give @s blue_stained_glass
execute at @s[scores={random=itemnumber}] run give @s blue_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s blue_terracotta
execute at @s[scores={random=itemnumber}] run give @s blue_wool
execute at @s[scores={random=itemnumber}] run give @s bolt_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s bone
execute at @s[scores={random=itemnumber}] run give @s bone_block
execute at @s[scores={random=itemnumber}] run give @s bone_meal
execute at @s[scores={random=itemnumber}] run give @s book
execute at @s[scores={random=itemnumber}] run give @s bookshelf
execute at @s[scores={random=itemnumber}] run give @s bordure_indented_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s bow
execute at @s[scores={random=itemnumber}] run give @s bowl
execute at @s[scores={random=itemnumber}] run give @s brain_coral
execute at @s[scores={random=itemnumber}] run give @s brain_coral_block
execute at @s[scores={random=itemnumber}] run give @s brain_coral_fan
execute at @s[scores={random=itemnumber}] run give @s bread
execute at @s[scores={random=itemnumber}] run give @s breeze_rod
execute at @s[scores={random=itemnumber}] run give @s brewer_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s brewing_stand
execute at @s[scores={random=itemnumber}] run give @s brick
execute at @s[scores={random=itemnumber}] run give @s brick_block
execute at @s[scores={random=itemnumber}] run give @s brick_slab
execute at @s[scores={random=itemnumber}] run give @s brick_stairs
execute at @s[scores={random=itemnumber}] run give @s brown_candle
execute at @s[scores={random=itemnumber}] run give @s brown_carpet
execute at @s[scores={random=itemnumber}] run give @s brown_concrete
execute at @s[scores={random=itemnumber}] run give @s brown_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s brown_dye
execute at @s[scores={random=itemnumber}] run give @s brown_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s brown_mushroom
execute at @s[scores={random=itemnumber}] run give @s brown_mushroom_block
execute at @s[scores={random=itemnumber}] run give @s brown_shulker_box
execute at @s[scores={random=itemnumber}] run give @s brown_stained_glass
execute at @s[scores={random=itemnumber}] run give @s brown_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s brown_terracotta
execute at @s[scores={random=itemnumber}] run give @s brown_wool
execute at @s[scores={random=itemnumber}] run give @s brush
execute at @s[scores={random=itemnumber}] run give @s bubble_coral
execute at @s[scores={random=itemnumber}] run give @s bubble_coral_block
execute at @s[scores={random=itemnumber}] run give @s bubble_coral_fan
execute at @s[scores={random=itemnumber}] run give @s bucket
execute at @s[scores={random=itemnumber}] run give @s budding_amethyst
execute at @s[scores={random=itemnumber}] run give @s burn_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s cactus
execute at @s[scores={random=itemnumber}] run give @s cake
execute at @s[scores={random=itemnumber}] run give @s calcite
execute at @s[scores={random=itemnumber}] run give @s calibrated_sculk_sensor
execute at @s[scores={random=itemnumber}] run give @s campfire
execute at @s[scores={random=itemnumber}] run give @s candle
execute at @s[scores={random=itemnumber}] run give @s carrot
execute at @s[scores={random=itemnumber}] run give @s carrot_on_a_stick
execute at @s[scores={random=itemnumber}] run give @s cartography_table
execute at @s[scores={random=itemnumber}] run give @s carved_pumpkin
execute at @s[scores={random=itemnumber}] run give @s cauldron
execute at @s[scores={random=itemnumber}] run give @s chain
execute at @s[scores={random=itemnumber}] run give @s chainmail_boots
execute at @s[scores={random=itemnumber}] run give @s chainmail_chestplate
execute at @s[scores={random=itemnumber}] run give @s chainmail_helmet
execute at @s[scores={random=itemnumber}] run give @s chainmail_leggings
execute at @s[scores={random=itemnumber}] run give @s charcoal
execute at @s[scores={random=itemnumber}] run give @s cherry_boat
execute at @s[scores={random=itemnumber}] run give @s cherry_button
execute at @s[scores={random=itemnumber}] run give @s cherry_chest_boat
execute at @s[scores={random=itemnumber}] run give @s cherry_door
execute at @s[scores={random=itemnumber}] run give @s cherry_fence
execute at @s[scores={random=itemnumber}] run give @s cherry_fence_gate
execute at @s[scores={random=itemnumber}] run give @s cherry_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s cherry_leaves
execute at @s[scores={random=itemnumber}] run give @s cherry_log
execute at @s[scores={random=itemnumber}] run give @s cherry_planks
execute at @s[scores={random=itemnumber}] run give @s cherry_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s cherry_sapling
execute at @s[scores={random=itemnumber}] run give @s cherry_sign
execute at @s[scores={random=itemnumber}] run give @s cherry_slab
execute at @s[scores={random=itemnumber}] run give @s cherry_stairs
execute at @s[scores={random=itemnumber}] run give @s cherry_trapdoor
execute at @s[scores={random=itemnumber}] run give @s cherry_wood
execute at @s[scores={random=itemnumber}] run give @s chest
execute at @s[scores={random=itemnumber}] run give @s chest_minecart
execute at @s[scores={random=itemnumber}] run give @s chicken
execute at @s[scores={random=itemnumber}] run give @s chiseled_bookshelf
execute at @s[scores={random=itemnumber}] run give @s chiseled_deepslate
execute at @s[scores={random=itemnumber}] run give @s chiseled_nether_bricks
execute at @s[scores={random=itemnumber}] run give @s chiseled_polished_blackstone
execute at @s[scores={random=itemnumber}] run give @s chiseled_tuff
execute at @s[scores={random=itemnumber}] run give @s chiseled_tuff_bricks
execute at @s[scores={random=itemnumber}] run give @s chorus_flower
execute at @s[scores={random=itemnumber}] run give @s chorus_fruit
execute at @s[scores={random=itemnumber}] run give @s chorus_plant
execute at @s[scores={random=itemnumber}] run give @s clay
execute at @s[scores={random=itemnumber}] run give @s clay_ball
execute at @s[scores={random=itemnumber}] run give @s clock
execute at @s[scores={random=itemnumber}] run give @s coal
execute at @s[scores={random=itemnumber}] run give @s coal_block
execute at @s[scores={random=itemnumber}] run give @s coal_ore
execute at @s[scores={random=itemnumber}] run give @s coast_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s cobbled_deepslate
execute at @s[scores={random=itemnumber}] run give @s cobbled_deepslate_slab
execute at @s[scores={random=itemnumber}] run give @s cobbled_deepslate_stairs
execute at @s[scores={random=itemnumber}] run give @s cobbled_deepslate_wall
execute at @s[scores={random=itemnumber}] run give @s cobblestone
execute at @s[scores={random=itemnumber}] run give @s cobblestone_slab
execute at @s[scores={random=itemnumber}] run give @s cobblestone_wall
execute at @s[scores={random=itemnumber}] run give @s cocoa_beans
execute at @s[scores={random=itemnumber}] run give @s cod
execute at @s[scores={random=itemnumber}] run give @s cod_bucket
execute at @s[scores={random=itemnumber}] run give @s comparator
execute at @s[scores={random=itemnumber}] run give @s compass
execute at @s[scores={random=itemnumber}] run give @s composter
execute at @s[scores={random=itemnumber}] run give @s conduit
execute at @s[scores={random=itemnumber}] run give @s cooked_beef
execute at @s[scores={random=itemnumber}] run give @s cooked_chicken
execute at @s[scores={random=itemnumber}] run give @s cooked_cod
execute at @s[scores={random=itemnumber}] run give @s cooked_mutton
execute at @s[scores={random=itemnumber}] run give @s cooked_porkchop
execute at @s[scores={random=itemnumber}] run give @s cooked_rabbit
execute at @s[scores={random=itemnumber}] run give @s cooked_salmon
execute at @s[scores={random=itemnumber}] run give @s cookie
execute at @s[scores={random=itemnumber}] run give @s copper_ingot
execute at @s[scores={random=itemnumber}] run give @s copper_ore
execute at @s[scores={random=itemnumber}] run give @s crafting_table
execute at @s[scores={random=itemnumber}] run give @s cornflower
execute at @s[scores={random=itemnumber}] run give @s cracked_deepslate_bricks
execute at @s[scores={random=itemnumber}] run give @s cracked_deepslate_tiles
execute at @s[scores={random=itemnumber}] run give @s cracked_nether_bricks
execute at @s[scores={random=itemnumber}] run give @s cracked_polished_blackstone_bricks
execute at @s[scores={random=itemnumber}] run give @s crafter
execute at @s[scores={random=itemnumber}] run give @s danger_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s dark_oak_boat
execute at @s[scores={random=itemnumber}] run give @s dark_oak_button
execute at @s[scores={random=itemnumber}] run give @s dark_oak_chest_boat
execute at @s[scores={random=itemnumber}] run give @s dark_oak_door
execute at @s[scores={random=itemnumber}] run give @s dark_oak_fence
execute at @s[scores={random=itemnumber}] run give @s dark_oak_fence_gate
execute at @s[scores={random=itemnumber}] run give @s dark_oak_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s dark_oak_leaves
execute at @s[scores={random=itemnumber}] run give @s dark_oak_log
execute at @s[scores={random=itemnumber}] run give @s dark_oak_planks
execute at @s[scores={random=itemnumber}] run give @s dark_oak_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s dark_oak_sapling
execute at @s[scores={random=itemnumber}] run give @s dark_oak_sign
execute at @s[scores={random=itemnumber}] run give @s dark_oak_slab
execute at @s[scores={random=itemnumber}] run give @s dark_oak_stairs
execute at @s[scores={random=itemnumber}] run give @s dark_oak_trapdoor
execute at @s[scores={random=itemnumber}] run give @s dark_oak_wood
execute at @s[scores={random=itemnumber}] run give @s dark_prismarine_stairs
execute at @s[scores={random=itemnumber}] run give @s daylight_detector
execute at @s[scores={random=itemnumber}] run give @s dead_brain_coral
execute at @s[scores={random=itemnumber}] run give @s dead_brain_coral_block
execute at @s[scores={random=itemnumber}] run give @s dead_brain_coral_fan
execute at @s[scores={random=itemnumber}] run give @s dead_bubble_coral
execute at @s[scores={random=itemnumber}] run give @s dead_bubble_coral_block
execute at @s[scores={random=itemnumber}] run give @s dead_bubble_coral_fan
execute at @s[scores={random=itemnumber}] run give @s dead_fire_coral
execute at @s[scores={random=itemnumber}] run give @s dead_fire_coral_block
execute at @s[scores={random=itemnumber}] run give @s dead_fire_coral_fan
execute at @s[scores={random=itemnumber}] run give @s dead_horn_coral
execute at @s[scores={random=itemnumber}] run give @s dead_horn_coral_block
execute at @s[scores={random=itemnumber}] run give @s dead_horn_coral_fan
execute at @s[scores={random=itemnumber}] run give @s dead_tube_coral
execute at @s[scores={random=itemnumber}] run give @s dead_tube_coral_block
execute at @s[scores={random=itemnumber}] run give @s dead_tube_coral_fan
execute at @s[scores={random=itemnumber}] run give @s deadbush
execute at @s[scores={random=itemnumber}] run give @s decorated_pot
execute at @s[scores={random=itemnumber}] run give @s deepslate
execute at @s[scores={random=itemnumber}] run give @s deepslate_brick_slab
execute at @s[scores={random=itemnumber}] run give @s deepslate_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s deepslate_brick_wall
execute at @s[scores={random=itemnumber}] run give @s deepslate_bricks
execute at @s[scores={random=itemnumber}] run give @s deepslate_coal_ore
execute at @s[scores={random=itemnumber}] run give @s deepslate_copper_ore
execute at @s[scores={random=itemnumber}] run give @s deepslate_diamond_ore
execute at @s[scores={random=itemnumber}] run give @s deepslate_emerald_ore
execute at @s[scores={random=itemnumber}] run give @s deepslate_gold_ore
execute at @s[scores={random=itemnumber}] run give @s deepslate_iron_ore
execute at @s[scores={random=itemnumber}] run give @s deepslate_lapis_ore
execute at @s[scores={random=itemnumber}] run give @s deepslate_redstone_ore
execute at @s[scores={random=itemnumber}] run give @s deepslate_tile_slab
execute at @s[scores={random=itemnumber}] run give @s deepslate_tile_stairs
execute at @s[scores={random=itemnumber}] run give @s deepslate_tile_wall
execute at @s[scores={random=itemnumber}] run give @s deepslate_tiles
execute at @s[scores={random=itemnumber}] run give @s detector_rail
execute at @s[scores={random=itemnumber}] run give @s diamond
execute at @s[scores={random=itemnumber}] run give @s diamond_axe
execute at @s[scores={random=itemnumber}] run give @s diamond_block
execute at @s[scores={random=itemnumber}] run give @s diamond_boots
execute at @s[scores={random=itemnumber}] run give @s diamond_chestplate
execute at @s[scores={random=itemnumber}] run give @s diamond_helmet
execute at @s[scores={random=itemnumber}] run give @s diamond_hoe
execute at @s[scores={random=itemnumber}] run give @s diamond_horse_armor
execute at @s[scores={random=itemnumber}] run give @s diamond_leggings
execute at @s[scores={random=itemnumber}] run give @s diamond_ore
execute at @s[scores={random=itemnumber}] run give @s diamond_pickaxe
execute at @s[scores={random=itemnumber}] run give @s diamond_shovel
execute at @s[scores={random=itemnumber}] run give @s diamond_sword
execute at @s[scores={random=itemnumber}] run give @s diorite
execute at @s[scores={random=itemnumber}] run give @s diorite_stairs
execute at @s[scores={random=itemnumber}] run give @s dirt
execute at @s[scores={random=itemnumber}] run give @s dirt_with_roots
execute at @s[scores={random=itemnumber}] run give @s disc_fragment_5
execute at @s[scores={random=itemnumber}] run give @s dispenser
execute at @s[scores={random=itemnumber}] run give @s dragon_breath
execute at @s[scores={random=itemnumber}] run give @s dragon_egg
execute at @s[scores={random=itemnumber}] run give @s dried_kelp
execute at @s[scores={random=itemnumber}] run give @s dried_kelp_block
execute at @s[scores={random=itemnumber}] run give @s dripstone_block
execute at @s[scores={random=itemnumber}] run give @s dropper
execute at @s[scores={random=itemnumber}] run give @s dune_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s echo_shard
execute at @s[scores={random=itemnumber}] run give @s egg
execute at @s[scores={random=itemnumber}] run give @s elytra
execute at @s[scores={random=itemnumber}] run give @s emerald
execute at @s[scores={random=itemnumber}] run give @s emerald_block
execute at @s[scores={random=itemnumber}] run give @s emerald_ore
execute at @s[scores={random=itemnumber}] run give @s empty_map
execute at @s[scores={random=itemnumber}] run give @s enchanted_golden_apple
execute at @s[scores={random=itemnumber}] run give @s enchanting_table
execute at @s[scores={random=itemnumber}] run give @s end_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s end_bricks
execute at @s[scores={random=itemnumber}] run give @s end_crystal
execute at @s[scores={random=itemnumber}] run give @s end_portal_frame
execute at @s[scores={random=itemnumber}] run give @s end_rod
execute at @s[scores={random=itemnumber}] run give @s end_stone
execute at @s[scores={random=itemnumber}] run give @s ender_chest
execute at @s[scores={random=itemnumber}] run give @s ender_eye
execute at @s[scores={random=itemnumber}] run give @s ender_pearl
execute at @s[scores={random=itemnumber}] run give @s experience_bottle
execute at @s[scores={random=itemnumber}] run give @s explorer_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s eye_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s farmland
execute at @s[scores={random=itemnumber}] run give @s feather
execute at @s[scores={random=itemnumber}] run give @s fence
execute at @s[scores={random=itemnumber}] run give @s fence_gate
execute at @s[scores={random=itemnumber}] run give @s fermented_spider_eye
execute at @s[scores={random=itemnumber}] run give @s fern
execute at @s[scores={random=itemnumber}] run give @s field_masoned_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s filled_map
execute at @s[scores={random=itemnumber}] run give @s fire_charge
execute at @s[scores={random=itemnumber}] run give @s fire_coral
execute at @s[scores={random=itemnumber}] run give @s fire_coral_block
execute at @s[scores={random=itemnumber}] run give @s firework_rocket
execute at @s[scores={random=itemnumber}] run give @s firework_star
execute at @s[scores={random=itemnumber}] run give @s fishing_rod
execute at @s[scores={random=itemnumber}] run give @s fletching_table
execute at @s[scores={random=itemnumber}] run give @s flint
execute at @s[scores={random=itemnumber}] run give @s flint_and_steel
execute at @s[scores={random=itemnumber}] run give @s flow_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s flow_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s flow_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s flower_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s flower_pot
execute at @s[scores={random=itemnumber}] run give @s flowering_azalea
execute at @s[scores={random=itemnumber}] run give @s frame
execute at @s[scores={random=itemnumber}] run give @s friend_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s frog_spawn
execute at @s[scores={random=itemnumber}] run give @s frosted_ice
execute at @s[scores={random=itemnumber}] run give @s furnace
execute at @s[scores={random=itemnumber}] run give @s ghast_tear
execute at @s[scores={random=itemnumber}] run give @s gilded_blackstone
execute at @s[scores={random=itemnumber}] run give @s glass
execute at @s[scores={random=itemnumber}] run give @s glass_bottle
execute at @s[scores={random=itemnumber}] run give @s glass_pane
execute at @s[scores={random=itemnumber}] run give @s glistering_melon_slice
execute at @s[scores={random=itemnumber}] run give @s globe_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s glow_frame
execute at @s[scores={random=itemnumber}] run give @s glow_ink_sac
execute at @s[scores={random=itemnumber}] run give @s glow_lichen
execute at @s[scores={random=itemnumber}] run give @s glowstone
execute at @s[scores={random=itemnumber}] run give @s glowstone_dust
execute at @s[scores={random=itemnumber}] run give @s gold_block
execute at @s[scores={random=itemnumber}] run give @s gold_ingot
execute at @s[scores={random=itemnumber}] run give @s gold_nugget
execute at @s[scores={random=itemnumber}] run give @s gold_ore
execute at @s[scores={random=itemnumber}] run give @s golden_apple
execute at @s[scores={random=itemnumber}] run give @s golden_axe
execute at @s[scores={random=itemnumber}] run give @s golden_boots
execute at @s[scores={random=itemnumber}] run give @s golden_carrot
execute at @s[scores={random=itemnumber}] run give @s golden_chestplate
execute at @s[scores={random=itemnumber}] run give @s golden_helmet
execute at @s[scores={random=itemnumber}] run give @s golden_hoe
execute at @s[scores={random=itemnumber}] run give @s golden_horse_armor
execute at @s[scores={random=itemnumber}] run give @s golden_leggings
execute at @s[scores={random=itemnumber}] run give @s golden_pickaxe
execute at @s[scores={random=itemnumber}] run give @s golden_rail
execute at @s[scores={random=itemnumber}] run give @s golden_shovel
execute at @s[scores={random=itemnumber}] run give @s golden_sword
execute at @s[scores={random=itemnumber}] run give @s granite
execute at @s[scores={random=itemnumber}] run give @s granite_stairs
execute at @s[scores={random=itemnumber}] run give @s grass_block
execute at @s[scores={random=itemnumber}] run give @s grass_path
execute at @s[scores={random=itemnumber}] run give @s gravel
execute at @s[scores={random=itemnumber}] run give @s gray_candle
execute at @s[scores={random=itemnumber}] run give @s glow_berries
execute at @s[scores={random=itemnumber}] run give @s gray_carpet
execute at @s[scores={random=itemnumber}] run give @s gray_concrete
execute at @s[scores={random=itemnumber}] run give @s gray_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s gray_dye
execute at @s[scores={random=itemnumber}] run give @s gray_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s gray_shulker_box
execute at @s[scores={random=itemnumber}] run give @s gray_stained_glass
execute at @s[scores={random=itemnumber}] run give @s gray_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s gray_terracotta
execute at @s[scores={random=itemnumber}] run give @s gray_wool
execute at @s[scores={random=itemnumber}] run give @s green_candle
execute at @s[scores={random=itemnumber}] run give @s green_carpet
execute at @s[scores={random=itemnumber}] run give @s green_concrete
execute at @s[scores={random=itemnumber}] run give @s green_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s green_dye
execute at @s[scores={random=itemnumber}] run give @s green_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s green_shulker_box
execute at @s[scores={random=itemnumber}] run give @s green_stained_glass
execute at @s[scores={random=itemnumber}] run give @s green_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s green_terracotta
execute at @s[scores={random=itemnumber}] run give @s green_wool
execute at @s[scores={random=itemnumber}] run give @s grindstone
execute at @s[scores={random=itemnumber}] run give @s gunpowder
execute at @s[scores={random=itemnumber}] run give @s guster_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s guster_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s hanging_roots
execute at @s[scores={random=itemnumber}] run give @s hardened_clay
execute at @s[scores={random=itemnumber}] run give @s hay_block
execute at @s[scores={random=itemnumber}] run give @s heart_of_the_sea
execute at @s[scores={random=itemnumber}] run give @s heart_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s heartbreak_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s heavy_core
execute at @s[scores={random=itemnumber}] run give @s heavy_weighted_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s honey_block
execute at @s[scores={random=itemnumber}] run give @s honey_bottle
execute at @s[scores={random=itemnumber}] run give @s honeycomb
execute at @s[scores={random=itemnumber}] run give @s honeycomb_block
execute at @s[scores={random=itemnumber}] run give @s hopper
execute at @s[scores={random=itemnumber}] run give @s hopper_minecart
execute at @s[scores={random=itemnumber}] run give @s horn_coral
execute at @s[scores={random=itemnumber}] run give @s horn_coral_block
execute at @s[scores={random=itemnumber}] run give @s horn_coral_fan
execute at @s[scores={random=itemnumber}] run give @s host_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s howl_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s ice
execute at @s[scores={random=itemnumber}] run give @s infested_deepslate
execute at @s[scores={random=itemnumber}] run give @s ink_sac
execute at @s[scores={random=itemnumber}] run give @s iron_axe
execute at @s[scores={random=itemnumber}] run give @s iron_bars
execute at @s[scores={random=itemnumber}] run give @s iron_block
execute at @s[scores={random=itemnumber}] run give @s iron_boots
execute at @s[scores={random=itemnumber}] run give @s iron_chestplate
execute at @s[scores={random=itemnumber}] run give @s iron_door
execute at @s[scores={random=itemnumber}] run give @s iron_helmet
execute at @s[scores={random=itemnumber}] run give @s iron_hoe
execute at @s[scores={random=itemnumber}] run give @s iron_horse_armor
execute at @s[scores={random=itemnumber}] run give @s iron_ingot
execute at @s[scores={random=itemnumber}] run give @s iron_leggings
execute at @s[scores={random=itemnumber}] run give @s iron_nugget
execute at @s[scores={random=itemnumber}] run give @s iron_ore
execute at @s[scores={random=itemnumber}] run give @s iron_pickaxe
execute at @s[scores={random=itemnumber}] run give @s iron_shovel
execute at @s[scores={random=itemnumber}] run give @s iron_sword
execute at @s[scores={random=itemnumber}] run give @s iron_trapdoor
execute at @s[scores={random=itemnumber}] run give @s jukebox
execute at @s[scores={random=itemnumber}] run give @s jungle_boat
execute at @s[scores={random=itemnumber}] run give @s jungle_button
execute at @s[scores={random=itemnumber}] run give @s jungle_chest_boat
execute at @s[scores={random=itemnumber}] run give @s jungle_door
execute at @s[scores={random=itemnumber}] run give @s jungle_fence
execute at @s[scores={random=itemnumber}] run give @s jungle_fence_gate
execute at @s[scores={random=itemnumber}] run give @s jungle_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s jungle_leaves
execute at @s[scores={random=itemnumber}] run give @s jungle_log
execute at @s[scores={random=itemnumber}] run give @s jungle_planks
execute at @s[scores={random=itemnumber}] run give @s jungle_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s jungle_sapling
execute at @s[scores={random=itemnumber}] run give @s jungle_sign
execute at @s[scores={random=itemnumber}] run give @s jungle_slab
execute at @s[scores={random=itemnumber}] run give @s jungle_stairs
execute at @s[scores={random=itemnumber}] run give @s jungle_trapdoor
execute at @s[scores={random=itemnumber}] run give @s jungle_wood
execute at @s[scores={random=itemnumber}] run give @s kelp
execute at @s[scores={random=itemnumber}] run give @s ladder
execute at @s[scores={random=itemnumber}] run give @s lantern
execute at @s[scores={random=itemnumber}] run give @s lapis_block
execute at @s[scores={random=itemnumber}] run give @s lapis_lazuli
execute at @s[scores={random=itemnumber}] run give @s lapis_ore
execute at @s[scores={random=itemnumber}] run give @s large_amethyst_bud
execute at @s[scores={random=itemnumber}] run give @s large_fern
execute at @s[scores={random=itemnumber}] run give @s lever
execute at @s[scores={random=itemnumber}] run give @s lava_bucket
execute at @s[scores={random=itemnumber}] run give @s lead
execute at @s[scores={random=itemnumber}] run give @s leather
execute at @s[scores={random=itemnumber}] run give @s leather_boots
execute at @s[scores={random=itemnumber}] run give @s leather_chestplate
execute at @s[scores={random=itemnumber}] run give @s leather_helmet
execute at @s[scores={random=itemnumber}] run give @s leather_horse_armor
execute at @s[scores={random=itemnumber}] run give @s leather_leggings
execute at @s[scores={random=itemnumber}] run give @s light_blue_candle
execute at @s[scores={random=itemnumber}] run give @s lectern
execute at @s[scores={random=itemnumber}] run give @s light_blue_carpet
execute at @s[scores={random=itemnumber}] run give @s light_blue_concrete
execute at @s[scores={random=itemnumber}] run give @s light_blue_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s light_blue_dye
execute at @s[scores={random=itemnumber}] run give @s light_blue_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s light_blue_shulker_box
execute at @s[scores={random=itemnumber}] run give @s light_blue_stained_glass
execute at @s[scores={random=itemnumber}] run give @s light_blue_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s light_blue_terracotta
execute at @s[scores={random=itemnumber}] run give @s light_blue_wool
execute at @s[scores={random=itemnumber}] run give @s light_gray_candle
execute at @s[scores={random=itemnumber}] run give @s light_gray_carpet
execute at @s[scores={random=itemnumber}] run give @s light_gray_concrete
execute at @s[scores={random=itemnumber}] run give @s light_gray_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s light_gray_dye
execute at @s[scores={random=itemnumber}] run give @s light_gray_shulker_box
execute at @s[scores={random=itemnumber}] run give @s light_gray_stained_glass
execute at @s[scores={random=itemnumber}] run give @s light_gray_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s light_gray_terracotta
execute at @s[scores={random=itemnumber}] run give @s light_gray_wool
execute at @s[scores={random=itemnumber}] run give @s light_weighted_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s lightning_rod
execute at @s[scores={random=itemnumber}] run give @s lilac
execute at @s[scores={random=itemnumber}] run give @s lily_of_the_valley
execute at @s[scores={random=itemnumber}] run give @s lime_candle
execute at @s[scores={random=itemnumber}] run give @s lime_carpet
execute at @s[scores={random=itemnumber}] run give @s lime_concrete
execute at @s[scores={random=itemnumber}] run give @s lime_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s lime_dye
execute at @s[scores={random=itemnumber}] run give @s lime_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s lime_shulker_box
execute at @s[scores={random=itemnumber}] run give @s lime_stained_glass
execute at @s[scores={random=itemnumber}] run give @s lime_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s lime_terracotta
execute at @s[scores={random=itemnumber}] run give @s lime_wool
execute at @s[scores={random=itemnumber}] run give @s lingering_potion
execute at @s[scores={random=itemnumber}] run give @s lit_pumpkin
execute at @s[scores={random=itemnumber}] run give @s lodestone
execute at @s[scores={random=itemnumber}] run give @s lodestone_compass
execute at @s[scores={random=itemnumber}] run give @s loom
execute at @s[scores={random=itemnumber}] run give @s mace
execute at @s[scores={random=itemnumber}] run give @s magenta_candle
execute at @s[scores={random=itemnumber}] run give @s magenta_carpet
execute at @s[scores={random=itemnumber}] run give @s magenta_concrete
execute at @s[scores={random=itemnumber}] run give @s magenta_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s magenta_dye
execute at @s[scores={random=itemnumber}] run give @s magenta_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s magenta_shulker_box
execute at @s[scores={random=itemnumber}] run give @s magenta_stained_glass
execute at @s[scores={random=itemnumber}] run give @s magenta_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s magenta_terracotta
execute at @s[scores={random=itemnumber}] run give @s magenta_wool
execute at @s[scores={random=itemnumber}] run give @s magma
execute at @s[scores={random=itemnumber}] run give @s magma_cream
execute at @s[scores={random=itemnumber}] run give @s mangrove_boat
execute at @s[scores={random=itemnumber}] run give @s mangrove_button
execute at @s[scores={random=itemnumber}] run give @s mangrove_chest_boat
execute at @s[scores={random=itemnumber}] run give @s mangrove_door
execute at @s[scores={random=itemnumber}] run give @s mangrove_fence
execute at @s[scores={random=itemnumber}] run give @s mangrove_fence_gate
execute at @s[scores={random=itemnumber}] run give @s mangrove_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s mangrove_leaves
execute at @s[scores={random=itemnumber}] run give @s mangrove_log
execute at @s[scores={random=itemnumber}] run give @s mangrove_planks
execute at @s[scores={random=itemnumber}] run give @s mangrove_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s mangrove_propagule
execute at @s[scores={random=itemnumber}] run give @s mangrove_roots
execute at @s[scores={random=itemnumber}] run give @s mangrove_sign
execute at @s[scores={random=itemnumber}] run give @s mangrove_slab
execute at @s[scores={random=itemnumber}] run give @s mangrove_stairs
execute at @s[scores={random=itemnumber}] run give @s mangrove_trapdoor
execute at @s[scores={random=itemnumber}] run give @s mangrove_wood
execute at @s[scores={random=itemnumber}] run give @s mycelium
execute at @s[scores={random=itemnumber}] run give @s medium_amethyst_bud
execute at @s[scores={random=itemnumber}] run give @s melon_block
execute at @s[scores={random=itemnumber}] run give @s melon_seeds
execute at @s[scores={random=itemnumber}] run give @s melon_slice
execute at @s[scores={random=itemnumber}] run give @s milk_bucket
execute at @s[scores={random=itemnumber}] run give @s minecart
execute at @s[scores={random=itemnumber}] run give @s mutton
execute at @s[scores={random=itemnumber}] run give @s music_disc_ward
execute at @s[scores={random=itemnumber}] run give @s music_disc_wait
execute at @s[scores={random=itemnumber}] run give @s music_disc_strad
execute at @s[scores={random=itemnumber}] run give @s music_disc_stal
execute at @s[scores={random=itemnumber}] run give @s music_disc_relic
execute at @s[scores={random=itemnumber}] run give @s music_disc_precipice
execute at @s[scores={random=itemnumber}] run give @s music_disc_pigstep
execute at @s[scores={random=itemnumber}] run give @s music_disc_otherside
execute at @s[scores={random=itemnumber}] run give @s music_disc_mellohi
execute at @s[scores={random=itemnumber}] run give @s music_disc_mall
execute at @s[scores={random=itemnumber}] run give @s music_disc_far
execute at @s[scores={random=itemnumber}] run give @s music_disc_creator_music_box
execute at @s[scores={random=itemnumber}] run give @s music_disc_creator
execute at @s[scores={random=itemnumber}] run give @s music_disc_chirp
execute at @s[scores={random=itemnumber}] run give @s music_disc_cat
execute at @s[scores={random=itemnumber}] run give @s music_disc_blocks
execute at @s[scores={random=itemnumber}] run give @s music_disc_5
execute at @s[scores={random=itemnumber}] run give @s music_disc_13
execute at @s[scores={random=itemnumber}] run give @s music_disc_11
execute at @s[scores={random=itemnumber}] run give @s mushroom_stew
execute at @s[scores={random=itemnumber}] run give @s muddy_mangrove_roots
execute at @s[scores={random=itemnumber}] run give @s mud_bricks
execute at @s[scores={random=itemnumber}] run give @s mud_brick_wall
execute at @s[scores={random=itemnumber}] run give @s mud_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s mud_brick_slab
execute at @s[scores={random=itemnumber}] run give @s mud
execute at @s[scores={random=itemnumber}] run give @s mourner_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s mossy_stone_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s mossy_cobblestone_stairs
execute at @s[scores={random=itemnumber}] run give @s mossy_cobblestone
execute at @s[scores={random=itemnumber}] run give @s moss_carpet
execute at @s[scores={random=itemnumber}] run give @s moss_block
execute at @s[scores={random=itemnumber}] run give @s monster_egg
execute at @s[scores={random=itemnumber}] run give @s mojang_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s mob_spawner
execute at @s[scores={random=itemnumber}] run give @s miner_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s noteblock
execute at @s[scores={random=itemnumber}] run give @s normal_stone_stairs
execute at @s[scores={random=itemnumber}] run give @s netherrack
execute at @s[scores={random=itemnumber}] run give @s netherite_upgrade_smithing_template
execute at @s[scores={random=itemnumber}] run give @s netherite_shovel
execute at @s[scores={random=itemnumber}] run give @s netherite_scrap
execute at @s[scores={random=itemnumber}] run give @s netherite_pickaxe
execute at @s[scores={random=itemnumber}] run give @s netherite_leggings
execute at @s[scores={random=itemnumber}] run give @s netherite_ingot
execute at @s[scores={random=itemnumber}] run give @s netherite_hoe
execute at @s[scores={random=itemnumber}] run give @s netherite_helmet
execute at @s[scores={random=itemnumber}] run give @s netherite_chestplate
execute at @s[scores={random=itemnumber}] run give @s netherite_boots
execute at @s[scores={random=itemnumber}] run give @s netherite_block
execute at @s[scores={random=itemnumber}] run give @s netherite_axe
execute at @s[scores={random=itemnumber}] run give @s netherbrick
execute at @s[scores={random=itemnumber}] run give @s nether_wart_block
execute at @s[scores={random=itemnumber}] run give @s nether_wart
execute at @s[scores={random=itemnumber}] run give @s nether_star
execute at @s[scores={random=itemnumber}] run give @s nether_sprouts
execute at @s[scores={random=itemnumber}] run give @s nether_gold_ore
execute at @s[scores={random=itemnumber}] run give @s nether_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s nether_brick_slab
execute at @s[scores={random=itemnumber}] run give @s nether_brick_fence
execute at @s[scores={random=itemnumber}] run give @s nether_brick
execute at @s[scores={random=itemnumber}] run give @s nautilus_shell
execute at @s[scores={random=itemnumber}] run give @s name_tag
execute at @s[scores={random=itemnumber}] run give @s oxeye_daisy
execute at @s[scores={random=itemnumber}] run give @s orange_wool
execute at @s[scores={random=itemnumber}] run give @s orange_tulip
execute at @s[scores={random=itemnumber}] run give @s orange_terracotta
execute at @s[scores={random=itemnumber}] run give @s orange_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s orange_stained_glass
execute at @s[scores={random=itemnumber}] run give @s orange_shulker_box
execute at @s[scores={random=itemnumber}] run give @s orange_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s orange_dye
execute at @s[scores={random=itemnumber}] run give @s orange_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s orange_concrete
execute at @s[scores={random=itemnumber}] run give @s orange_carpet
execute at @s[scores={random=itemnumber}] run give @s orange_candle
execute at @s[scores={random=itemnumber}] run give @s ominous_trial_key
execute at @s[scores={random=itemnumber}] run give @s ominous_bottle
execute at @s[scores={random=itemnumber}] run give @s ochre_froglight
execute at @s[scores={random=itemnumber}] run give @s obsidian
execute at @s[scores={random=itemnumber}] run give @s observer
execute at @s[scores={random=itemnumber}] run give @s oak_wood
execute at @s[scores={random=itemnumber}] run give @s oak_stairs
execute at @s[scores={random=itemnumber}] run give @s oak_slab
execute at @s[scores={random=itemnumber}] run give @s oak_sign
execute at @s[scores={random=itemnumber}] run give @s oak_sapling
execute at @s[scores={random=itemnumber}] run give @s oak_planks
execute at @s[scores={random=itemnumber}] run give @s oak_log
execute at @s[scores={random=itemnumber}] run give @s oak_leaves
execute at @s[scores={random=itemnumber}] run give @s oak_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s oak_fence
execute at @s[scores={random=itemnumber}] run give @s oak_chest_boat
execute at @s[scores={random=itemnumber}] run give @s oak_boat
execute at @s[scores={random=itemnumber}] run give @s purpur_stairs
execute at @s[scores={random=itemnumber}] run give @s purpur_block
execute at @s[scores={random=itemnumber}] run give @s purple_wool
execute at @s[scores={random=itemnumber}] run give @s purple_terracotta
execute at @s[scores={random=itemnumber}] run give @s purple_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s purple_stained_glass
execute at @s[scores={random=itemnumber}] run give @s purple_shulker_box
execute at @s[scores={random=itemnumber}] run give @s purple_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s purple_dye
execute at @s[scores={random=itemnumber}] run give @s purple_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s purple_concrete
execute at @s[scores={random=itemnumber}] run give @s purple_carpet
execute at @s[scores={random=itemnumber}] run give @s purple_candle
execute at @s[scores={random=itemnumber}] run give @s pumpkin_seeds
execute at @s[scores={random=itemnumber}] run give @s pumpkin_pie
execute at @s[scores={random=itemnumber}] run give @s pumpkin
execute at @s[scores={random=itemnumber}] run give @s pufferfish_bucket
execute at @s[scores={random=itemnumber}] run give @s pufferfish
execute at @s[scores={random=itemnumber}] run give @s prize_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s prismarine_stairs
execute at @s[scores={random=itemnumber}] run give @s prismarine_shard
execute at @s[scores={random=itemnumber}] run give @s prismarine_crystals
execute at @s[scores={random=itemnumber}] run give @s prismarine_bricks_stairs
execute at @s[scores={random=itemnumber}] run give @s prismarine
execute at @s[scores={random=itemnumber}] run give @s powder_snow_bucket
execute at @s[scores={random=itemnumber}] run give @s potion
execute at @s[scores={random=itemnumber}] run give @s potato
execute at @s[scores={random=itemnumber}] run give @s porkchop
execute at @s[scores={random=itemnumber}] run give @s poppy
execute at @s[scores={random=itemnumber}] run give @s popped_chorus_fruit
execute at @s[scores={random=itemnumber}] run give @s polished_tuff_wall
execute at @s[scores={random=itemnumber}] run give @s polished_tuff_stairs
execute at @s[scores={random=itemnumber}] run give @s polished_tuff_slab
execute at @s[scores={random=itemnumber}] run give @s polished_tuff
execute at @s[scores={random=itemnumber}] run give @s polished_granite_stairs
execute at @s[scores={random=itemnumber}] run give @s polished_granite
execute at @s[scores={random=itemnumber}] run give @s polished_diorite_stairs
execute at @s[scores={random=itemnumber}] run give @s polished_diorite
execute at @s[scores={random=itemnumber}] run give @s polished_deepslate_wall
execute at @s[scores={random=itemnumber}] run give @s polished_deepslate_stairs
execute at @s[scores={random=itemnumber}] run give @s polished_deepslate_slab
execute at @s[scores={random=itemnumber}] run give @s polished_deepslate
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_wall
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_stairs
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_slab
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_button
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_bricks
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_brick_wall
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone_brick_slab
execute at @s[scores={random=itemnumber}] run give @s polished_blackstone
execute at @s[scores={random=itemnumber}] run give @s polished_basalt
execute at @s[scores={random=itemnumber}] run give @s polished_andesite_stairs
execute at @s[scores={random=itemnumber}] run give @s polished_andesite
execute at @s[scores={random=itemnumber}] run give @s poisonous_potato
execute at @s[scores={random=itemnumber}] run give @s pointed_dripstone
execute at @s[scores={random=itemnumber}] run give @s podzol
execute at @s[scores={random=itemnumber}] run give @s plenty_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s pitcher_pod
execute at @s[scores={random=itemnumber}] run give @s pitcher_plant
execute at @s[scores={random=itemnumber}] run give @s piston
execute at @s[scores={random=itemnumber}] run give @s pink_wool
execute at @s[scores={random=itemnumber}] run give @s pink_tulip
execute at @s[scores={random=itemnumber}] run give @s pink_terracotta
execute at @s[scores={random=itemnumber}] run give @s pink_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s pink_stained_glass
execute at @s[scores={random=itemnumber}] run give @s pink_shulker_box
execute at @s[scores={random=itemnumber}] run give @s pink_petals
execute at @s[scores={random=itemnumber}] run give @s pink_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s pink_dye
execute at @s[scores={random=itemnumber}] run give @s pink_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s pink_concrete
execute at @s[scores={random=itemnumber}] run give @s pink_carpet
execute at @s[scores={random=itemnumber}] run give @s pink_candle
execute at @s[scores={random=itemnumber}] run give @s piglin_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s phantom_membrane
execute at @s[scores={random=itemnumber}] run give @s petrified_oak_slab
execute at @s[scores={random=itemnumber}] run give @s peony
execute at @s[scores={random=itemnumber}] run give @s pearlescent_froglight
execute at @s[scores={random=itemnumber}] run give @s paper
execute at @s[scores={random=itemnumber}] run give @s painting
execute at @s[scores={random=itemnumber}] run give @s packed_mud
execute at @s[scores={random=itemnumber}] run give @s packed_ice
execute at @s[scores={random=itemnumber}] run give @s quartz_stairs
execute at @s[scores={random=itemnumber}] run give @s quartz_slab
execute at @s[scores={random=itemnumber}] run give @s quartz_ore
execute at @s[scores={random=itemnumber}] run give @s quartz_bricks
execute at @s[scores={random=itemnumber}] run give @s quartz_block
execute at @s[scores={random=itemnumber}] run give @s quartz
execute at @s[scores={random=itemnumber}] run give @s rotten_flesh
execute at @s[scores={random=itemnumber}] run give @s rose_bush
execute at @s[scores={random=itemnumber}] run give @s rib_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s respawn_anchor
execute at @s[scores={random=itemnumber}] run give @s repeater
execute at @s[scores={random=itemnumber}] run give @s reinforced_deepslate
execute at @s[scores={random=itemnumber}] run give @s redstone_torch
execute at @s[scores={random=itemnumber}] run give @s redstone_ore
execute at @s[scores={random=itemnumber}] run give @s redstone_lamp
execute at @s[scores={random=itemnumber}] run give @s redstone_block
execute at @s[scores={random=itemnumber}] run give @s redstone
execute at @s[scores={random=itemnumber}] run give @s red_wool
execute at @s[scores={random=itemnumber}] run give @s red_tulip
execute at @s[scores={random=itemnumber}] run give @s red_terracotta
execute at @s[scores={random=itemnumber}] run give @s red_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s red_stained_glass
execute at @s[scores={random=itemnumber}] run give @s red_shulker_box
execute at @s[scores={random=itemnumber}] run give @s red_sandstone_stairs
execute at @s[scores={random=itemnumber}] run give @s red_sandstone
execute at @s[scores={random=itemnumber}] run give @s red_nether_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s red_nether_brick
execute at @s[scores={random=itemnumber}] run give @s red_mushroom_block
execute at @s[scores={random=itemnumber}] run give @s red_mushroom
execute at @s[scores={random=itemnumber}] run give @s red_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s red_dye
execute at @s[scores={random=itemnumber}] run give @s red_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s red_concrete
execute at @s[scores={random=itemnumber}] run give @s red_carpet
execute at @s[scores={random=itemnumber}] run give @s red_candle
execute at @s[scores={random=itemnumber}] run give @s recovery_compass
execute at @s[scores={random=itemnumber}] run give @s raw_iron_block
execute at @s[scores={random=itemnumber}] run give @s raw_iron
execute at @s[scores={random=itemnumber}] run give @s raw_gold_block
execute at @s[scores={random=itemnumber}] run give @s raw_gold
execute at @s[scores={random=itemnumber}] run give @s raw_copper_block
execute at @s[scores={random=itemnumber}] run give @s raw_copper
execute at @s[scores={random=itemnumber}] run give @s raiser_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s rail
execute at @s[scores={random=itemnumber}] run give @s rabbit_stew
execute at @s[scores={random=itemnumber}] run give @s rabbit_hide
execute at @s[scores={random=itemnumber}] run give @s rabbit_foot
execute at @s[scores={random=itemnumber}] run give @s rabbit
execute at @s[scores={random=itemnumber}] run give @s sweet_berries
execute at @s[scores={random=itemnumber}] run give @s suspicious_sand
execute at @s[scores={random=itemnumber}] run give @s suspicious_gravel
execute at @s[scores={random=itemnumber}] run give @s sunflower
execute at @s[scores={random=itemnumber}] run give @s sugar_cane
execute at @s[scores={random=itemnumber}] run give @s sugar
execute at @s[scores={random=itemnumber}] run give @s stripped_warped_stem
execute at @s[scores={random=itemnumber}] run give @s stripped_warped_hyphae
execute at @s[scores={random=itemnumber}] run give @s stripped_spruce_wood
execute at @s[scores={random=itemnumber}] run give @s stripped_spruce_log
execute at @s[scores={random=itemnumber}] run give @s stripped_oak_wood
execute at @s[scores={random=itemnumber}] run give @s stripped_oak_log
execute at @s[scores={random=itemnumber}] run give @s stripped_mangrove_wood
execute at @s[scores={random=itemnumber}] run give @s stripped_mangrove_log
execute at @s[scores={random=itemnumber}] run give @s stripped_jungle_wood
execute at @s[scores={random=itemnumber}] run give @s stripped_jungle_log
execute at @s[scores={random=itemnumber}] run give @s stripped_dark_oak_wood
execute at @s[scores={random=itemnumber}] run give @s stripped_dark_oak_log
execute at @s[scores={random=itemnumber}] run give @s stripped_crimson_stem
execute at @s[scores={random=itemnumber}] run give @s stripped_crimson_hyphae
execute at @s[scores={random=itemnumber}] run give @s stripped_cherry_wood
execute at @s[scores={random=itemnumber}] run give @s stripped_cherry_log
execute at @s[scores={random=itemnumber}] run give @s stripped_birch_wood
execute at @s[scores={random=itemnumber}] run give @s stripped_birch_log
execute at @s[scores={random=itemnumber}] run give @s stripped_bamboo_block
execute at @s[scores={random=itemnumber}] run give @s stripped_acacia_wood
execute at @s[scores={random=itemnumber}] run give @s stripped_acacia_log
execute at @s[scores={random=itemnumber}] run give @s string
execute at @s[scores={random=itemnumber}] run give @s stonecutter_block
execute at @s[scores={random=itemnumber}] run give @s stonebrick
execute at @s[scores={random=itemnumber}] run give @s stone_sword
execute at @s[scores={random=itemnumber}] run give @s stone_stairs
execute at @s[scores={random=itemnumber}] run give @s stone_shovel
execute at @s[scores={random=itemnumber}] run give @s stone_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s stone_pickaxe
execute at @s[scores={random=itemnumber}] run give @s stone_hoe
execute at @s[scores={random=itemnumber}] run give @s stone_button
execute at @s[scores={random=itemnumber}] run give @s stone_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s stone_brick_slab
execute at @s[scores={random=itemnumber}] run give @s stone_block_slab4
execute at @s[scores={random=itemnumber}] run give @s stone_block_slab3
execute at @s[scores={random=itemnumber}] run give @s stone_block_slab2
execute at @s[scores={random=itemnumber}] run give @s stone_axe
execute at @s[scores={random=itemnumber}] run give @s stone
execute at @s[scores={random=itemnumber}] run give @s sticky_piston
execute at @s[scores={random=itemnumber}] run give @s stick
execute at @s[scores={random=itemnumber}] run give @s spyglass
execute at @s[scores={random=itemnumber}] run give @s spruce_wood
execute at @s[scores={random=itemnumber}] run give @s spruce_trapdoor
execute at @s[scores={random=itemnumber}] run give @s spruce_stairs
execute at @s[scores={random=itemnumber}] run give @s spruce_slab
execute at @s[scores={random=itemnumber}] run give @s spruce_sign
execute at @s[scores={random=itemnumber}] run give @s spruce_sapling
execute at @s[scores={random=itemnumber}] run give @s spruce_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s spruce_planks
execute at @s[scores={random=itemnumber}] run give @s spruce_log
execute at @s[scores={random=itemnumber}] run give @s spruce_leaves
execute at @s[scores={random=itemnumber}] run give @s spruce_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s spruce_fence_gate
execute at @s[scores={random=itemnumber}] run give @s spruce_fence
execute at @s[scores={random=itemnumber}] run give @s spruce_door
execute at @s[scores={random=itemnumber}] run give @s spruce_chest_boat
execute at @s[scores={random=itemnumber}] run give @s spruce_button
execute at @s[scores={random=itemnumber}] run give @s spruce_boat
execute at @s[scores={random=itemnumber}] run give @s spore_blossom
execute at @s[scores={random=itemnumber}] run give @s sponge
execute at @s[scores={random=itemnumber}] run give @s splash_potion
execute at @s[scores={random=itemnumber}] run give @s spire_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s spider_eye
execute at @s[scores={random=itemnumber}] run give @s soul_torch
execute at @s[scores={random=itemnumber}] run give @s soul_soil
execute at @s[scores={random=itemnumber}] run give @s soul_sand
execute at @s[scores={random=itemnumber}] run give @s soul_lantern
execute at @s[scores={random=itemnumber}] run give @s soul_campfire
execute at @s[scores={random=itemnumber}] run give @s snowball
execute at @s[scores={random=itemnumber}] run give @s snow_layer
execute at @s[scores={random=itemnumber}] run give @s snow
execute at @s[scores={random=itemnumber}] run give @s snout_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s snort_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s sniffer_egg
execute at @s[scores={random=itemnumber}] run give @s smooth_stone_slab
execute at @s[scores={random=itemnumber}] run give @s smooth_sandstone_stairs
execute at @s[scores={random=itemnumber}] run give @s smooth_stone
execute at @s[scores={random=itemnumber}] run give @s smooth_red_sandstone_stairs
execute at @s[scores={random=itemnumber}] run give @s smooth_quartz_stairs
execute at @s[scores={random=itemnumber}] run give @s smooth_basalt
execute at @s[scores={random=itemnumber}] run give @s smoker
execute at @s[scores={random=itemnumber}] run give @s smithing_table
execute at @s[scores={random=itemnumber}] run give @s small_dripleaf_block
execute at @s[scores={random=itemnumber}] run give @s small_amethyst_bud
execute at @s[scores={random=itemnumber}] run give @s slime_ball
execute at @s[scores={random=itemnumber}] run give @s slime
execute at @s[scores={random=itemnumber}] run give @s skull_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s skull_banner_pattern
execute at @s[scores={random=itemnumber}] run give @s skull
execute at @s[scores={random=itemnumber}] run give @s silver_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s silence_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s shulker_shell
execute at @s[scores={random=itemnumber}] run give @s shroomlight
execute at @s[scores={random=itemnumber}] run give @s short_grass
execute at @s[scores={random=itemnumber}] run give @s shield
execute at @s[scores={random=itemnumber}] run give @s shelter_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s shears
execute at @s[scores={random=itemnumber}] run give @s sheaf_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s shaper_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s sentry_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s seagrass
execute at @s[scores={random=itemnumber}] run give @s sea_pickle
execute at @s[scores={random=itemnumber}] run give @s sea_lantern
execute at @s[scores={random=itemnumber}] run give @s sculk_vein
execute at @s[scores={random=itemnumber}] run give @s sculk_shrieker
execute at @s[scores={random=itemnumber}] run give @s sculk_sensor
execute at @s[scores={random=itemnumber}] run give @s sculk_catalyst
execute at @s[scores={random=itemnumber}] run give @s sculk
execute at @s[scores={random=itemnumber}] run give @s scrape_pottery_sherd
execute at @s[scores={random=itemnumber}] run give @s scaffolding
execute at @s[scores={random=itemnumber}] run give @s sandstone_stairs
execute at @s[scores={random=itemnumber}] run give @s sandstone_slab
execute at @s[scores={random=itemnumber}] run give @s sandstone
execute at @s[scores={random=itemnumber}] run give @s sand
execute at @s[scores={random=itemnumber}] run give @s salmon_bucket
execute at @s[scores={random=itemnumber}] run give @s salmon
execute at @s[scores={random=itemnumber}] run give @s saddle
execute at @s[scores={random=itemnumber}] run give @s twisting_vines
execute at @s[scores={random=itemnumber}] run give @s turtle_scute
execute at @s[scores={random=itemnumber}] run give @s turtle_helmet
execute at @s[scores={random=itemnumber}] run give @s turtle_egg
execute at @s[scores={random=itemnumber}] run give @s tuff_wall
execute at @s[scores={random=itemnumber}] run give @s tuff_stairs
execute at @s[scores={random=itemnumber}] run give @s tuff_slab
execute at @s[scores={random=itemnumber}] run give @s tuff_bricks
execute at @s[scores={random=itemnumber}] run give @s tuff_brick_wall
execute at @s[scores={random=itemnumber}] run give @s tuff_brick_stairs
execute at @s[scores={random=itemnumber}] run give @s tuff_brick_slab
execute at @s[scores={random=itemnumber}] run give @s tuff
execute at @s[scores={random=itemnumber}] run give @s tube_coral_fan
execute at @s[scores={random=itemnumber}] run give @s tube_coral_block
execute at @s[scores={random=itemnumber}] run give @s tube_coral
execute at @s[scores={random=itemnumber}] run give @s tropical_fish_bucket
execute at @s[scores={random=itemnumber}] run give @s tropical_fish
execute at @s[scores={random=itemnumber}] run give @s tripwire_hook
execute at @s[scores={random=itemnumber}] run give @s trident
execute at @s[scores={random=itemnumber}] run give @s trial_spawner
execute at @s[scores={random=itemnumber}] run give @s trial_key
execute at @s[scores={random=itemnumber}] run give @s trapped_chest
execute at @s[scores={random=itemnumber}] run give @s trapdoor
execute at @s[scores={random=itemnumber}] run give @s totem_of_undying
execute at @s[scores={random=itemnumber}] run give @s torchflower_seeds
execute at @s[scores={random=itemnumber}] run give @s torchflower
execute at @s[scores={random=itemnumber}] run give @s torch
execute at @s[scores={random=itemnumber}] run give @s tnt_minecart
execute at @s[scores={random=itemnumber}] run give @s tnt
execute at @s[scores={random=itemnumber}] run give @s tinted_glass
execute at @s[scores={random=itemnumber}] run give @s tide_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s target
execute at @s[scores={random=itemnumber}] run give @s tall_grass
execute at @s[scores={random=itemnumber}] run give @s tadpole_bucket
execute at @s[scores={random=itemnumber}] run give @s undyed_shulker_box
execute at @s[scores={random=itemnumber}] run give @s vine
execute at @s[scores={random=itemnumber}] run give @s vex_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s verdant_froglight
execute at @s[scores={random=itemnumber}] run give @s vault
execute at @s[scores={random=itemnumber}] run give @s writable_book
execute at @s[scores={random=itemnumber}] run give @s wooden_sword
execute at @s[scores={random=itemnumber}] run give @s wooden_slab
execute at @s[scores={random=itemnumber}] run give @s wooden_shovel
execute at @s[scores={random=itemnumber}] run give @s wooden_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s wooden_pickaxe
execute at @s[scores={random=itemnumber}] run give @s wooden_hoe
execute at @s[scores={random=itemnumber}] run give @s wooden_door
execute at @s[scores={random=itemnumber}] run give @s wooden_button
execute at @s[scores={random=itemnumber}] run give @s wooden_axe
execute at @s[scores={random=itemnumber}] run give @s wolf_armor
execute at @s[scores={random=itemnumber}] run give @s wither_rose
execute at @s[scores={random=itemnumber}] run give @s wind_charge
execute at @s[scores={random=itemnumber}] run give @s wild_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s white_wool
execute at @s[scores={random=itemnumber}] run give @s white_tulip
execute at @s[scores={random=itemnumber}] run give @s white_terracotta
execute at @s[scores={random=itemnumber}] run give @s white_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s white_stained_glass
execute at @s[scores={random=itemnumber}] run give @s white_shulker_box
execute at @s[scores={random=itemnumber}] run give @s white_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s white_dye
execute at @s[scores={random=itemnumber}] run give @s white_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s white_concrete
execute at @s[scores={random=itemnumber}] run give @s white_carpet
execute at @s[scores={random=itemnumber}] run give @s white_candle
execute at @s[scores={random=itemnumber}] run give @s wheat_seeds
execute at @s[scores={random=itemnumber}] run give @s wheat
execute at @s[scores={random=itemnumber}] run give @s weeping_vines
execute at @s[scores={random=itemnumber}] run give @s web
execute at @s[scores={random=itemnumber}] run give @s wayfinder_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s waterlily
execute at @s[scores={random=itemnumber}] run give @s water_bucket
execute at @s[scores={random=itemnumber}] run give @s warped_wart_block
execute at @s[scores={random=itemnumber}] run give @s warped_trapdoor
execute at @s[scores={random=itemnumber}] run give @s warped_stem
execute at @s[scores={random=itemnumber}] run give @s warped_stairs
execute at @s[scores={random=itemnumber}] run give @s warped_slab
execute at @s[scores={random=itemnumber}] run give @s warped_sign
execute at @s[scores={random=itemnumber}] run give @s warped_roots
execute at @s[scores={random=itemnumber}] run give @s warped_pressure_plate
execute at @s[scores={random=itemnumber}] run give @s warped_planks
execute at @s[scores={random=itemnumber}] run give @s warped_nylium
execute at @s[scores={random=itemnumber}] run give @s warped_hyphae
execute at @s[scores={random=itemnumber}] run give @s warped_hanging_sign
execute at @s[scores={random=itemnumber}] run give @s warped_fungus_on_a_stick
execute at @s[scores={random=itemnumber}] run give @s warped_fungus
execute at @s[scores={random=itemnumber}] run give @s warped_fence_gate
execute at @s[scores={random=itemnumber}] run give @s warped_fence
execute at @s[scores={random=itemnumber}] run give @s warped_door
execute at @s[scores={random=itemnumber}] run give @s warped_button
execute at @s[scores={random=itemnumber}] run give @s ward_armor_trim_smithing_template
execute at @s[scores={random=itemnumber}] run give @s yellow_wool
execute at @s[scores={random=itemnumber}] run give @s yellow_terracotta
execute at @s[scores={random=itemnumber}] run give @s yellow_stained_glass_pane
execute at @s[scores={random=itemnumber}] run give @s yellow_stained_glass
execute at @s[scores={random=itemnumber}] run give @s yellow_shulker_box
execute at @s[scores={random=itemnumber}] run give @s yellow_glazed_terracotta
execute at @s[scores={random=itemnumber}] run give @s yellow_dye
execute at @s[scores={random=itemnumber}] run give @s yellow_concrete_powder
execute at @s[scores={random=itemnumber}] run give @s yellow_concrete
execute at @s[scores={random=itemnumber}] run give @s yellow_carpet
execute at @s[scores={random=itemnumber}] run give @s yellow_candle
execute at @s[scores={random=itemnumber}] run give @s bed 1 1
execute at @s[scores={random=itemnumber}] run give @s bed 1 2
execute at @s[scores={random=itemnumber}] run give @s bed 1 3
execute at @s[scores={random=itemnumber}] run give @s bed 1 4
execute at @s[scores={random=itemnumber}] run give @s bed 1 5
execute at @s[scores={random=itemnumber}] run give @s bed 1 6
execute at @s[scores={random=itemnumber}] run give @s bed 1 7
execute at @s[scores={random=itemnumber}] run give @s bed 1 8
execute at @s[scores={random=itemnumber}] run give @s bed 1 9
execute at @s[scores={random=itemnumber}] run give @s bed 1 10
execute at @s[scores={random=itemnumber}] run give @s bed 1 11
execute at @s[scores={random=itemnumber}] run give @s bed 1 12
execute at @s[scores={random=itemnumber}] run give @s bed 1 13
execute at @s[scores={random=itemnumber}] run give @s bed 1 14
execute at @s[scores={random=itemnumber}] run give @s bed 1 15
execute at @s[scores={random=itemnumber}] run give @s ominous_bottle 1 1
execute at @s[scores={random=itemnumber}] run give @s ominous_bottle 1 2
execute at @s[scores={random=itemnumber}] run give @s ominous_bottle 1 3
execute at @s[scores={random=itemnumber}] run give @s ominous_bottle 1 4
execute at @s[scores={random=itemnumber}] run give @s firework_rocket 1 2
execute at @s[scores={random=itemnumber}] run give @s firework_rocket 1 3
execute at @s[scores={random=itemnumber}] run give @s banner 1 1
execute at @s[scores={random=itemnumber}] run give @s banner 1 2
execute at @s[scores={random=itemnumber}] run give @s banner 1 3
execute at @s[scores={random=itemnumber}] run give @s banner 1 4
execute at @s[scores={random=itemnumber}] run give @s banner 1 5
execute at @s[scores={random=itemnumber}] run give @s banner 1 6
execute at @s[scores={random=itemnumber}] run give @s banner 1 7
execute at @s[scores={random=itemnumber}] run give @s banner 1 8
execute at @s[scores={random=itemnumber}] run give @s banner 1 9
execute at @s[scores={random=itemnumber}] run give @s banner 1 10
execute at @s[scores={random=itemnumber}] run give @s banner 1 11
execute at @s[scores={random=itemnumber}] run give @s banner 1 12
execute at @s[scores={random=itemnumber}] run give @s banner 1 13
execute at @s[scores={random=itemnumber}] run give @s banner 1 14
execute at @s[scores={random=itemnumber}] run give @s banner 1 15
execute at @s[scores={random=itemnumber}] run give @s skull 1 1
execute at @s[scores={random=itemnumber}] run give @s skull 1 2
execute at @s[scores={random=itemnumber}] run give @s skull 1 3
execute at @s[scores={random=itemnumber}] run give @s skull 1 4
execute at @s[scores={random=itemnumber}] run give @s skull 1 5
execute at @s[scores={random=itemnumber}] run give @s bundle
execute at @s[scores={random=itemnumber}] run give @s black_bundle
execute at @s[scores={random=itemnumber}] run give @s blue_bundle
execute at @s[scores={random=itemnumber}] run give @s brown_bundle
execute at @s[scores={random=itemnumber}] run give @s cyan_bundle
execute at @s[scores={random=itemnumber}] run give @s gray_bundle
execute at @s[scores={random=itemnumber}] run give @s green_bundle
execute at @s[scores={random=itemnumber}] run give @s light_blue_bundle
execute at @s[scores={random=itemnumber}] run give @s light_gray_bundle
execute at @s[scores={random=itemnumber}] run give @s lime_bundle
execute at @s[scores={random=itemnumber}] run give @s magenta_bundle
execute at @s[scores={random=itemnumber}] run give @s orange_bundle
execute at @s[scores={random=itemnumber}] run give @s pink_bundle
execute at @s[scores={random=itemnumber}] run give @s purple_bundle
execute at @s[scores={random=itemnumber}] run give @s red_bundle
execute at @s[scores={random=itemnumber}] run give @s white_bundle
execute at @s[scores={random=itemnumber}] run give @s yellow_bundle
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 0
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 1
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 2
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 3
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 4
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 5
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 6
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 7
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 8
execute at @s[scores={random=itemnumber}] run give @s suspicious_stew 1 9
execute at @s[scores={random=itemnumber}] run give @s goat_horn 1 0
execute at @s[scores={random=itemnumber}] run give @s goat_horn 1 1
execute at @s[scores={random=itemnumber}] run give @s goat_horn 1 2
execute at @s[scores={random=itemnumber}] run give @s goat_horn 1 3
execute at @s[scores={random=itemnumber}] run give @s goat_horn 1 4
execute at @s[scores={random=itemnumber}] run give @s goat_horn 1 5
execute at @s[scores={random=itemnumber}] run give @s goat_horn 1 6
execute at @s[scores={random=itemnumber}] run give @s goat_horn 1 7