scoreboard players random @s random 1 100
execute at @s[scores={random=1}] run structure load books:AquaAffinity1 ~ ~ ~
execute at @s[scores={random=2}] run structure load books:BaneOfArthropods1 ~ ~ ~
execute at @s[scores={random=3}] run structure load books:BaneOfArthropods2 ~ ~ ~
execute at @s[scores={random=4}] run structure load books:BaneOfArthropods3 ~ ~ ~
execute at @s[scores={random=5}] run structure load books:BaneOfArthropods4 ~ ~ ~
execute at @s[scores={random=6}] run structure load books:BaneOfArthropods5 ~ ~ ~
execute at @s[scores={random=7}] run structure load books:BlastProt1 ~ ~ ~
execute at @s[scores={random=8}] run structure load books:BlastProt2 ~ ~ ~
execute at @s[scores={random=9}] run structure load books:BlastProt3 ~ ~ ~
execute at @s[scores={random=10}] run structure load books:BlastProt4 ~ ~ ~
execute at @s[scores={random=11}] run structure load books:Breach1 ~ ~ ~
execute at @s[scores={random=12}] run structure load books:Breach2 ~ ~ ~
execute at @s[scores={random=13}] run structure load books:Breach3 ~ ~ ~
execute at @s[scores={random=14}] run structure load books:Breach4 ~ ~ ~
execute at @s[scores={random=15}] run structure load books:Channeling1 ~ ~ ~
execute at @s[scores={random=16}] run structure load books:CurseOfBinding1 ~ ~ ~
execute at @s[scores={random=17}] run structure load books:CurseOfVanishing1 ~ ~ ~
execute at @s[scores={random=18}] run structure load books:Density1 ~ ~ ~
execute at @s[scores={random=19}] run structure load books:Density2 ~ ~ ~
execute at @s[scores={random=20}] run structure load books:Density3 ~ ~ ~
execute at @s[scores={random=21}] run structure load books:Density4 ~ ~ ~
execute at @s[scores={random=22}] run structure load books:Density5 ~ ~ ~
execute at @s[scores={random=23}] run structure load books:DepthStrider1 ~ ~ ~
execute at @s[scores={random=24}] run structure load books:DepthStrider2 ~ ~ ~
execute at @s[scores={random=25}] run structure load books:DepthStrider3 ~ ~ ~
execute at @s[scores={random=26}] run structure load books:Efficiency1 ~ ~ ~
execute at @s[scores={random=27}] run structure load books:Efficiency2 ~ ~ ~
execute at @s[scores={random=28}] run structure load books:Efficiency3 ~ ~ ~
execute at @s[scores={random=29}] run structure load books:Efficiency4 ~ ~ ~
execute at @s[scores={random=30}] run structure load books:Efficiency5 ~ ~ ~
execute at @s[scores={random=31}] run structure load books:FeatherFalling1 ~ ~ ~
execute at @s[scores={random=32}] run structure load books:FeatherFalling2 ~ ~ ~
execute at @s[scores={random=33}] run structure load books:FeatherFalling3 ~ ~ ~
execute at @s[scores={random=34}] run structure load books:FeatherFalling4 ~ ~ ~
execute at @s[scores={random=35}] run structure load books:FireAspect1 ~ ~ ~
execute at @s[scores={random=36}] run structure load books:FireAspect2 ~ ~ ~
execute at @s[scores={random=37}] run structure load books:FireProt1 ~ ~ ~
execute at @s[scores={random=38}] run structure load books:FireProt2 ~ ~ ~
execute at @s[scores={random=39}] run structure load books:FireProt3 ~ ~ ~
execute at @s[scores={random=40}] run structure load books:FireProt4 ~ ~ ~
execute at @s[scores={random=41}] run structure load books:Flame1 ~ ~ ~
execute at @s[scores={random=42}] run structure load books:Fortune1 ~ ~ ~
execute at @s[scores={random=43}] run structure load books:Fortune2 ~ ~ ~
execute at @s[scores={random=44}] run structure load books:Fortune3 ~ ~ ~
execute at @s[scores={random=45}] run structure load books:FrostWalker1 ~ ~ ~
execute at @s[scores={random=46}] run structure load books:FrostWalker2 ~ ~ ~
execute at @s[scores={random=47}] run structure load books:Impaling1 ~ ~ ~
execute at @s[scores={random=48}] run structure load books:Impaling2 ~ ~ ~
execute at @s[scores={random=49}] run structure load books:Impaling3 ~ ~ ~
execute at @s[scores={random=50}] run structure load books:Impaling4 ~ ~ ~
execute at @s[scores={random=51}] run structure load books:Impaling5 ~ ~ ~
execute at @s[scores={random=52}] run structure load books:Infinity1 ~ ~ ~
execute at @s[scores={random=53}] run structure load books:Knockback1 ~ ~ ~
execute at @s[scores={random=54}] run structure load books:Knockback2 ~ ~ ~
execute at @s[scores={random=55}] run structure load books:Looting1 ~ ~ ~
execute at @s[scores={random=56}] run structure load books:Looting2 ~ ~ ~
execute at @s[scores={random=57}] run structure load books:Looting3 ~ ~ ~
execute at @s[scores={random=58}] run structure load books:Loyalty1 ~ ~ ~
execute at @s[scores={random=59}] run structure load books:Loyalty2 ~ ~ ~
execute at @s[scores={random=60}] run structure load books:Loyalty3 ~ ~ ~
execute at @s[scores={random=61}] run structure load books:LuckOfTheSea1 ~ ~ ~
execute at @s[scores={random=62}] run structure load books:LuckOfTheSea2 ~ ~ ~
execute at @s[scores={random=63}] run structure load books:LuckOfTheSea3 ~ ~ ~
execute at @s[scores={random=64}] run structure load books:Lure1 ~ ~ ~
execute at @s[scores={random=65}] run structure load books:Lure2 ~ ~ ~
execute at @s[scores={random=66}] run structure load books:Lure3 ~ ~ ~
execute at @s[scores={random=67}] run structure load books:Mending1 ~ ~ ~
execute at @s[scores={random=68}] run structure load books:Multishot1 ~ ~ ~
execute at @s[scores={random=69}] run structure load books:Piercing1 ~ ~ ~
execute at @s[scores={random=70}] run structure load books:Piercing2 ~ ~ ~
execute at @s[scores={random=71}] run structure load books:Piercing3 ~ ~ ~
execute at @s[scores={random=72}] run structure load books:Piercing4 ~ ~ ~
execute at @s[scores={random=73}] run structure load books:Power1 ~ ~ ~
execute at @s[scores={random=74}] run structure load books:Power2 ~ ~ ~
execute at @s[scores={random=75}] run structure load books:Power3 ~ ~ ~
execute at @s[scores={random=76}] run structure load books:Power4 ~ ~ ~
execute at @s[scores={random=77}] run structure load books:Power5 ~ ~ ~
execute at @s[scores={random=78}] run structure load books:ProjectileProt1 ~ ~ ~
execute at @s[scores={random=79}] run structure load books:ProjectileProt2 ~ ~ ~
execute at @s[scores={random=80}] run structure load books:ProjectileProt3 ~ ~ ~
execute at @s[scores={random=81}] run structure load books:ProjectileProt4 ~ ~ ~
execute at @s[scores={random=82}] run structure load books:Prot1 ~ ~ ~
execute at @s[scores={random=83}] run structure load books:Prot2 ~ ~ ~
execute at @s[scores={random=84}] run structure load books:Prot3 ~ ~ ~
execute at @s[scores={random=85}] run structure load books:Prot4 ~ ~ ~
execute at @s[scores={random=86}] run structure load books:Punch1 ~ ~ ~
execute at @s[scores={random=87}] run structure load books:Punch2 ~ ~ ~
execute at @s[scores={random=88}] run structure load books:QuickCharge1 ~ ~ ~
execute at @s[scores={random=89}] run structure load books:QuickCharge2 ~ ~ ~
execute at @s[scores={random=90}] run structure load books:QuickCharge3 ~ ~ ~
execute at @s[scores={random=91}] run structure load books:Respiration1 ~ ~ ~
execute at @s[scores={random=92}] run structure load books:Respiration2 ~ ~ ~
execute at @s[scores={random=93}] run structure load books:Respiration3 ~ ~ ~
execute at @s[scores={random=94}] run structure load books:Riptide1 ~ ~ ~
execute at @s[scores={random=95}] run structure load books:Riptide2 ~ ~ ~
execute at @s[scores={random=96}] run structure load books:Riptide3 ~ ~ ~
execute at @s[scores={random=97}] run structure load books:Sharpness1 ~ ~ ~
execute at @s[scores={random=98}] run structure load books:Sharpness2 ~ ~ ~
execute at @s[scores={random=99}] run structure load books:Sharpness3 ~ ~ ~
execute at @s[scores={random=100}] run structure load books:Sharpness4 ~ ~ ~

scoreboard players random @s random 1 1246