scoreboard players random @s random 1 1111
execute at @s[scores={random=1}] run give @s acacia_boat
execute at @s[scores={random=2}] run give @s acacia_button
execute at @s[scores={random=3}] run give @s acacia_chest_boat
execute at @s[scores={random=4}] run give @s acacia_door
execute at @s[scores={random=5}] run give @s acacia_fence
execute at @s[scores={random=6}] run give @s acacia_fence_gate
execute at @s[scores={random=7}] run give @s acacia_hanging_sign
execute at @s[scores={random=8}] run give @s acacia_leaves
execute at @s[scores={random=9}] run give @s acacia_log
execute at @s[scores={random=10}] run give @s acacia_planks
execute at @s[scores={random=11}] run give @s acacia_pressure_plate
execute at @s[scores={random=12}] run give @s acacia_sapling
execute at @s[scores={random=13}] run give @s acacia_sign
execute at @s[scores={random=14}] run give @s acacia_slab
execute at @s[scores={random=15}] run give @s acacia_stairs
execute at @s[scores={random=16}] run give @s acacia_trapdoor
execute at @s[scores={random=17}] run give @s acacia_wood
execute at @s[scores={random=18}] run give @s activator_rail
execute at @s[scores={random=19}] run give @s air
execute at @s[scores={random=20}] run give @s allium
execute at @s[scores={random=21}] run give @s amethyst_block
execute at @s[scores={random=22}] run give @s amethyst_cluster
execute at @s[scores={random=23}] run give @s amethyst_shard
execute at @s[scores={random=24}] run give @s ancient_debris
execute at @s[scores={random=25}] run give @s andesite
execute at @s[scores={random=26}] run give @s andesite_stairs
execute at @s[scores={random=27}] run give @s angler_pottery_sherd
execute at @s[scores={random=28}] run give @s anvil
execute at @s[scores={random=29}] run give @s apple
execute at @s[scores={random=30}] run give @s archer_pottery_sherd
execute at @s[scores={random=31}] run give @s armadillo_scute
execute at @s[scores={random=32}] run give @s armor_stand
execute at @s[scores={random=33}] run give @s arms_up_pottery_sherd
execute at @s[scores={random=34}] run give @s arrow
execute at @s[scores={random=35}] run give @s axolotl_bucket
execute at @s[scores={random=36}] run give @s azalea
execute at @s[scores={random=37}] run give @s azalea_leaves
execute at @s[scores={random=38}] run give @s azalea_leaves_flowered
execute at @s[scores={random=39}] run give @s azure_bluet
execute at @s[scores={random=40}] run give @s baked_potato
execute at @s[scores={random=41}] run give @s bamboo
execute at @s[scores={random=42}] run give @s bamboo_block
execute at @s[scores={random=43}] run give @s bamboo_button
execute at @s[scores={random=44}] run give @s bamboo_chest_raft
execute at @s[scores={random=45}] run give @s bamboo_door
execute at @s[scores={random=46}] run give @s bamboo_fence
execute at @s[scores={random=47}] run give @s bamboo_fence_gate
execute at @s[scores={random=48}] run give @s bamboo_hanging_sign
execute at @s[scores={random=49}] run give @s bamboo_mosaic
execute at @s[scores={random=50}] run give @s bamboo_mosaic_slab
execute at @s[scores={random=51}] run give @s bamboo_mosaic_stairs
execute at @s[scores={random=52}] run give @s bamboo_planks
execute at @s[scores={random=53}] run give @s bamboo_pressure_plate
execute at @s[scores={random=54}] run give @s bamboo_raft
execute at @s[scores={random=55}] run give @s bamboo_sign
execute at @s[scores={random=56}] run give @s bamboo_slab
execute at @s[scores={random=57}] run give @s bamboo_stairs
execute at @s[scores={random=58}] run give @s bamboo_trapdoor
execute at @s[scores={random=59}] run give @s banner
execute at @s[scores={random=60}] run give @s barrel
execute at @s[scores={random=61}] run give @s basalt
execute at @s[scores={random=62}] run give @s beacon
execute at @s[scores={random=63}] run give @s bed
execute at @s[scores={random=64}] run give @s bee_nest
execute at @s[scores={random=65}] run give @s beef
execute at @s[scores={random=66}] run give @s beehive
execute at @s[scores={random=67}] run give @s beetroot
execute at @s[scores={random=68}] run give @s beetroot_seeds
execute at @s[scores={random=69}] run give @s beetroot_soup
execute at @s[scores={random=70}] run give @s bell
execute at @s[scores={random=71}] run give @s big_dripleaf
execute at @s[scores={random=72}] run give @s birch_boat
execute at @s[scores={random=73}] run give @s birch_button
execute at @s[scores={random=74}] run give @s birch_chest_boat
execute at @s[scores={random=75}] run give @s birch_door
execute at @s[scores={random=76}] run give @s birch_fence
execute at @s[scores={random=77}] run give @s birch_fence_gate
execute at @s[scores={random=78}] run give @s birch_hanging_sign
execute at @s[scores={random=79}] run give @s birch_leaves
execute at @s[scores={random=80}] run give @s birch_log
execute at @s[scores={random=81}] run give @s birch_planks
execute at @s[scores={random=82}] run give @s birch_pressure_plate
execute at @s[scores={random=83}] run give @s birch_sapling
execute at @s[scores={random=84}] run give @s birch_sign
execute at @s[scores={random=85}] run give @s birch_slab
execute at @s[scores={random=86}] run give @s birch_stairs
execute at @s[scores={random=87}] run give @s birch_trapdoor
execute at @s[scores={random=88}] run give @s birch_wood
execute at @s[scores={random=89}] run give @s black_candle
execute at @s[scores={random=90}] run give @s black_carpet
execute at @s[scores={random=91}] run give @s black_concrete
execute at @s[scores={random=92}] run give @s black_concrete_powder
execute at @s[scores={random=93}] run give @s black_dye
execute at @s[scores={random=94}] run give @s black_glazed_terracotta
execute at @s[scores={random=95}] run give @s black_shulker_box
execute at @s[scores={random=96}] run give @s black_stained_glass
execute at @s[scores={random=97}] run give @s black_stained_glass_pane
execute at @s[scores={random=98}] run give @s black_terracotta
execute at @s[scores={random=99}] run give @s black_wool
execute at @s[scores={random=100}] run give @s blackstone
execute at @s[scores={random=101}] run give @s blackstone_slab
execute at @s[scores={random=102}] run give @s blackstone_stairs
execute at @s[scores={random=103}] run give @s blackstone_wall
execute at @s[scores={random=104}] run give @s blade_pottery_sherd
execute at @s[scores={random=105}] run give @s blast_furnace
execute at @s[scores={random=106}] run give @s blaze_powder
execute at @s[scores={random=107}] run give @s blaze_rod
execute at @s[scores={random=108}] run give @s blue_candle
execute at @s[scores={random=109}] run give @s blue_carpet
execute at @s[scores={random=110}] run give @s blue_concrete
execute at @s[scores={random=111}] run give @s blue_concrete_powder
execute at @s[scores={random=112}] run give @s blue_dye
execute at @s[scores={random=113}] run give @s blue_glazed_terracotta
execute at @s[scores={random=114}] run give @s blue_ice
execute at @s[scores={random=115}] run give @s blue_orchid
execute at @s[scores={random=116}] run give @s blue_shulker_box
execute at @s[scores={random=117}] run give @s blue_stained_glass
execute at @s[scores={random=118}] run give @s blue_stained_glass_pane
execute at @s[scores={random=119}] run give @s blue_terracotta
execute at @s[scores={random=120}] run give @s blue_wool
execute at @s[scores={random=121}] run give @s bolt_armor_trim_smithing_template
execute at @s[scores={random=122}] run give @s bone
execute at @s[scores={random=123}] run give @s bone_block
execute at @s[scores={random=124}] run give @s bone_meal
execute at @s[scores={random=125}] run give @s book
execute at @s[scores={random=126}] run give @s bookshelf
execute at @s[scores={random=127}] run give @s bordure_indented_banner_pattern
execute at @s[scores={random=128}] run give @s bow
execute at @s[scores={random=129}] run give @s bowl
execute at @s[scores={random=130}] run give @s brain_coral
execute at @s[scores={random=131}] run give @s brain_coral_block
execute at @s[scores={random=132}] run give @s brain_coral_fan
execute at @s[scores={random=133}] run give @s bread
execute at @s[scores={random=134}] run give @s breeze_rod
execute at @s[scores={random=135}] run give @s brewer_pottery_sherd
execute at @s[scores={random=136}] run give @s brewing_stand
execute at @s[scores={random=137}] run give @s brick
execute at @s[scores={random=138}] run give @s brick_block
execute at @s[scores={random=139}] run give @s brick_slab
execute at @s[scores={random=140}] run give @s brick_stairs
execute at @s[scores={random=141}] run give @s brown_candle
execute at @s[scores={random=142}] run give @s brown_carpet
execute at @s[scores={random=143}] run give @s brown_concrete
execute at @s[scores={random=144}] run give @s brown_concrete_powder
execute at @s[scores={random=145}] run give @s brown_dye
execute at @s[scores={random=146}] run give @s brown_glazed_terracotta
execute at @s[scores={random=147}] run give @s brown_mushroom
execute at @s[scores={random=148}] run give @s brown_mushroom_block
execute at @s[scores={random=149}] run give @s brown_shulker_box
execute at @s[scores={random=150}] run give @s brown_stained_glass
execute at @s[scores={random=151}] run give @s brown_stained_glass_pane
execute at @s[scores={random=152}] run give @s brown_terracotta
execute at @s[scores={random=153}] run give @s brown_wool
execute at @s[scores={random=154}] run give @s brush
execute at @s[scores={random=155}] run give @s bubble_coral
execute at @s[scores={random=156}] run give @s bubble_coral_block
execute at @s[scores={random=157}] run give @s bubble_coral_fan
execute at @s[scores={random=158}] run give @s bucket
execute at @s[scores={random=159}] run give @s budding_amethyst
execute at @s[scores={random=160}] run give @s burn_pottery_sherd
execute at @s[scores={random=161}] run give @s cactus
execute at @s[scores={random=162}] run give @s cake
execute at @s[scores={random=163}] run give @s calcite
execute at @s[scores={random=164}] run give @s calibrated_sculk_sensor
execute at @s[scores={random=165}] run give @s campfire
execute at @s[scores={random=166}] run give @s candle
execute at @s[scores={random=167}] run give @s carrot
execute at @s[scores={random=168}] run give @s carrot_on_a_stick
execute at @s[scores={random=169}] run give @s cartography_table
execute at @s[scores={random=170}] run give @s carved_pumpkin
execute at @s[scores={random=171}] run give @s cauldron
execute at @s[scores={random=172}] run give @s chain
execute at @s[scores={random=173}] run give @s chainmail_boots
execute at @s[scores={random=174}] run give @s chainmail_chestplate
execute at @s[scores={random=175}] run give @s chainmail_helmet
execute at @s[scores={random=176}] run give @s chainmail_leggings
execute at @s[scores={random=177}] run give @s charcoal
execute at @s[scores={random=178}] run give @s cherry_boat
execute at @s[scores={random=179}] run give @s cherry_button
execute at @s[scores={random=180}] run give @s cherry_chest_boat
execute at @s[scores={random=181}] run give @s cherry_door
execute at @s[scores={random=182}] run give @s cherry_fence
execute at @s[scores={random=183}] run give @s cherry_fence_gate
execute at @s[scores={random=184}] run give @s cherry_hanging_sign
execute at @s[scores={random=185}] run give @s cherry_leaves
execute at @s[scores={random=186}] run give @s cherry_log
execute at @s[scores={random=187}] run give @s cherry_planks
execute at @s[scores={random=188}] run give @s cherry_pressure_plate
execute at @s[scores={random=189}] run give @s cherry_sapling
execute at @s[scores={random=190}] run give @s cherry_sign
execute at @s[scores={random=191}] run give @s cherry_slab
execute at @s[scores={random=192}] run give @s cherry_stairs
execute at @s[scores={random=193}] run give @s cherry_trapdoor
execute at @s[scores={random=194}] run give @s cherry_wood
execute at @s[scores={random=195}] run give @s chest
execute at @s[scores={random=196}] run give @s chest_minecart
execute at @s[scores={random=197}] run give @s chicken
execute at @s[scores={random=198}] run give @s chiseled_bookshelf
execute at @s[scores={random=199}] run give @s chiseled_deepslate
execute at @s[scores={random=200}] run give @s chiseled_nether_bricks
execute at @s[scores={random=201}] run give @s chiseled_polished_blackstone
execute at @s[scores={random=202}] run give @s chiseled_tuff
execute at @s[scores={random=203}] run give @s chiseled_tuff_bricks
execute at @s[scores={random=204}] run give @s chorus_flower
execute at @s[scores={random=205}] run give @s chorus_fruit
execute at @s[scores={random=206}] run give @s chorus_plant
execute at @s[scores={random=207}] run give @s clay
execute at @s[scores={random=208}] run give @s clay_ball
execute at @s[scores={random=209}] run give @s clock
execute at @s[scores={random=210}] run give @s coal
execute at @s[scores={random=211}] run give @s coal_block
execute at @s[scores={random=212}] run give @s coal_ore
execute at @s[scores={random=213}] run give @s coast_armor_trim_smithing_template
execute at @s[scores={random=214}] run give @s cobbled_deepslate
execute at @s[scores={random=215}] run give @s cobbled_deepslate_slab
execute at @s[scores={random=216}] run give @s cobbled_deepslate_stairs
execute at @s[scores={random=217}] run give @s cobbled_deepslate_wall
execute at @s[scores={random=218}] run give @s cobblestone
execute at @s[scores={random=219}] run give @s cobblestone_slab
execute at @s[scores={random=220}] run give @s cobblestone_wall
execute at @s[scores={random=221}] run give @s cocoa_beans
execute at @s[scores={random=222}] run give @s cod
execute at @s[scores={random=223}] run give @s cod_bucket
execute at @s[scores={random=224}] run give @s comparator
execute at @s[scores={random=225}] run give @s compass
execute at @s[scores={random=226}] run give @s composter
execute at @s[scores={random=227}] run give @s conduit
execute at @s[scores={random=228}] run give @s cooked_beef
execute at @s[scores={random=229}] run give @s cooked_chicken
execute at @s[scores={random=230}] run give @s cooked_cod
execute at @s[scores={random=231}] run give @s cooked_mutton
execute at @s[scores={random=232}] run give @s cooked_porkchop
execute at @s[scores={random=233}] run give @s cooked_rabbit
execute at @s[scores={random=234}] run give @s cooked_salmon
execute at @s[scores={random=235}] run give @s cookie
execute at @s[scores={random=236}] run give @s copper_ingot
execute at @s[scores={random=237}] run give @s copper_ore
execute at @s[scores={random=238}] run give @s crafting_table
execute at @s[scores={random=239}] run give @s cornflower
execute at @s[scores={random=240}] run give @s cracked_deepslate_bricks
execute at @s[scores={random=241}] run give @s cracked_deepslate_tiles
execute at @s[scores={random=242}] run give @s cracked_nether_bricks
execute at @s[scores={random=243}] run give @s cracked_polished_blackstone_bricks
execute at @s[scores={random=244}] run give @s crafter
execute at @s[scores={random=245}] run give @s danger_pottery_sherd
execute at @s[scores={random=246}] run give @s dark_oak_boat
execute at @s[scores={random=247}] run give @s dark_oak_button
execute at @s[scores={random=248}] run give @s dark_oak_chest_boat
execute at @s[scores={random=249}] run give @s dark_oak_door
execute at @s[scores={random=250}] run give @s dark_oak_fence
execute at @s[scores={random=251}] run give @s dark_oak_fence_gate
execute at @s[scores={random=252}] run give @s dark_oak_hanging_sign
execute at @s[scores={random=253}] run give @s dark_oak_leaves
execute at @s[scores={random=254}] run give @s dark_oak_log
execute at @s[scores={random=255}] run give @s dark_oak_planks
execute at @s[scores={random=256}] run give @s dark_oak_pressure_plate
execute at @s[scores={random=257}] run give @s dark_oak_sapling
execute at @s[scores={random=258}] run give @s dark_oak_sign
execute at @s[scores={random=259}] run give @s dark_oak_slab
execute at @s[scores={random=260}] run give @s dark_oak_stairs
execute at @s[scores={random=261}] run give @s dark_oak_trapdoor
execute at @s[scores={random=262}] run give @s dark_oak_wood
execute at @s[scores={random=263}] run give @s dark_prismarine_stairs
execute at @s[scores={random=264}] run give @s daylight_detector
execute at @s[scores={random=265}] run give @s dead_brain_coral
execute at @s[scores={random=266}] run give @s dead_brain_coral_block
execute at @s[scores={random=267}] run give @s dead_brain_coral_fan
execute at @s[scores={random=268}] run give @s dead_bubble_coral
execute at @s[scores={random=269}] run give @s dead_bubble_coral_block
execute at @s[scores={random=270}] run give @s dead_bubble_coral_fan
execute at @s[scores={random=271}] run give @s dead_fire_coral
execute at @s[scores={random=272}] run give @s dead_fire_coral_block
execute at @s[scores={random=273}] run give @s dead_fire_coral_fan
execute at @s[scores={random=274}] run give @s dead_horn_coral
execute at @s[scores={random=275}] run give @s dead_horn_coral_block
execute at @s[scores={random=276}] run give @s dead_horn_coral_fan
execute at @s[scores={random=277}] run give @s dead_tube_coral
execute at @s[scores={random=278}] run give @s dead_tube_coral_block
execute at @s[scores={random=279}] run give @s dead_tube_coral_fan
execute at @s[scores={random=280}] run give @s deadbush
execute at @s[scores={random=281}] run give @s decorated_pot
execute at @s[scores={random=282}] run give @s deepslate
execute at @s[scores={random=283}] run give @s deepslate_brick_slab
execute at @s[scores={random=284}] run give @s deepslate_brick_stairs
execute at @s[scores={random=285}] run give @s deepslate_brick_wall
execute at @s[scores={random=286}] run give @s deepslate_bricks
execute at @s[scores={random=287}] run give @s deepslate_coal_ore
execute at @s[scores={random=288}] run give @s deepslate_copper_ore
execute at @s[scores={random=289}] run give @s deepslate_diamond_ore
execute at @s[scores={random=290}] run give @s deepslate_emerald_ore
execute at @s[scores={random=291}] run give @s deepslate_gold_ore
execute at @s[scores={random=292}] run give @s deepslate_iron_ore
execute at @s[scores={random=293}] run give @s deepslate_lapis_ore
execute at @s[scores={random=294}] run give @s deepslate_redstone_ore
execute at @s[scores={random=295}] run give @s deepslate_tile_slab
execute at @s[scores={random=296}] run give @s deepslate_tile_stairs
execute at @s[scores={random=297}] run give @s deepslate_tile_wall
execute at @s[scores={random=298}] run give @s deepslate_tiles
execute at @s[scores={random=299}] run give @s detector_rail
execute at @s[scores={random=300}] run give @s diamond
execute at @s[scores={random=301}] run give @s diamond_axe
execute at @s[scores={random=302}] run give @s diamond_block
execute at @s[scores={random=303}] run give @s diamond_boots
execute at @s[scores={random=304}] run give @s diamond_chestplate
execute at @s[scores={random=305}] run give @s diamond_helmet
execute at @s[scores={random=306}] run give @s diamond_hoe
execute at @s[scores={random=307}] run give @s diamond_horse_armor
execute at @s[scores={random=308}] run give @s diamond_leggings
execute at @s[scores={random=309}] run give @s diamond_ore
execute at @s[scores={random=310}] run give @s diamond_pickaxe
execute at @s[scores={random=311}] run give @s diamond_shovel
execute at @s[scores={random=312}] run give @s diamond_sword
execute at @s[scores={random=313}] run give @s diorite
execute at @s[scores={random=314}] run give @s diorite_stairs
execute at @s[scores={random=315}] run give @s dirt
execute at @s[scores={random=316}] run give @s dirt_with_roots
execute at @s[scores={random=317}] run give @s disc_fragment_5
execute at @s[scores={random=318}] run give @s dispenser
execute at @s[scores={random=319}] run give @s dragon_breath
execute at @s[scores={random=320}] run give @s dragon_egg
execute at @s[scores={random=321}] run give @s dried_kelp
execute at @s[scores={random=322}] run give @s dried_kelp_block
execute at @s[scores={random=323}] run give @s dripstone_block
execute at @s[scores={random=324}] run give @s dropper
execute at @s[scores={random=325}] run give @s dune_armor_trim_smithing_template
execute at @s[scores={random=326}] run give @s echo_shard
execute at @s[scores={random=327}] run give @s egg
execute at @s[scores={random=328}] run give @s elytra
execute at @s[scores={random=329}] run give @s emerald
execute at @s[scores={random=330}] run give @s emerald_block
execute at @s[scores={random=331}] run give @s emerald_ore
execute at @s[scores={random=332}] run give @s empty_map
execute at @s[scores={random=333}] run give @s enchanted_golden_apple
execute at @s[scores={random=334}] run give @s enchanting_table
execute at @s[scores={random=335}] run give @s end_brick_stairs
execute at @s[scores={random=336}] run give @s end_bricks
execute at @s[scores={random=337}] run give @s end_crystal
execute at @s[scores={random=338}] run give @s end_portal_frame
execute at @s[scores={random=339}] run give @s end_rod
execute at @s[scores={random=340}] run give @s end_stone
execute at @s[scores={random=341}] run give @s ender_chest
execute at @s[scores={random=342}] run give @s ender_eye
execute at @s[scores={random=343}] run give @s ender_pearl
execute at @s[scores={random=344}] run give @s experience_bottle
execute at @s[scores={random=345}] run give @s explorer_pottery_sherd
execute at @s[scores={random=346}] run give @s eye_armor_trim_smithing_template
execute at @s[scores={random=347}] run give @s farmland
execute at @s[scores={random=348}] run give @s feather
execute at @s[scores={random=349}] run give @s fence
execute at @s[scores={random=350}] run give @s fence_gate
execute at @s[scores={random=351}] run give @s fermented_spider_eye
execute at @s[scores={random=352}] run give @s fern
execute at @s[scores={random=353}] run give @s field_masoned_banner_pattern
execute at @s[scores={random=354}] run give @s filled_map
execute at @s[scores={random=355}] run give @s fire_charge
execute at @s[scores={random=356}] run give @s fire_coral
execute at @s[scores={random=357}] run give @s fire_coral_block
execute at @s[scores={random=358}] run give @s fire_coral_fan
execute at @s[scores={random=359}] run give @s firework_rocket
execute at @s[scores={random=360}] run give @s firework_star
execute at @s[scores={random=361}] run give @s fishing_rod
execute at @s[scores={random=362}] run give @s fletching_table
execute at @s[scores={random=363}] run give @s flint
execute at @s[scores={random=364}] run give @s flint_and_steel
execute at @s[scores={random=365}] run give @s flow_armor_trim_smithing_template
execute at @s[scores={random=366}] run give @s flow_banner_pattern
execute at @s[scores={random=367}] run give @s flow_pottery_sherd
execute at @s[scores={random=368}] run give @s flower_banner_pattern
execute at @s[scores={random=369}] run give @s flower_pot
execute at @s[scores={random=370}] run give @s flowering_azalea
execute at @s[scores={random=371}] run give @s frame
execute at @s[scores={random=372}] run give @s friend_pottery_sherd
execute at @s[scores={random=373}] run give @s frog_spawn
execute at @s[scores={random=374}] run give @s frosted_ice
execute at @s[scores={random=375}] run give @s furnace
execute at @s[scores={random=376}] run give @s ghast_tear
execute at @s[scores={random=377}] run give @s gilded_blackstone
execute at @s[scores={random=378}] run give @s glass
execute at @s[scores={random=379}] run give @s glass_bottle
execute at @s[scores={random=380}] run give @s glass_pane
execute at @s[scores={random=381}] run give @s glistering_melon_slice
execute at @s[scores={random=382}] run give @s globe_banner_pattern
execute at @s[scores={random=383}] run give @s glow_frame
execute at @s[scores={random=384}] run give @s glow_ink_sac
execute at @s[scores={random=385}] run give @s glow_lichen
execute at @s[scores={random=386}] run give @s glowstone
execute at @s[scores={random=387}] run give @s glowstone_dust
execute at @s[scores={random=388}] run give @s goat_horn
execute at @s[scores={random=389}] run give @s gold_block
execute at @s[scores={random=390}] run give @s gold_ingot
execute at @s[scores={random=391}] run give @s gold_nugget
execute at @s[scores={random=392}] run give @s gold_ore
execute at @s[scores={random=393}] run give @s golden_apple
execute at @s[scores={random=394}] run give @s golden_axe
execute at @s[scores={random=395}] run give @s golden_boots
execute at @s[scores={random=396}] run give @s golden_carrot
execute at @s[scores={random=397}] run give @s golden_chestplate
execute at @s[scores={random=398}] run give @s golden_helmet
execute at @s[scores={random=399}] run give @s golden_hoe
execute at @s[scores={random=400}] run give @s golden_horse_armor
execute at @s[scores={random=401}] run give @s golden_leggings
execute at @s[scores={random=402}] run give @s golden_pickaxe
execute at @s[scores={random=403}] run give @s golden_rail
execute at @s[scores={random=404}] run give @s golden_shovel
execute at @s[scores={random=405}] run give @s golden_sword
execute at @s[scores={random=406}] run give @s granite
execute at @s[scores={random=407}] run give @s granite_stairs
execute at @s[scores={random=408}] run give @s grass_block
execute at @s[scores={random=409}] run give @s grass_path
execute at @s[scores={random=410}] run give @s gravel
execute at @s[scores={random=411}] run give @s gray_candle
execute at @s[scores={random=412}] run give @s glow_berries
execute at @s[scores={random=413}] run give @s gray_carpet
execute at @s[scores={random=414}] run give @s gray_concrete
execute at @s[scores={random=415}] run give @s gray_concrete_powder
execute at @s[scores={random=416}] run give @s gray_dye
execute at @s[scores={random=417}] run give @s gray_glazed_terracotta
execute at @s[scores={random=418}] run give @s gray_shulker_box
execute at @s[scores={random=419}] run give @s gray_stained_glass
execute at @s[scores={random=420}] run give @s gray_stained_glass_pane
execute at @s[scores={random=421}] run give @s gray_terracotta
execute at @s[scores={random=422}] run give @s gray_wool
execute at @s[scores={random=423}] run give @s green_candle
execute at @s[scores={random=424}] run give @s green_carpet
execute at @s[scores={random=425}] run give @s green_concrete
execute at @s[scores={random=426}] run give @s green_concrete_powder
execute at @s[scores={random=427}] run give @s green_dye
execute at @s[scores={random=428}] run give @s green_glazed_terracotta
execute at @s[scores={random=429}] run give @s green_shulker_box
execute at @s[scores={random=430}] run give @s green_stained_glass
execute at @s[scores={random=431}] run give @s green_stained_glass_pane
execute at @s[scores={random=432}] run give @s green_terracotta
execute at @s[scores={random=433}] run give @s green_wool
execute at @s[scores={random=434}] run give @s grindstone
execute at @s[scores={random=435}] run give @s gunpowder
execute at @s[scores={random=436}] run give @s guster_banner_pattern
execute at @s[scores={random=437}] run give @s guster_pottery_sherd
execute at @s[scores={random=438}] run give @s hanging_roots
execute at @s[scores={random=439}] run give @s hardened_clay
execute at @s[scores={random=440}] run give @s hay_block
execute at @s[scores={random=441}] run give @s heart_of_the_sea
execute at @s[scores={random=442}] run give @s heart_pottery_sherd
execute at @s[scores={random=443}] run give @s heartbreak_pottery_sherd
execute at @s[scores={random=444}] run give @s heavy_core
execute at @s[scores={random=445}] run give @s heavy_weighted_pressure_plate
execute at @s[scores={random=446}] run give @s honey_block
execute at @s[scores={random=447}] run give @s honey_bottle
execute at @s[scores={random=448}] run give @s honeycomb
execute at @s[scores={random=449}] run give @s honeycomb_block
execute at @s[scores={random=450}] run give @s hopper
execute at @s[scores={random=451}] run give @s hopper_minecart
execute at @s[scores={random=452}] run give @s horn_coral
execute at @s[scores={random=453}] run give @s horn_coral_block
execute at @s[scores={random=454}] run give @s horn_coral_fan
execute at @s[scores={random=455}] run give @s host_armor_trim_smithing_template
execute at @s[scores={random=456}] run give @s howl_pottery_sherd
execute at @s[scores={random=457}] run give @s ice
execute at @s[scores={random=458}] run give @s infested_deepslate
execute at @s[scores={random=459}] run give @s ink_sac
execute at @s[scores={random=460}] run give @s iron_axe
execute at @s[scores={random=461}] run give @s iron_bars
execute at @s[scores={random=462}] run give @s iron_block
execute at @s[scores={random=463}] run give @s iron_boots
execute at @s[scores={random=464}] run give @s iron_chestplate
execute at @s[scores={random=465}] run give @s iron_door
execute at @s[scores={random=466}] run give @s iron_helmet
execute at @s[scores={random=467}] run give @s iron_hoe
execute at @s[scores={random=468}] run give @s iron_horse_armor
execute at @s[scores={random=469}] run give @s iron_ingot
execute at @s[scores={random=470}] run give @s iron_leggings
execute at @s[scores={random=471}] run give @s iron_nugget
execute at @s[scores={random=472}] run give @s iron_ore
execute at @s[scores={random=473}] run give @s iron_pickaxe
execute at @s[scores={random=474}] run give @s iron_shovel
execute at @s[scores={random=475}] run give @s iron_sword
execute at @s[scores={random=476}] run give @s iron_trapdoor
execute at @s[scores={random=477}] run give @s jukebox
execute at @s[scores={random=478}] run give @s jungle_boat
execute at @s[scores={random=479}] run give @s jungle_button
execute at @s[scores={random=480}] run give @s jungle_chest_boat
execute at @s[scores={random=481}] run give @s jungle_door
execute at @s[scores={random=482}] run give @s jungle_fence
execute at @s[scores={random=483}] run give @s jungle_fence_gate
execute at @s[scores={random=484}] run give @s jungle_hanging_sign
execute at @s[scores={random=485}] run give @s jungle_leaves
execute at @s[scores={random=486}] run give @s jungle_log
execute at @s[scores={random=487}] run give @s jungle_planks
execute at @s[scores={random=488}] run give @s jungle_pressure_plate
execute at @s[scores={random=489}] run give @s jungle_sapling
execute at @s[scores={random=490}] run give @s jungle_sign
execute at @s[scores={random=491}] run give @s jungle_slab
execute at @s[scores={random=492}] run give @s jungle_stairs
execute at @s[scores={random=493}] run give @s jungle_trapdoor
execute at @s[scores={random=494}] run give @s jungle_wood
execute at @s[scores={random=495}] run give @s kelp
execute at @s[scores={random=496}] run give @s ladder
execute at @s[scores={random=497}] run give @s lantern
execute at @s[scores={random=498}] run give @s lapis_block
execute at @s[scores={random=499}] run give @s lapis_lazuli
execute at @s[scores={random=500}] run give @s lapis_ore
execute at @s[scores={random=501}] run give @s large_amethyst_bud
execute at @s[scores={random=502}] run give @s large_fern
execute at @s[scores={random=503}] run give @s lever
execute at @s[scores={random=504}] run give @s lava_bucket
execute at @s[scores={random=505}] run give @s lead
execute at @s[scores={random=506}] run give @s leather
execute at @s[scores={random=507}] run give @s leather_boots
execute at @s[scores={random=508}] run give @s leather_chestplate
execute at @s[scores={random=509}] run give @s leather_helmet
execute at @s[scores={random=510}] run give @s leather_horse_armor
execute at @s[scores={random=511}] run give @s leather_leggings
execute at @s[scores={random=512}] run give @s light_blue_candle
execute at @s[scores={random=513}] run give @s lectern
execute at @s[scores={random=514}] run give @s light_blue_carpet
execute at @s[scores={random=515}] run give @s light_blue_concrete
execute at @s[scores={random=516}] run give @s light_blue_concrete_powder
execute at @s[scores={random=517}] run give @s light_blue_dye
execute at @s[scores={random=518}] run give @s light_blue_glazed_terracotta
execute at @s[scores={random=519}] run give @s light_blue_shulker_box
execute at @s[scores={random=520}] run give @s light_blue_stained_glass
execute at @s[scores={random=521}] run give @s light_blue_stained_glass_pane
execute at @s[scores={random=522}] run give @s light_blue_terracotta
execute at @s[scores={random=523}] run give @s light_blue_wool
execute at @s[scores={random=524}] run give @s light_gray_candle
execute at @s[scores={random=525}] run give @s light_gray_carpet
execute at @s[scores={random=526}] run give @s light_gray_concrete
execute at @s[scores={random=527}] run give @s light_gray_concrete_powder
execute at @s[scores={random=528}] run give @s light_gray_dye
execute at @s[scores={random=529}] run give @s light_gray_shulker_box
execute at @s[scores={random=530}] run give @s light_gray_stained_glass
execute at @s[scores={random=531}] run give @s light_gray_stained_glass_pane
execute at @s[scores={random=532}] run give @s light_gray_terracotta
execute at @s[scores={random=533}] run give @s light_gray_wool
execute at @s[scores={random=534}] run give @s light_weighted_pressure_plate
execute at @s[scores={random=535}] run give @s lightning_rod
execute at @s[scores={random=536}] run give @s lilac
execute at @s[scores={random=537}] run give @s lily_of_the_valley
execute at @s[scores={random=538}] run give @s lime_candle
execute at @s[scores={random=539}] run give @s lime_carpet
execute at @s[scores={random=540}] run give @s lime_concrete
execute at @s[scores={random=541}] run give @s lime_concrete_powder
execute at @s[scores={random=542}] run give @s lime_dye
execute at @s[scores={random=543}] run give @s lime_glazed_terracotta
execute at @s[scores={random=544}] run give @s lime_shulker_box
execute at @s[scores={random=545}] run give @s lime_stained_glass
execute at @s[scores={random=546}] run give @s lime_stained_glass_pane
execute at @s[scores={random=547}] run give @s lime_terracotta
execute at @s[scores={random=548}] run give @s lime_wool
execute at @s[scores={random=549}] run give @s lingering_potion
execute at @s[scores={random=550}] run give @s lit_pumpkin
execute at @s[scores={random=551}] run give @s lodestone
execute at @s[scores={random=552}] run give @s lodestone_compass
execute at @s[scores={random=553}] run give @s loom
execute at @s[scores={random=554}] run give @s mace
execute at @s[scores={random=555}] run give @s magenta_candle
execute at @s[scores={random=556}] run give @s magenta_carpet
execute at @s[scores={random=557}] run give @s magenta_concrete
execute at @s[scores={random=558}] run give @s magenta_concrete_powder
execute at @s[scores={random=559}] run give @s magenta_dye
execute at @s[scores={random=560}] run give @s magenta_glazed_terracotta
execute at @s[scores={random=561}] run give @s magenta_shulker_box
execute at @s[scores={random=562}] run give @s magenta_stained_glass
execute at @s[scores={random=563}] run give @s magenta_stained_glass_pane
execute at @s[scores={random=564}] run give @s magenta_terracotta
execute at @s[scores={random=565}] run give @s magenta_wool
execute at @s[scores={random=566}] run give @s magma
execute at @s[scores={random=567}] run give @s magma_cream
execute at @s[scores={random=568}] run give @s mangrove_boat
execute at @s[scores={random=569}] run give @s mangrove_button
execute at @s[scores={random=570}] run give @s mangrove_chest_boat
execute at @s[scores={random=571}] run give @s mangrove_door
execute at @s[scores={random=572}] run give @s mangrove_fence
execute at @s[scores={random=573}] run give @s mangrove_fence_gate
execute at @s[scores={random=574}] run give @s mangrove_hanging_sign
execute at @s[scores={random=575}] run give @s mangrove_leaves
execute at @s[scores={random=576}] run give @s mangrove_log
execute at @s[scores={random=577}] run give @s mangrove_planks
execute at @s[scores={random=578}] run give @s mangrove_pressure_plate
execute at @s[scores={random=579}] run give @s mangrove_propagule
execute at @s[scores={random=580}] run give @s mangrove_roots
execute at @s[scores={random=581}] run give @s mangrove_sign
execute at @s[scores={random=582}] run give @s mangrove_slab
execute at @s[scores={random=583}] run give @s mangrove_stairs
execute at @s[scores={random=584}] run give @s mangrove_trapdoor
execute at @s[scores={random=585}] run give @s mangrove_wood
execute at @s[scores={random=586}] run give @s mycelium
execute at @s[scores={random=587}] run give @s medium_amethyst_bud
execute at @s[scores={random=588}] run give @s melon_block
execute at @s[scores={random=589}] run give @s melon_seeds
execute at @s[scores={random=590}] run give @s melon_slice
execute at @s[scores={random=591}] run give @s milk_bucket
execute at @s[scores={random=592}] run give @s minecart
execute at @s[scores={random=593}] run give @s mutton
execute at @s[scores={random=594}] run give @s music_disc_ward
execute at @s[scores={random=595}] run give @s music_disc_wait
execute at @s[scores={random=596}] run give @s music_disc_strad
execute at @s[scores={random=597}] run give @s music_disc_stal
execute at @s[scores={random=598}] run give @s music_disc_relic
execute at @s[scores={random=599}] run give @s music_disc_precipice
execute at @s[scores={random=600}] run give @s music_disc_pigstep
execute at @s[scores={random=601}] run give @s music_disc_otherside
execute at @s[scores={random=602}] run give @s music_disc_mellohi
execute at @s[scores={random=603}] run give @s music_disc_mall
execute at @s[scores={random=604}] run give @s music_disc_far
execute at @s[scores={random=605}] run give @s music_disc_creator_music_box
execute at @s[scores={random=606}] run give @s music_disc_creator
execute at @s[scores={random=607}] run give @s music_disc_chirp
execute at @s[scores={random=608}] run give @s music_disc_cat
execute at @s[scores={random=609}] run give @s music_disc_blocks
execute at @s[scores={random=610}] run give @s music_disc_5
execute at @s[scores={random=611}] run give @s music_disc_13
execute at @s[scores={random=612}] run give @s music_disc_11
execute at @s[scores={random=613}] run give @s mushroom_stew
execute at @s[scores={random=614}] run give @s muddy_mangrove_roots
execute at @s[scores={random=615}] run give @s mud_bricks
execute at @s[scores={random=616}] run give @s mud_brick_wall
execute at @s[scores={random=617}] run give @s mud_brick_stairs
execute at @s[scores={random=618}] run give @s mud_brick_slab
execute at @s[scores={random=619}] run give @s mud
execute at @s[scores={random=620}] run give @s mourner_pottery_sherd
execute at @s[scores={random=621}] run give @s mossy_stone_brick_stairs
execute at @s[scores={random=622}] run give @s mossy_cobblestone_stairs
execute at @s[scores={random=623}] run give @s mossy_cobblestone
execute at @s[scores={random=624}] run give @s moss_carpet
execute at @s[scores={random=625}] run give @s moss_block
execute at @s[scores={random=626}] run give @s monster_egg
execute at @s[scores={random=627}] run give @s mojang_banner_pattern
execute at @s[scores={random=628}] run give @s mob_spawner
execute at @s[scores={random=629}] run give @s miner_pottery_sherd
execute at @s[scores={random=630}] run give @s noteblock
execute at @s[scores={random=631}] run give @s normal_stone_stairs
execute at @s[scores={random=632}] run give @s netherrack
execute at @s[scores={random=633}] run give @s netherite_upgrade_smithing_template
execute at @s[scores={random=634}] run give @s netherite_shovel
execute at @s[scores={random=635}] run give @s netherite_scrap
execute at @s[scores={random=636}] run give @s netherite_pickaxe
execute at @s[scores={random=637}] run give @s netherite_leggings
execute at @s[scores={random=638}] run give @s netherite_ingot
execute at @s[scores={random=639}] run give @s netherite_hoe
execute at @s[scores={random=640}] run give @s netherite_helmet
execute at @s[scores={random=641}] run give @s netherite_chestplate
execute at @s[scores={random=642}] run give @s netherite_boots
execute at @s[scores={random=643}] run give @s netherite_block
execute at @s[scores={random=644}] run give @s netherite_axe
execute at @s[scores={random=645}] run give @s netherbrick
execute at @s[scores={random=646}] run give @s nether_wart_block
execute at @s[scores={random=647}] run give @s nether_wart
execute at @s[scores={random=648}] run give @s nether_star
execute at @s[scores={random=649}] run give @s nether_sprouts
execute at @s[scores={random=650}] run give @s nether_gold_ore
execute at @s[scores={random=651}] run give @s nether_brick_stairs
execute at @s[scores={random=652}] run give @s nether_brick_slab
execute at @s[scores={random=653}] run give @s nether_brick_fence
execute at @s[scores={random=654}] run give @s nether_brick
execute at @s[scores={random=655}] run give @s nautilus_shell
execute at @s[scores={random=656}] run give @s name_tag
execute at @s[scores={random=657}] run give @s oxeye_daisy
execute at @s[scores={random=658}] run give @s orange_wool
execute at @s[scores={random=659}] run give @s orange_tulip
execute at @s[scores={random=660}] run give @s orange_terracotta
execute at @s[scores={random=661}] run give @s orange_stained_glass_pane
execute at @s[scores={random=662}] run give @s orange_stained_glass
execute at @s[scores={random=663}] run give @s orange_shulker_box
execute at @s[scores={random=664}] run give @s orange_glazed_terracotta
execute at @s[scores={random=665}] run give @s orange_dye
execute at @s[scores={random=666}] run give @s orange_concrete_powder
execute at @s[scores={random=667}] run give @s orange_concrete
execute at @s[scores={random=668}] run give @s orange_carpet
execute at @s[scores={random=669}] run give @s orange_candle
execute at @s[scores={random=670}] run give @s ominous_trial_key
execute at @s[scores={random=671}] run give @s ominous_bottle
execute at @s[scores={random=672}] run give @s ochre_froglight
execute at @s[scores={random=673}] run give @s obsidian
execute at @s[scores={random=674}] run give @s observer
execute at @s[scores={random=675}] run give @s oak_wood
execute at @s[scores={random=676}] run give @s oak_stairs
execute at @s[scores={random=677}] run give @s oak_slab
execute at @s[scores={random=678}] run give @s oak_sign
execute at @s[scores={random=679}] run give @s oak_sapling
execute at @s[scores={random=680}] run give @s oak_planks
execute at @s[scores={random=681}] run give @s oak_log
execute at @s[scores={random=682}] run give @s oak_leaves
execute at @s[scores={random=683}] run give @s oak_hanging_sign
execute at @s[scores={random=684}] run give @s oak_fence
execute at @s[scores={random=685}] run give @s oak_chest_boat
execute at @s[scores={random=686}] run give @s oak_boat
execute at @s[scores={random=687}] run give @s purpur_stairs
execute at @s[scores={random=688}] run give @s purpur_block
execute at @s[scores={random=689}] run give @s purple_wool
execute at @s[scores={random=690}] run give @s purple_terracotta
execute at @s[scores={random=691}] run give @s purple_stained_glass_pane
execute at @s[scores={random=692}] run give @s purple_stained_glass
execute at @s[scores={random=693}] run give @s purple_shulker_box
execute at @s[scores={random=694}] run give @s purple_glazed_terracotta
execute at @s[scores={random=695}] run give @s purple_dye
execute at @s[scores={random=696}] run give @s purple_concrete_powder
execute at @s[scores={random=697}] run give @s purple_concrete
execute at @s[scores={random=698}] run give @s purple_carpet
execute at @s[scores={random=699}] run give @s purple_candle
execute at @s[scores={random=700}] run give @s pumpkin_seeds
execute at @s[scores={random=701}] run give @s pumpkin_pie
execute at @s[scores={random=702}] run give @s pumpkin
execute at @s[scores={random=703}] run give @s pufferfish_bucket
execute at @s[scores={random=704}] run give @s pufferfish
execute at @s[scores={random=705}] run give @s prize_pottery_sherd
execute at @s[scores={random=706}] run give @s prismarine_stairs
execute at @s[scores={random=707}] run give @s prismarine_shard
execute at @s[scores={random=708}] run give @s prismarine_crystals
execute at @s[scores={random=709}] run give @s prismarine_bricks_stairs
execute at @s[scores={random=710}] run give @s prismarine
execute at @s[scores={random=711}] run give @s powder_snow_bucket
execute at @s[scores={random=712}] run give @s potion
execute at @s[scores={random=713}] run give @s potato
execute at @s[scores={random=714}] run give @s porkchop
execute at @s[scores={random=715}] run give @s poppy
execute at @s[scores={random=716}] run give @s popped_chorus_fruit
execute at @s[scores={random=717}] run give @s polished_tuff_wall
execute at @s[scores={random=718}] run give @s polished_tuff_stairs
execute at @s[scores={random=719}] run give @s polished_tuff_slab
execute at @s[scores={random=720}] run give @s polished_tuff
execute at @s[scores={random=721}] run give @s polished_granite_stairs
execute at @s[scores={random=722}] run give @s polished_granite
execute at @s[scores={random=723}] run give @s polished_diorite_stairs
execute at @s[scores={random=724}] run give @s polished_diorite
execute at @s[scores={random=725}] run give @s polished_deepslate_wall
execute at @s[scores={random=726}] run give @s polished_deepslate_stairs
execute at @s[scores={random=727}] run give @s polished_deepslate_slab
execute at @s[scores={random=728}] run give @s polished_deepslate
execute at @s[scores={random=729}] run give @s polished_blackstone_wall
execute at @s[scores={random=730}] run give @s polished_blackstone_stairs
execute at @s[scores={random=731}] run give @s polished_blackstone_slab
execute at @s[scores={random=732}] run give @s polished_blackstone_pressure_plate
execute at @s[scores={random=733}] run give @s polished_blackstone_button
execute at @s[scores={random=734}] run give @s polished_blackstone_bricks
execute at @s[scores={random=735}] run give @s polished_blackstone_brick_wall
execute at @s[scores={random=736}] run give @s polished_blackstone_brick_stairs
execute at @s[scores={random=737}] run give @s polished_blackstone_brick_slab
execute at @s[scores={random=738}] run give @s polished_blackstone
execute at @s[scores={random=739}] run give @s polished_basalt
execute at @s[scores={random=740}] run give @s polished_andesite_stairs
execute at @s[scores={random=741}] run give @s polished_andesite
execute at @s[scores={random=742}] run give @s poisonous_potato
execute at @s[scores={random=743}] run give @s pointed_dripstone
execute at @s[scores={random=744}] run give @s podzol
execute at @s[scores={random=745}] run give @s plenty_pottery_sherd
execute at @s[scores={random=746}] run give @s pitcher_pod
execute at @s[scores={random=747}] run give @s pitcher_plant
execute at @s[scores={random=748}] run give @s piston
execute at @s[scores={random=749}] run give @s pink_wool
execute at @s[scores={random=750}] run give @s pink_tulip
execute at @s[scores={random=751}] run give @s pink_terracotta
execute at @s[scores={random=752}] run give @s pink_stained_glass_pane
execute at @s[scores={random=753}] run give @s pink_stained_glass
execute at @s[scores={random=754}] run give @s pink_shulker_box
execute at @s[scores={random=755}] run give @s pink_petals
execute at @s[scores={random=756}] run give @s pink_glazed_terracotta
execute at @s[scores={random=757}] run give @s pink_dye
execute at @s[scores={random=758}] run give @s pink_concrete_powder
execute at @s[scores={random=759}] run give @s pink_concrete
execute at @s[scores={random=760}] run give @s pink_carpet
execute at @s[scores={random=761}] run give @s pink_candle
execute at @s[scores={random=762}] run give @s piglin_banner_pattern
execute at @s[scores={random=763}] run give @s phantom_membrane
execute at @s[scores={random=764}] run give @s petrified_oak_slab
execute at @s[scores={random=765}] run give @s peony
execute at @s[scores={random=766}] run give @s pearlescent_froglight
execute at @s[scores={random=767}] run give @s paper
execute at @s[scores={random=768}] run give @s painting
execute at @s[scores={random=769}] run give @s packed_mud
execute at @s[scores={random=770}] run give @s packed_ice
execute at @s[scores={random=771}] run give @s quartz_stairs
execute at @s[scores={random=772}] run give @s quartz_slab
execute at @s[scores={random=773}] run give @s quartz_ore
execute at @s[scores={random=774}] run give @s quartz_bricks
execute at @s[scores={random=775}] run give @s quartz_block
execute at @s[scores={random=776}] run give @s quartz
execute at @s[scores={random=777}] run give @s rotten_flesh
execute at @s[scores={random=778}] run give @s rose_bush
execute at @s[scores={random=779}] run give @s rib_armor_trim_smithing_template
execute at @s[scores={random=780}] run give @s respawn_anchor
execute at @s[scores={random=781}] run give @s repeater
execute at @s[scores={random=782}] run give @s reinforced_deepslate
execute at @s[scores={random=783}] run give @s redstone_torch
execute at @s[scores={random=784}] run give @s redstone_ore
execute at @s[scores={random=785}] run give @s redstone_lamp
execute at @s[scores={random=786}] run give @s redstone_block
execute at @s[scores={random=787}] run give @s redstone
execute at @s[scores={random=788}] run give @s red_wool
execute at @s[scores={random=789}] run give @s red_tulip
execute at @s[scores={random=790}] run give @s red_terracotta
execute at @s[scores={random=791}] run give @s red_stained_glass_pane
execute at @s[scores={random=792}] run give @s red_stained_glass
execute at @s[scores={random=793}] run give @s red_shulker_box
execute at @s[scores={random=794}] run give @s red_sandstone_stairs
execute at @s[scores={random=795}] run give @s red_sandstone
execute at @s[scores={random=796}] run give @s red_nether_brick_stairs
execute at @s[scores={random=797}] run give @s red_nether_brick
execute at @s[scores={random=798}] run give @s red_mushroom_block
execute at @s[scores={random=799}] run give @s red_mushroom
execute at @s[scores={random=800}] run give @s red_glazed_terracotta
execute at @s[scores={random=801}] run give @s red_dye
execute at @s[scores={random=802}] run give @s red_concrete_powder
execute at @s[scores={random=803}] run give @s red_concrete
execute at @s[scores={random=804}] run give @s red_carpet
execute at @s[scores={random=805}] run give @s red_candle
execute at @s[scores={random=806}] run give @s recovery_compass
execute at @s[scores={random=807}] run give @s raw_iron_block
execute at @s[scores={random=808}] run give @s raw_iron
execute at @s[scores={random=809}] run give @s raw_gold_block
execute at @s[scores={random=810}] run give @s raw_gold
execute at @s[scores={random=811}] run give @s raw_copper_block
execute at @s[scores={random=812}] run give @s raw_copper
execute at @s[scores={random=813}] run give @s raiser_armor_trim_smithing_template
execute at @s[scores={random=814}] run give @s rail
execute at @s[scores={random=815}] run give @s rabbit_stew
execute at @s[scores={random=816}] run give @s rabbit_hide
execute at @s[scores={random=817}] run give @s rabbit_foot
execute at @s[scores={random=818}] run give @s rabbit
execute at @s[scores={random=819}] run give @s sweet_berries
execute at @s[scores={random=820}] run give @s suspicious_stew
execute at @s[scores={random=821}] run give @s suspicious_sand
execute at @s[scores={random=822}] run give @s suspicious_gravel
execute at @s[scores={random=823}] run give @s sunflower
execute at @s[scores={random=824}] run give @s sugar_cane
execute at @s[scores={random=825}] run give @s sugar
execute at @s[scores={random=826}] run give @s stripped_warped_stem
execute at @s[scores={random=827}] run give @s stripped_warped_hyphae
execute at @s[scores={random=828}] run give @s stripped_spruce_wood
execute at @s[scores={random=829}] run give @s stripped_spruce_log
execute at @s[scores={random=830}] run give @s stripped_oak_wood
execute at @s[scores={random=831}] run give @s stripped_oak_log
execute at @s[scores={random=832}] run give @s stripped_mangrove_wood
execute at @s[scores={random=833}] run give @s stripped_mangrove_log
execute at @s[scores={random=834}] run give @s stripped_jungle_wood
execute at @s[scores={random=835}] run give @s stripped_jungle_log
execute at @s[scores={random=836}] run give @s stripped_dark_oak_wood
execute at @s[scores={random=837}] run give @s stripped_dark_oak_log
execute at @s[scores={random=838}] run give @s stripped_crimson_stem
execute at @s[scores={random=839}] run give @s stripped_crimson_hyphae
execute at @s[scores={random=840}] run give @s stripped_cherry_wood
execute at @s[scores={random=841}] run give @s stripped_cherry_log
execute at @s[scores={random=842}] run give @s stripped_birch_wood
execute at @s[scores={random=843}] run give @s stripped_birch_log
execute at @s[scores={random=844}] run give @s stripped_bamboo_block
execute at @s[scores={random=845}] run give @s stripped_acacia_wood
execute at @s[scores={random=846}] run give @s stripped_acacia_log
execute at @s[scores={random=847}] run give @s string
execute at @s[scores={random=848}] run give @s stonecutter_block
execute at @s[scores={random=849}] run give @s stonebrick
execute at @s[scores={random=850}] run give @s stone_sword
execute at @s[scores={random=851}] run give @s stone_stairs
execute at @s[scores={random=852}] run give @s stone_shovel
execute at @s[scores={random=853}] run give @s stone_pressure_plate
execute at @s[scores={random=854}] run give @s stone_pickaxe
execute at @s[scores={random=855}] run give @s stone_hoe
execute at @s[scores={random=856}] run give @s stone_button
execute at @s[scores={random=857}] run give @s stone_brick_stairs
execute at @s[scores={random=858}] run give @s stone_brick_slab
execute at @s[scores={random=859}] run give @s stone_block_slab4
execute at @s[scores={random=860}] run give @s stone_block_slab3
execute at @s[scores={random=861}] run give @s stone_block_slab2
execute at @s[scores={random=862}] run give @s stone_axe
execute at @s[scores={random=863}] run give @s stone
execute at @s[scores={random=864}] run give @s sticky_piston
execute at @s[scores={random=865}] run give @s stick
execute at @s[scores={random=866}] run give @s spyglass
execute at @s[scores={random=867}] run give @s spruce_wood
execute at @s[scores={random=868}] run give @s spruce_trapdoor
execute at @s[scores={random=869}] run give @s spruce_stairs
execute at @s[scores={random=870}] run give @s spruce_slab
execute at @s[scores={random=871}] run give @s spruce_sign
execute at @s[scores={random=872}] run give @s spruce_sapling
execute at @s[scores={random=873}] run give @s spruce_pressure_plate
execute at @s[scores={random=874}] run give @s spruce_planks
execute at @s[scores={random=875}] run give @s spruce_log
execute at @s[scores={random=876}] run give @s spruce_leaves
execute at @s[scores={random=877}] run give @s spruce_hanging_sign
execute at @s[scores={random=878}] run give @s spruce_fence_gate
execute at @s[scores={random=879}] run give @s spruce_fence
execute at @s[scores={random=880}] run give @s spruce_door
execute at @s[scores={random=881}] run give @s spruce_chest_boat
execute at @s[scores={random=882}] run give @s spruce_button
execute at @s[scores={random=883}] run give @s spruce_boat
execute at @s[scores={random=884}] run give @s spore_blossom
execute at @s[scores={random=885}] run give @s sponge
execute at @s[scores={random=886}] run give @s splash_potion
execute at @s[scores={random=887}] run give @s spire_armor_trim_smithing_template
execute at @s[scores={random=888}] run give @s spider_eye
execute at @s[scores={random=889}] run give @s soul_torch
execute at @s[scores={random=890}] run give @s soul_soil
execute at @s[scores={random=891}] run give @s soul_sand
execute at @s[scores={random=892}] run give @s soul_lantern
execute at @s[scores={random=893}] run give @s soul_campfire
execute at @s[scores={random=894}] run give @s snowball
execute at @s[scores={random=895}] run give @s snow_layer
execute at @s[scores={random=896}] run give @s snow
execute at @s[scores={random=897}] run give @s snout_armor_trim_smithing_template
execute at @s[scores={random=898}] run give @s snort_pottery_sherd
execute at @s[scores={random=899}] run give @s sniffer_egg
execute at @s[scores={random=900}] run give @s smooth_stone_slab
execute at @s[scores={random=901}] run give @s smooth_sandstone_stairs
execute at @s[scores={random=902}] run give @s smooth_stone
execute at @s[scores={random=903}] run give @s smooth_red_sandstone_stairs
execute at @s[scores={random=904}] run give @s smooth_quartz_stairs
execute at @s[scores={random=905}] run give @s smooth_basalt
execute at @s[scores={random=906}] run give @s smoker
execute at @s[scores={random=907}] run give @s smithing_table
execute at @s[scores={random=908}] run give @s small_dripleaf_block
execute at @s[scores={random=909}] run give @s small_amethyst_bud
execute at @s[scores={random=910}] run give @s slime_ball
execute at @s[scores={random=911}] run give @s slime
execute at @s[scores={random=912}] run give @s skull_pottery_sherd
execute at @s[scores={random=913}] run give @s skull_banner_pattern
execute at @s[scores={random=914}] run give @s skull
execute at @s[scores={random=915}] run give @s silver_glazed_terracotta
execute at @s[scores={random=916}] run give @s silence_armor_trim_smithing_template
execute at @s[scores={random=917}] run give @s shulker_shell
execute at @s[scores={random=918}] run give @s shroomlight
execute at @s[scores={random=919}] run give @s short_grass
execute at @s[scores={random=920}] run give @s shield
execute at @s[scores={random=921}] run give @s shelter_pottery_sherd
execute at @s[scores={random=922}] run give @s shears
execute at @s[scores={random=923}] run give @s sheaf_pottery_sherd
execute at @s[scores={random=924}] run give @s shaper_armor_trim_smithing_template
execute at @s[scores={random=925}] run give @s sentry_armor_trim_smithing_template
execute at @s[scores={random=926}] run give @s seagrass
execute at @s[scores={random=927}] run give @s sea_pickle
execute at @s[scores={random=928}] run give @s sea_lantern
execute at @s[scores={random=929}] run give @s sculk_vein
execute at @s[scores={random=930}] run give @s sculk_shrieker
execute at @s[scores={random=931}] run give @s sculk_sensor
execute at @s[scores={random=932}] run give @s sculk_catalyst
execute at @s[scores={random=933}] run give @s sculk
execute at @s[scores={random=934}] run give @s scrape_pottery_sherd
execute at @s[scores={random=935}] run give @s scaffolding
execute at @s[scores={random=936}] run give @s sandstone_stairs
execute at @s[scores={random=937}] run give @s sandstone_slab
execute at @s[scores={random=938}] run give @s sandstone
execute at @s[scores={random=939}] run give @s sand
execute at @s[scores={random=940}] run give @s salmon_bucket
execute at @s[scores={random=941}] run give @s salmon
execute at @s[scores={random=942}] run give @s saddle
execute at @s[scores={random=943}] run give @s twisting_vines
execute at @s[scores={random=944}] run give @s turtle_scute
execute at @s[scores={random=945}] run give @s turtle_helmet
execute at @s[scores={random=946}] run give @s turtle_egg
execute at @s[scores={random=947}] run give @s tuff_wall
execute at @s[scores={random=948}] run give @s tuff_stairs
execute at @s[scores={random=949}] run give @s tuff_slab
execute at @s[scores={random=950}] run give @s tuff_bricks
execute at @s[scores={random=951}] run give @s tuff_brick_wall
execute at @s[scores={random=952}] run give @s tuff_brick_stairs
execute at @s[scores={random=953}] run give @s tuff_brick_slab
execute at @s[scores={random=954}] run give @s tuff
execute at @s[scores={random=955}] run give @s tube_coral_fan
execute at @s[scores={random=956}] run give @s tube_coral_block
execute at @s[scores={random=957}] run give @s tube_coral
execute at @s[scores={random=958}] run give @s tropical_fish_bucket
execute at @s[scores={random=959}] run give @s tropical_fish
execute at @s[scores={random=960}] run give @s tripwire_hook
execute at @s[scores={random=961}] run give @s trident
execute at @s[scores={random=962}] run give @s trial_spawner
execute at @s[scores={random=963}] run give @s trial_key
execute at @s[scores={random=964}] run give @s trapped_chest
execute at @s[scores={random=965}] run give @s trapdoor
execute at @s[scores={random=966}] run give @s totem_of_undying
execute at @s[scores={random=967}] run give @s torchflower_seeds
execute at @s[scores={random=968}] run give @s torchflower
execute at @s[scores={random=969}] run give @s torch
execute at @s[scores={random=970}] run give @s tnt_minecart
execute at @s[scores={random=971}] run give @s tnt
execute at @s[scores={random=972}] run give @s tinted_glass
execute at @s[scores={random=973}] run give @s tide_armor_trim_smithing_template
execute at @s[scores={random=974}] run give @s target
execute at @s[scores={random=975}] run give @s tall_grass
execute at @s[scores={random=976}] run give @s tadpole_bucket
execute at @s[scores={random=977}] run give @s undyed_shulker_box
execute at @s[scores={random=978}] run give @s vine
execute at @s[scores={random=979}] run give @s vex_armor_trim_smithing_template
execute at @s[scores={random=980}] run give @s verdant_froglight
execute at @s[scores={random=981}] run give @s vault
execute at @s[scores={random=982}] run give @s writable_book
execute at @s[scores={random=983}] run give @s wooden_sword
execute at @s[scores={random=984}] run give @s wooden_slab
execute at @s[scores={random=985}] run give @s wooden_shovel
execute at @s[scores={random=986}] run give @s wooden_pressure_plate
execute at @s[scores={random=987}] run give @s wooden_pickaxe
execute at @s[scores={random=988}] run give @s wooden_hoe
execute at @s[scores={random=989}] run give @s wooden_door
execute at @s[scores={random=990}] run give @s wooden_button
execute at @s[scores={random=991}] run give @s wooden_axe
execute at @s[scores={random=992}] run give @s wolf_armor
execute at @s[scores={random=993}] run give @s wither_rose
execute at @s[scores={random=994}] run give @s wind_charge
execute at @s[scores={random=995}] run give @s wild_armor_trim_smithing_template
execute at @s[scores={random=996}] run give @s white_wool
execute at @s[scores={random=997}] run give @s white_tulip
execute at @s[scores={random=998}] run give @s white_terracotta
execute at @s[scores={random=999}] run give @s white_stained_glass_pane
execute at @s[scores={random=1000}] run give @s white_stained_glass
execute at @s[scores={random=1001}] run give @s white_shulker_box
execute at @s[scores={random=1002}] run give @s white_glazed_terracotta
execute at @s[scores={random=1003}] run give @s white_dye
execute at @s[scores={random=1004}] run give @s white_concrete_powder
execute at @s[scores={random=1005}] run give @s white_concrete
execute at @s[scores={random=1006}] run give @s white_carpet
execute at @s[scores={random=1007}] run give @s white_candle
execute at @s[scores={random=1008}] run give @s wheat_seeds
execute at @s[scores={random=1009}] run give @s wheat
execute at @s[scores={random=1010}] run give @s weeping_vines
execute at @s[scores={random=1011}] run give @s web
execute at @s[scores={random=1012}] run give @s wayfinder_armor_trim_smithing_template
execute at @s[scores={random=1013}] run give @s waterlily
execute at @s[scores={random=1014}] run give @s water_bucket
execute at @s[scores={random=1015}] run give @s warped_wart_block
execute at @s[scores={random=1016}] run give @s warped_trapdoor
execute at @s[scores={random=1017}] run give @s warped_stem
execute at @s[scores={random=1018}] run give @s warped_stairs
execute at @s[scores={random=1019}] run give @s warped_slab
execute at @s[scores={random=1020}] run give @s warped_sign
execute at @s[scores={random=1021}] run give @s warped_roots
execute at @s[scores={random=1022}] run give @s warped_pressure_plate
execute at @s[scores={random=1023}] run give @s warped_planks
execute at @s[scores={random=1024}] run give @s warped_nylium
execute at @s[scores={random=1025}] run give @s warped_hyphae
execute at @s[scores={random=1026}] run give @s warped_hanging_sign
execute at @s[scores={random=1027}] run give @s warped_fungus_on_a_stick
execute at @s[scores={random=1028}] run give @s warped_fungus
execute at @s[scores={random=1029}] run give @s warped_fence_gate
execute at @s[scores={random=1030}] run give @s warped_fence
execute at @s[scores={random=1031}] run give @s warped_door
execute at @s[scores={random=1032}] run give @s warped_button
execute at @s[scores={random=1033}] run give @s ward_armor_trim_smithing_template
execute at @s[scores={random=1034}] run give @s yellow_wool
execute at @s[scores={random=1035}] run give @s yellow_terracotta
execute at @s[scores={random=1036}] run give @s yellow_stained_glass_pane
execute at @s[scores={random=1037}] run give @s yellow_stained_glass
execute at @s[scores={random=1038}] run give @s yellow_shulker_box
execute at @s[scores={random=1039}] run give @s yellow_glazed_terracotta
execute at @s[scores={random=1040}] run give @s yellow_dye
execute at @s[scores={random=1041}] run give @s yellow_concrete_powder
execute at @s[scores={random=1042}] run give @s yellow_concrete
execute at @s[scores={random=1043}] run give @s yellow_carpet
execute at @s[scores={random=1044}] run give @s yellow_candle
execute at @s[scores={random=1045}] run give @s bed 1 1
execute at @s[scores={random=1046}] run give @s bed 1 2
execute at @s[scores={random=1047}] run give @s bed 1 3
execute at @s[scores={random=1048}] run give @s bed 1 4
execute at @s[scores={random=1049}] run give @s bed 1 5
execute at @s[scores={random=1050}] run give @s bed 1 6
execute at @s[scores={random=1051}] run give @s bed 1 7
execute at @s[scores={random=1052}] run give @s bed 1 8
execute at @s[scores={random=1053}] run give @s bed 1 9
execute at @s[scores={random=1054}] run give @s bed 1 10
execute at @s[scores={random=1055}] run give @s bed 1 11
execute at @s[scores={random=1056}] run give @s bed 1 12
execute at @s[scores={random=1057}] run give @s bed 1 13
execute at @s[scores={random=1058}] run give @s bed 1 14
execute at @s[scores={random=1059}] run give @s bed 1 15
execute at @s[scores={random=1060}] run give @s ominous_bottle 1 1
execute at @s[scores={random=1061}] run give @s ominous_bottle 1 2
execute at @s[scores={random=1062}] run give @s ominous_bottle 1 3
execute at @s[scores={random=1063}] run give @s ominous_bottle 1 4
execute at @s[scores={random=1064}] run give @s firework_rocket 1 2
execute at @s[scores={random=1065}] run give @s firework_rocket 1 3
execute at @s[scores={random=1066}] run give @s banner 1 1
execute at @s[scores={random=1067}] run give @s banner 1 2
execute at @s[scores={random=1068}] run give @s banner 1 3
execute at @s[scores={random=1069}] run give @s banner 1 4
execute at @s[scores={random=1070}] run give @s banner 1 5
execute at @s[scores={random=1071}] run give @s banner 1 6
execute at @s[scores={random=1072}] run give @s banner 1 7
execute at @s[scores={random=1073}] run give @s banner 1 8
execute at @s[scores={random=1074}] run give @s banner 1 9
execute at @s[scores={random=1075}] run give @s banner 1 10
execute at @s[scores={random=1076}] run give @s banner 1 11
execute at @s[scores={random=1077}] run give @s banner 1 12
execute at @s[scores={random=1078}] run give @s banner 1 13
execute at @s[scores={random=1079}] run give @s banner 1 14
execute at @s[scores={random=1080}] run give @s banner 1 15
execute at @s[scores={random=1081}] run give @s skull 1 1
execute at @s[scores={random=1082}] run give @s skull 1 2
execute at @s[scores={random=1083}] run give @s skull 1 3
execute at @s[scores={random=1084}] run give @s skull 1 4
execute at @s[scores={random=1085}] run give @s skull 1 5
execute as @s[scores={random=1086}] run function variants/runbooks
execute as @s[scores={random=1087}] run function variants/runbooks
execute as @s[scores={random=1088}] run function variants/runeggs
execute as @s[scores={random=1089}] run function variants/runeggs
execute as @s[scores={random=1090}] run function variants/runpotions
execute as @s[scores={random=1091}] run function variants/runpotions
execute as @s[scores={random=1092}] run function variants/runpotions
execute as @s[scores={random=1093}] run function variants/runpotions
execute as @s[scores={random=1094}] run function variants/runpotions
execute as @s[scores={random=1095}] run function variants/runpotions
execute as @s[scores={random=1096}] run function variants/runcopper
execute as @s[scores={random=1097}] run function variants/runcopper
execute as @s[scores={random=1098}] run function variants/runcopper
execute as @s[scores={random=1099}] run function variants/runcopper
execute as @s[scores={random=1100}] run function variants/runcopper
execute as @s[scores={random=1101}] run function variants/runcopper
execute as @s[scores={random=1102}] run function variants/runcopper
execute as @s[scores={random=1103}] run function variants/runcopper
execute as @s[scores={random=1104}] run function variants/runcopper
execute as @s[scores={random=1105}] run function variants/runcopper
execute as @s[scores={random=1106}] run function variants/runcopper
execute as @s[scores={random=1107}] run function variants/runcopper
execute as @s[scores={random=1108}] run function variants/runcopper
execute as @s[scores={random=1109}] run function variants/runcopper
execute as @s[scores={random=1110}] run function variants/runcopper
execute as @s[scores={random=1111}] run function variants/runcopper