execute at @a[scores={random=1}] run give @p acacia_boat
execute at @a[scores={random=2}] run give @p acacia_button
execute at @a[scores={random=3}] run give @p acacia_chest_boat
execute at @a[scores={random=4}] run give @p acacia_door
execute at @a[scores={random=6}] run give @p acacia_fence
execute at @a[scores={random=7}] run give @p acacia_fence_gate
execute at @a[scores={random=8}] run give @p acacia_hanging_sign
execute at @a[scores={random=9}] run give @p acacia_leaves
execute at @a[scores={random=10}] run give @p acacia_log
execute at @a[scores={random=11}] run give @p acacia_planks
execute at @a[scores={random=12}] run give @p acacia_pressure_plate
execute at @a[scores={random=13}] run give @p acacia_sapling
execute at @a[scores={random=14}] run give @p acacia_sign
execute at @a[scores={random=15}] run give @p acacia_slab
execute at @a[scores={random=16}] run give @p acacia_stairs
execute at @a[scores={random=18}] run give @p acacia_trapdoor
execute at @a[scores={random=20}] run give @p acacia_wood
execute at @a[scores={random=21}] run give @p activator_rail
execute at @a[scores={random=23}] run give @p air
execute at @a[scores={random=24}] run give @p allay_spawn_egg
execute at @a[scores={random=25}] run give @p allium
execute at @a[scores={random=27}] run give @p amethyst_block
execute at @a[scores={random=28}] run give @p amethyst_cluster
execute at @a[scores={random=29}] run give @p amethyst_shard
execute at @a[scores={random=30}] run give @p ancient_debris
execute at @a[scores={random=31}] run give @p andesite
execute at @a[scores={random=34}] run give @p andesite_stairs
execute at @a[scores={random=35}] run give @p angler_pottery_sherd
execute at @a[scores={random=36}] run give @p anvil
execute at @a[scores={random=37}] run give @p apple
execute at @a[scores={random=38}] run give @p archer_pottery_sherd
execute at @a[scores={random=39}] run give @p armadillo_scute
execute at @a[scores={random=40}] run give @p armadillo_spawn_egg
execute at @a[scores={random=41}] run give @p armor_stand
execute at @a[scores={random=42}] run give @p arms_up_pottery_sherd
execute at @a[scores={random=43}] run give @p arrow
execute at @a[scores={random=44}] run give @p axolotl_bucket
execute at @a[scores={random=45}] run give @p axolotl_spawn_egg
execute at @a[scores={random=46}] run give @p azalea
execute at @a[scores={random=47}] run give @p azalea_leaves
execute at @a[scores={random=48}] run give @p azalea_leaves_flowered
execute at @a[scores={random=49}] run give @p azure_bluet