execute at @a[scores={random=50}] run give @p baked_potato
execute at @a[scores={random=52}] run give @p bamboo
execute at @a[scores={random=53}] run give @p bamboo_block
execute at @a[scores={random=54}] run give @p bamboo_button
execute at @a[scores={random=55}] run give @p bamboo_chest_raft
execute at @a[scores={random=56}] run give @p bamboo_door
execute at @a[scores={random=58}] run give @p bamboo_fence
execute at @a[scores={random=59}] run give @p bamboo_fence_gate
execute at @a[scores={random=60}] run give @p bamboo_hanging_sign
execute at @a[scores={random=61}] run give @p bamboo_mosaic
execute at @a[scores={random=63}] run give @p bamboo_mosaic_slab
execute at @a[scores={random=64}] run give @p bamboo_mosaic_stairs
execute at @a[scores={random=65}] run give @p bamboo_planks
execute at @a[scores={random=66}] run give @p bamboo_pressure_plate
execute at @a[scores={random=67}] run give @p bamboo_raft
execute at @a[scores={random=69}] run give @p bamboo_sign
execute at @a[scores={random=70}] run give @p bamboo_slab
execute at @a[scores={random=71}] run give @p bamboo_stairs
execute at @a[scores={random=73}] run give @p bamboo_trapdoor
execute at @a[scores={random=75}] run give @p banner
execute at @a[scores={random=77}] run give @p barrel
execute at @a[scores={random=79}] run give @p basalt
execute at @a[scores={random=80}] run give @p bat_spawn_egg
execute at @a[scores={random=81}] run give @p beacon
execute at @a[scores={random=82}] run give @p bed
execute at @a[scores={random=84}] run give @p bee_nest
execute at @a[scores={random=85}] run give @p bee_spawn_egg
execute at @a[scores={random=86}] run give @p beef
execute at @a[scores={random=88}] run give @p beehive
execute at @a[scores={random=89}] run give @p beetroot
execute at @a[scores={random=90}] run give @p beetroot_seeds
execute at @a[scores={random=91}] run give @p beetroot_soup
execute at @a[scores={random=92}] run give @p bell
execute at @a[scores={random=93}] run give @p big_dripleaf
execute at @a[scores={random=94}] run give @p birch_boat
execute at @a[scores={random=95}] run give @p birch_button
execute at @a[scores={random=96}] run give @p birch_chest_boat
execute at @a[scores={random=97}] run give @p birch_door
execute at @a[scores={random=99}] run give @p birch_fence
execute at @a[scores={random=100}] run give @p birch_fence_gate
execute at @a[scores={random=101}] run give @p birch_hanging_sign
execute at @a[scores={random=102}] run give @p birch_leaves
execute at @a[scores={random=103}] run give @p birch_log
execute at @a[scores={random=104}] run give @p birch_planks
execute at @a[scores={random=105}] run give @p birch_pressure_plate
execute at @a[scores={random=106}] run give @p birch_sapling
execute at @a[scores={random=107}] run give @p birch_sign
execute at @a[scores={random=108}] run give @p birch_slab
execute at @a[scores={random=109}] run give @p birch_stairs
execute at @a[scores={random=111}] run give @p birch_trapdoor
execute at @a[scores={random=113}] run give @p birch_wood
execute at @a[scores={random=114}] run give @p black_candle
execute at @a[scores={random=116}] run give @p black_carpet
execute at @a[scores={random=117}] run give @p black_concrete
execute at @a[scores={random=118}] run give @p black_concrete_powder
execute at @a[scores={random=119}] run give @p black_dye
execute at @a[scores={random=120}] run give @p black_glazed_terracotta
execute at @a[scores={random=121}] run give @p black_shulker_box
execute at @a[scores={random=122}] run give @p black_stained_glass
execute at @a[scores={random=123}] run give @p black_stained_glass_pane
execute at @a[scores={random=124}] run give @p black_terracotta
execute at @a[scores={random=125}] run give @p black_wool
execute at @a[scores={random=126}] run give @p blackstone
execute at @a[scores={random=128}] run give @p blackstone_slab
execute at @a[scores={random=129}] run give @p blackstone_stairs
execute at @a[scores={random=130}] run give @p blackstone_wall
execute at @a[scores={random=131}] run give @p blade_pottery_sherd
execute at @a[scores={random=132}] run give @p blast_furnace
execute at @a[scores={random=133}] run give @p blaze_powder
execute at @a[scores={random=134}] run give @p blaze_rod
execute at @a[scores={random=135}] run give @p blaze_spawn_egg
execute at @a[scores={random=137}] run give @p blue_candle
execute at @a[scores={random=139}] run give @p blue_carpet
execute at @a[scores={random=140}] run give @p blue_concrete
execute at @a[scores={random=141}] run give @p blue_concrete_powder
execute at @a[scores={random=142}] run give @p blue_dye
execute at @a[scores={random=143}] run give @p blue_glazed_terracotta
execute at @a[scores={random=144}] run give @p blue_ice
execute at @a[scores={random=145}] run give @p blue_orchid
execute at @a[scores={random=146}] run give @p blue_shulker_box
execute at @a[scores={random=147}] run give @p blue_stained_glass
execute at @a[scores={random=148}] run give @p blue_stained_glass_pane
execute at @a[scores={random=149}] run give @p blue_terracotta
execute at @a[scores={random=150}] run give @p blue_wool
execute at @a[scores={random=152}] run give @p bogged_spawn_egg
execute at @a[scores={random=153}] run give @p bolt_armor_trim_smithing_template
execute at @a[scores={random=154}] run give @p bone
execute at @a[scores={random=155}] run give @p bone_block
execute at @a[scores={random=156}] run give @p bone_meal
execute at @a[scores={random=157}] run give @p book
execute at @a[scores={random=158}] run give @p bookshelf
execute at @a[scores={random=160}] run give @p bordure_indented_banner_pattern
execute at @a[scores={random=161}] run give @p bow
execute at @a[scores={random=162}] run give @p bowl
execute at @a[scores={random=163}] run give @p brain_coral
execute at @a[scores={random=164}] run give @p brain_coral_block
execute at @a[scores={random=165}] run give @p brain_coral_fan
execute at @a[scores={random=167}] run give @p bread
execute at @a[scores={random=168}] run give @p breeze_rod
execute at @a[scores={random=169}] run give @p breeze_spawn_egg
execute at @a[scores={random=170}] run give @p brewer_pottery_sherd
execute at @a[scores={random=171}] run give @p brewing_stand
execute at @a[scores={random=172}] run give @p brick
execute at @a[scores={random=173}] run give @p brick_block
execute at @a[scores={random=175}] run give @p brick_slab
execute at @a[scores={random=176}] run give @p brick_stairs
execute at @a[scores={random=177}] run give @p brown_candle
execute at @a[scores={random=179}] run give @p brown_carpet
execute at @a[scores={random=180}] run give @p brown_concrete
execute at @a[scores={random=181}] run give @p brown_concrete_powder
execute at @a[scores={random=182}] run give @p brown_dye
execute at @a[scores={random=183}] run give @p brown_glazed_terracotta
execute at @a[scores={random=184}] run give @p brown_mushroom
execute at @a[scores={random=185}] run give @p brown_mushroom_block
execute at @a[scores={random=186}] run give @p brown_shulker_box
execute at @a[scores={random=187}] run give @p brown_stained_glass
execute at @a[scores={random=188}] run give @p brown_stained_glass_pane
execute at @a[scores={random=189}] run give @p brown_terracotta
execute at @a[scores={random=190}] run give @p brown_wool
execute at @a[scores={random=191}] run give @p brush
execute at @a[scores={random=193}] run give @p bubble_coral
execute at @a[scores={random=194}] run give @p bubble_coral_block
execute at @a[scores={random=195}] run give @p bubble_coral_fan
execute at @a[scores={random=197}] run give @p bucket
execute at @a[scores={random=198}] run give @p budding_amethyst
execute at @a[scores={random=199}] run give @p burn_pottery_sherd