execute at @a[scores={random=200}] run give @p cactus
execute at @a[scores={random=201}] run give @p cake
execute at @a[scores={random=202}] run give @p calcite
execute at @a[scores={random=203}] run give @p calibrated_sculk_sensor
execute at @a[scores={random=204}] run give @p camel_spawn_egg
execute at @a[scores={random=206}] run give @p campfire
execute at @a[scores={random=207}] run give @p candle
execute at @a[scores={random=208}] run give @p carrot
execute at @a[scores={random=210}] run give @p carrot_on_a_stick
execute at @a[scores={random=212}] run give @p cartography_table
execute at @a[scores={random=213}] run give @p carved_pumpkin
execute at @a[scores={random=214}] run give @p cat_spawn_egg
execute at @a[scores={random=215}] run give @p cauldron
execute at @a[scores={random=216}] run give @p cave_spider_spawn_egg
execute at @a[scores={random=220}] run give @p chain
execute at @a[scores={random=222}] run give @p chainmail_boots
execute at @a[scores={random=223}] run give @p chainmail_chestplate
execute at @a[scores={random=224}] run give @p chainmail_helmet
execute at @a[scores={random=225}] run give @p chainmail_leggings
execute at @a[scores={random=226}] run give @p charcoal
execute at @a[scores={random=229}] run give @p cherry_boat
execute at @a[scores={random=230}] run give @p cherry_button
execute at @a[scores={random=231}] run give @p cherry_chest_boat
execute at @a[scores={random=232}] run give @p cherry_door
execute at @a[scores={random=234}] run give @p cherry_fence
execute at @a[scores={random=235}] run give @p cherry_fence_gate
execute at @a[scores={random=236}] run give @p cherry_hanging_sign
execute at @a[scores={random=237}] run give @p cherry_leaves
execute at @a[scores={random=238}] run give @p cherry_log
execute at @a[scores={random=239}] run give @p cherry_planks
execute at @a[scores={random=240}] run give @p cherry_pressure_plate
execute at @a[scores={random=241}] run give @p cherry_sapling
execute at @a[scores={random=242}] run give @p cherry_sign
execute at @a[scores={random=243}] run give @p cherry_slab
execute at @a[scores={random=244}] run give @p cherry_stairs
execute at @a[scores={random=246}] run give @p cherry_trapdoor
execute at @a[scores={random=248}] run give @p cherry_wood
execute at @a[scores={random=249}] run give @p chest
execute at @a[scores={random=251}] run give @p chest_minecart
execute at @a[scores={random=252}] run give @p chicken
execute at @a[scores={random=253}] run give @p chicken_spawn_egg
execute at @a[scores={random=255}] run give @p chiseled_bookshelf
execute at @a[scores={random=256}] run give @p chiseled_copper
execute at @a[scores={random=257}] run give @p chiseled_deepslate
execute at @a[scores={random=258}] run give @p chiseled_nether_bricks
execute at @a[scores={random=259}] run give @p chiseled_polished_blackstone
execute at @a[scores={random=264}] run give @p chiseled_tuff
execute at @a[scores={random=265}] run give @p chiseled_tuff_bricks
execute at @a[scores={random=266}] run give @p chorus_flower
execute at @a[scores={random=267}] run give @p chorus_fruit
execute at @a[scores={random=268}] run give @p chorus_plant
execute at @a[scores={random=269}] run give @p clay
execute at @a[scores={random=270}] run give @p clay_ball
execute at @a[scores={random=272}] run give @p clock
execute at @a[scores={random=273}] run give @p coal
execute at @a[scores={random=274}] run give @p coal_block
execute at @a[scores={random=275}] run give @p coal_ore
execute at @a[scores={random=277}] run give @p coast_armor_trim_smithing_template
execute at @a[scores={random=278}] run give @p cobbled_deepslate
execute at @a[scores={random=280}] run give @p cobbled_deepslate_slab
execute at @a[scores={random=281}] run give @p cobbled_deepslate_stairs
execute at @a[scores={random=282}] run give @p cobbled_deepslate_wall
execute at @a[scores={random=283}] run give @p cobblestone
execute at @a[scores={random=285}] run give @p cobblestone_slab
execute at @a[scores={random=286}] run give @p cobblestone_wall
execute at @a[scores={random=288}] run give @p cocoa_beans
execute at @a[scores={random=289}] run give @p cod
execute at @a[scores={random=290}] run give @p cod_bucket
execute at @a[scores={random=291}] run give @p cod_spawn_egg
execute at @a[scores={random=296}] run give @p comparator
execute at @a[scores={random=297}] run give @p compass
execute at @a[scores={random=298}] run give @p composter
execute at @a[scores={random=302}] run give @p conduit
execute at @a[scores={random=303}] run give @p cooked_beef
execute at @a[scores={random=304}] run give @p cooked_chicken
execute at @a[scores={random=305}] run give @p cooked_cod
execute at @a[scores={random=306}] run give @p cooked_mutton
execute at @a[scores={random=307}] run give @p cooked_porkchop
execute at @a[scores={random=308}] run give @p cooked_rabbit
execute at @a[scores={random=309}] run give @p cooked_salmon
execute at @a[scores={random=310}] run give @p cookie
execute at @a[scores={random=311}] run give @p copper_block
execute at @a[scores={random=312}] run give @p copper_bulb
execute at @a[scores={random=313}] run give @p copper_door
execute at @a[scores={random=314}] run give @p copper_grate
execute at @a[scores={random=315}] run give @p copper_ingot
execute at @a[scores={random=316}] run give @p copper_ore
execute at @a[scores={random=317}] run give @p copper_trapdoor
execute at @a[scores={random=320}] run give @p crafting_table
execute at @a[scores={random=322}] run give @p cornflower
execute at @a[scores={random=323}] run give @p cow_spawn_egg
execute at @a[scores={random=324}] run give @p cracked_deepslate_bricks
execute at @a[scores={random=325}] run give @p cracked_deepslate_tiles
execute at @a[scores={random=326}] run give @p cracked_nether_bricks
execute at @a[scores={random=327}] run give @p cracked_polished_blackstone_bricks
execute at @a[scores={random=329}] run give @p crafter