execute at @a[scores={random=348}] run give @p danger_pottery_sherd
execute at @a[scores={random=330}] run give @p dark_oak_boat
execute at @a[scores={random=331}] run give @p dark_oak_button
execute at @a[scores={random=332}] run give @p dark_oak_chest_boat
execute at @a[scores={random=333}] run give @p dark_oak_door
execute at @a[scores={random=335}] run give @p dark_oak_fence
execute at @a[scores={random=336}] run give @p dark_oak_fence_gate
execute at @a[scores={random=337}] run give @p dark_oak_hanging_sign
execute at @a[scores={random=338}] run give @p dark_oak_leaves
execute at @a[scores={random=339}] run give @p dark_oak_log
execute at @a[scores={random=340}] run give @p dark_oak_planks
execute at @a[scores={random=341}] run give @p dark_oak_pressure_plate
execute at @a[scores={random=342}] run give @p dark_oak_sapling
execute at @a[scores={random=343}] run give @p dark_oak_sign
execute at @a[scores={random=344}] run give @p dark_oak_slab
execute at @a[scores={random=345}] run give @p dark_oak_stairs
execute at @a[scores={random=346}] run give @p dark_oak_trapdoor
execute at @a[scores={random=347}] run give @p dark_oak_wood
execute at @a[scores={random=399}] run give @p dark_prismarine_stairs
execute at @a[scores={random=402}] run give @p daylight_detector
execute at @a[scores={random=404}] run give @p dead_brain_coral
execute at @a[scores={random=405}] run give @p dead_brain_coral_block
execute at @a[scores={random=406}] run give @p dead_brain_coral_fan
execute at @a[scores={random=408}] run give @p dead_bubble_coral
execute at @a[scores={random=409}] run give @p dead_bubble_coral_block
execute at @a[scores={random=410}] run give @p dead_bubble_coral_fan
execute at @a[scores={random=412}] run give @p dead_fire_coral
execute at @a[scores={random=413}] run give @p dead_fire_coral_block
execute at @a[scores={random=414}] run give @p dead_fire_coral_fan
execute at @a[scores={random=416}] run give @p dead_horn_coral
execute at @a[scores={random=417}] run give @p dead_horn_coral_block
execute at @a[scores={random=418}] run give @p dead_horn_coral_fan
execute at @a[scores={random=420}] run give @p dead_tube_coral
execute at @a[scores={random=421}] run give @p dead_tube_coral_block
execute at @a[scores={random=422}] run give @p dead_tube_coral_fan
execute at @a[scores={random=424}] run give @p deadbush
execute at @a[scores={random=426}] run give @p decorated_pot
execute at @a[scores={random=427}] run give @p deepslate
execute at @a[scores={random=429}] run give @p deepslate_brick_slab
execute at @a[scores={random=430}] run give @p deepslate_brick_stairs
execute at @a[scores={random=431}] run give @p deepslate_brick_wall
execute at @a[scores={random=432}] run give @p deepslate_bricks
execute at @a[scores={random=433}] run give @p deepslate_coal_ore
execute at @a[scores={random=434}] run give @p deepslate_copper_ore
execute at @a[scores={random=435}] run give @p deepslate_diamond_ore
execute at @a[scores={random=436}] run give @p deepslate_emerald_ore
execute at @a[scores={random=437}] run give @p deepslate_gold_ore
execute at @a[scores={random=438}] run give @p deepslate_iron_ore
execute at @a[scores={random=439}] run give @p deepslate_lapis_ore
execute at @a[scores={random=440}] run give @p deepslate_redstone_ore
execute at @a[scores={random=442}] run give @p deepslate_tile_slab
execute at @a[scores={random=443}] run give @p deepslate_tile_stairs
execute at @a[scores={random=444}] run give @p deepslate_tile_wall
execute at @a[scores={random=445}] run give @p deepslate_tiles
execute at @a[scores={random=448}] run give @p detector_rail
execute at @a[scores={random=449}] run give @p diamond
execute at @a[scores={random=450}] run give @p diamond_axe
execute at @a[scores={random=451}] run give @p diamond_block
execute at @a[scores={random=452}] run give @p diamond_boots
execute at @a[scores={random=453}] run give @p diamond_chestplate
execute at @a[scores={random=454}] run give @p diamond_helmet
execute at @a[scores={random=455}] run give @p diamond_hoe
execute at @a[scores={random=456}] run give @p diamond_horse_armor
execute at @a[scores={random=457}] run give @p diamond_leggings
execute at @a[scores={random=458}] run give @p diamond_ore
execute at @a[scores={random=459}] run give @p diamond_pickaxe
execute at @a[scores={random=460}] run give @p diamond_shovel
execute at @a[scores={random=461}] run give @p diamond_sword
execute at @a[scores={random=463}] run give @p diorite
execute at @a[scores={random=465}] run give @p diorite_stairs
execute at @a[scores={random=466}] run give @p dirt
execute at @a[scores={random=467}] run give @p dirt_with_roots
execute at @a[scores={random=468}] run give @p disc_fragment_5
execute at @a[scores={random=469}] run give @p dispenser
execute at @a[scores={random=470}] run give @p dolphin_spawn_egg
execute at @a[scores={random=471}] run give @p donkey_spawn_egg
execute at @a[scores={random=478}] run give @p dragon_breath
execute at @a[scores={random=479}] run give @p dragon_egg
execute at @a[scores={random=480}] run give @p dried_kelp
execute at @a[scores={random=481}] run give @p dried_kelp_block
execute at @a[scores={random=482}] run give @p dripstone_block
execute at @a[scores={random=483}] run give @p dropper
execute at @a[scores={random=484}] run give @p drowned_spawn_egg
execute at @a[scores={random=485}] run give @p dune_armor_trim_smithing_template