execute at @a[scores={random=487}] run give @p echo_shard
execute at @a[scores={random=488}] run give @p egg
execute at @a[scores={random=489}] run give @p elder_guardian_spawn_egg
execute at @a[scores={random=609}] run give @p elytra
execute at @a[scores={random=610}] run give @p emerald
execute at @a[scores={random=611}] run give @p emerald_block
execute at @a[scores={random=612}] run give @p emerald_ore
execute at @a[scores={random=613}] run give @p empty_map
execute at @a[scores={random=614}] run give @p enchanted_book
execute at @a[scores={random=615}] run give @p enchanted_golden_apple
execute at @a[scores={random=616}] run give @p enchanting_table
execute at @a[scores={random=617}] run give @p end_brick_stairs
execute at @a[scores={random=618}] run give @p end_bricks
execute at @a[scores={random=619}] run give @p end_crystal
execute at @a[scores={random=622}] run give @p end_portal_frame
execute at @a[scores={random=623}] run give @p end_rod
execute at @a[scores={random=624}] run give @p end_stone
execute at @a[scores={random=627}] run give @p ender_chest
execute at @a[scores={random=628}] run give @p ender_dragon_spawn_egg
execute at @a[scores={random=629}] run give @p ender_eye
execute at @a[scores={random=630}] run give @p ender_pearl
execute at @a[scores={random=631}] run give @p enderman_spawn_egg
execute at @a[scores={random=632}] run give @p endermite_spawn_egg
execute at @a[scores={random=633}] run give @p evoker_spawn_egg
execute at @a[scores={random=634}] run give @p experience_bottle
execute at @a[scores={random=635}] run give @p explorer_pottery_sherd
execute at @a[scores={random=636}] run give @p exposed_chiseled_copper
execute at @a[scores={random=637}] run give @p exposed_copper
execute at @a[scores={random=638}] run give @p exposed_copper_bulb
execute at @a[scores={random=639}] run give @p exposed_copper_door
execute at @a[scores={random=640}] run give @p exposed_copper_grate
execute at @a[scores={random=641}] run give @p exposed_copper_trapdoor
execute at @a[scores={random=642}] run give @p exposed_cut_copper
execute at @a[scores={random=643}] run give @p exposed_cut_copper_slab
execute at @a[scores={random=644}] run give @p exposed_cut_copper_stairs
execute at @a[scores={random=646}] run give @p eye_armor_trim_smithing_template