execute at @a[scores={random=647}] run give @p farmland
execute at @a[scores={random=648}] run give @p feather
execute at @a[scores={random=649}] run give @p fence
execute at @a[scores={random=650}] run give @p fence_gate
execute at @a[scores={random=651}] run give @p fermented_spider_eye
execute at @a[scores={random=652}] run give @p fern
execute at @a[scores={random=653}] run give @p field_masoned_banner_pattern
execute at @a[scores={random=654}] run give @p filled_map
execute at @a[scores={random=656}] run give @p fire_charge
execute at @a[scores={random=657}] run give @p fire_coral
execute at @a[scores={random=658}] run give @p fire_coral_block
execute at @a[scores={random=659}] run give @p fire_coral_fan
execute at @a[scores={random=661}] run give @p firework_rocket
execute at @a[scores={random=662}] run give @p firework_star
execute at @a[scores={random=663}] run give @p fishing_rod
execute at @a[scores={random=664}] run give @p fletching_table
execute at @a[scores={random=665}] run give @p flint
execute at @a[scores={random=666}] run give @p flint_and_steel
execute at @a[scores={random=667}] run give @p flow_armor_trim_smithing_template
execute at @a[scores={random=668}] run give @p flow_banner_pattern
execute at @a[scores={random=669}] run give @p flow_pottery_sherd
execute at @a[scores={random=670}] run give @p flower_banner_pattern
execute at @a[scores={random=671}] run give @p flower_pot
execute at @a[scores={random=672}] run give @p flowering_azalea
execute at @a[scores={random=675}] run give @p fox_spawn_egg
execute at @a[scores={random=676}] run give @p frame
execute at @a[scores={random=677}] run give @p friend_pottery_sherd
execute at @a[scores={random=678}] run give @p frog_spawn
execute at @a[scores={random=679}] run give @p frog_spawn_egg
execute at @a[scores={random=680}] run give @p frosted_ice
execute at @a[scores={random=681}] run give @p furnace