execute at @a[scores={random=682}] run give @p ghast_spawn_egg
execute at @a[scores={random=683}] run give @p ghast_tear
execute at @a[scores={random=684}] run give @p gilded_blackstone
execute at @a[scores={random=685}] run give @p glass
execute at @a[scores={random=686}] run give @p glass_bottle
execute at @a[scores={random=687}] run give @p glass_pane
execute at @a[scores={random=688}] run give @p glistering_melon_slice
execute at @a[scores={random=689}] run give @p globe_banner_pattern
execute at @a[scores={random=690}] run give @p glow_frame
execute at @a[scores={random=691}] run give @p glow_ink_sac
execute at @a[scores={random=692}] run give @p glow_lichen
execute at @a[scores={random=693}] run give @p glow_squid_spawn_egg
execute at @a[scores={random=696}] run give @p glowstone
execute at @a[scores={random=697}] run give @p glowstone_dust
execute at @a[scores={random=698}] run give @p goat_horn
execute at @a[scores={random=699}] run give @p goat_spawn_egg
execute at @a[scores={random=700}] run give @p gold_block
execute at @a[scores={random=701}] run give @p gold_ingot
execute at @a[scores={random=702}] run give @p gold_nugget
execute at @a[scores={random=703}] run give @p gold_ore
execute at @a[scores={random=704}] run give @p golden_apple
execute at @a[scores={random=705}] run give @p golden_axe
execute at @a[scores={random=706}] run give @p golden_boots
execute at @a[scores={random=707}] run give @p golden_carrot
execute at @a[scores={random=708}] run give @p golden_chestplate
execute at @a[scores={random=709}] run give @p golden_helmet
execute at @a[scores={random=710}] run give @p golden_hoe
execute at @a[scores={random=711}] run give @p golden_horse_armor
execute at @a[scores={random=712}] run give @p golden_leggings
execute at @a[scores={random=713}] run give @p golden_pickaxe
execute at @a[scores={random=714}] run give @p golden_rail
execute at @a[scores={random=715}] run give @p golden_shovel
execute at @a[scores={random=716}] run give @p golden_sword
execute at @a[scores={random=717}] run give @p granite
execute at @a[scores={random=720}] run give @p granite_stairs
execute at @a[scores={random=721}] run give @p grass_block
execute at @a[scores={random=722}] run give @p grass_path
execute at @a[scores={random=723}] run give @p gravel
execute at @a[scores={random=724}] run give @p gray_candle
execute at @a[scores={random=725}] run give @p glow_berries
execute at @a[scores={random=726}] run give @p gray_carpet
execute at @a[scores={random=727}] run give @p gray_concrete
execute at @a[scores={random=728}] run give @p gray_concrete_powder
execute at @a[scores={random=729}] run give @p gray_dye
execute at @a[scores={random=730}] run give @p gray_glazed_terracotta
execute at @a[scores={random=731}] run give @p gray_shulker_box
execute at @a[scores={random=732}] run give @p gray_stained_glass
execute at @a[scores={random=733}] run give @p gray_stained_glass_pane
execute at @a[scores={random=734}] run give @p gray_terracotta
execute at @a[scores={random=735}] run give @p gray_wool
execute at @a[scores={random=736}] run give @p green_candle
execute at @a[scores={random=738}] run give @p green_carpet
execute at @a[scores={random=739}] run give @p green_concrete
execute at @a[scores={random=740}] run give @p green_concrete_powder
execute at @a[scores={random=741}] run give @p green_dye
execute at @a[scores={random=742}] run give @p green_glazed_terracotta
execute at @a[scores={random=743}] run give @p green_shulker_box
execute at @a[scores={random=744}] run give @p green_stained_glass
execute at @a[scores={random=745}] run give @p green_stained_glass_pane
execute at @a[scores={random=746}] run give @p green_terracotta
execute at @a[scores={random=747}] run give @p green_wool
execute at @a[scores={random=748}] run give @p grindstone
execute at @a[scores={random=749}] run give @p guardian_spawn_egg
execute at @a[scores={random=750}] run give @p gunpowder
execute at @a[scores={random=751}] run give @p guster_banner_pattern
execute at @a[scores={random=752}] run give @p guster_pottery_sherd