execute at @a[scores={random=753}] run give @p hanging_roots
execute at @a[scores={random=790}] run give @p hardened_clay
execute at @a[scores={random=791}] run give @p hay_block
execute at @a[scores={random=792}] run give @p heart_of_the_sea
execute at @a[scores={random=793}] run give @p heart_pottery_sherd
execute at @a[scores={random=794}] run give @p heartbreak_pottery_sherd
execute at @a[scores={random=795}] run give @p heavy_core
execute at @a[scores={random=796}] run give @p heavy_weighted_pressure_plate
execute at @a[scores={random=797}] run give @p hoglin_spawn_egg
execute at @a[scores={random=798}] run give @p honey_block
execute at @a[scores={random=799}] run give @p honey_bottle
execute at @a[scores={random=800}] run give @p honeycomb
execute at @a[scores={random=801}] run give @p honeycomb_block
execute at @a[scores={random=802}] run give @p hopper
execute at @a[scores={random=803}] run give @p hopper_minecart
execute at @a[scores={random=804}] run give @p horn_coral
execute at @a[scores={random=805}] run give @p horn_coral_block
execute at @a[scores={random=806}] run give @p horn_coral_fan
execute at @a[scores={random=808}] run give @p horse_spawn_egg
execute at @a[scores={random=809}] run give @p host_armor_trim_smithing_template
execute at @a[scores={random=810}] run give @p howl_pottery_sherd
execute at @a[scores={random=811}] run give @p husk_spawn_egg