execute at @a[scores={random=812}] run give @p ice
execute at @a[scores={random=817}] run give @p infested_deepslate
execute at @a[scores={random=823}] run give @p ink_sac
execute at @a[scores={random=825}] run give @p iron_axe
execute at @a[scores={random=826}] run give @p iron_bars
execute at @a[scores={random=827}] run give @p iron_block
execute at @a[scores={random=828}] run give @p iron_boots
execute at @a[scores={random=829}] run give @p iron_chestplate
execute at @a[scores={random=830}] run give @p iron_door
execute at @a[scores={random=831}] run give @p iron_golem_spawn_egg
execute at @a[scores={random=832}] run give @p iron_helmet
execute at @a[scores={random=833}] run give @p iron_hoe
execute at @a[scores={random=834}] run give @p iron_horse_armor
execute at @a[scores={random=835}] run give @p iron_ingot
execute at @a[scores={random=836}] run give @p iron_leggings
execute at @a[scores={random=837}] run give @p iron_nugget
execute at @a[scores={random=838}] run give @p iron_ore
execute at @a[scores={random=839}] run give @p iron_pickaxe
execute at @a[scores={random=840}] run give @p iron_shovel
execute at @a[scores={random=841}] run give @p iron_sword
execute at @a[scores={random=842}] run give @p iron_trapdoor