execute at @a[scores={random=844}] run give @p jukebox
execute at @a[scores={random=845}] run give @p jungle_boat
execute at @a[scores={random=846}] run give @p jungle_button
execute at @a[scores={random=847}] run give @p jungle_chest_boat
execute at @a[scores={random=848}] run give @p jungle_door
execute at @a[scores={random=850}] run give @p jungle_fence
execute at @a[scores={random=851}] run give @p jungle_fence_gate
execute at @a[scores={random=852}] run give @p jungle_hanging_sign
execute at @a[scores={random=853}] run give @p jungle_leaves
execute at @a[scores={random=854}] run give @p jungle_log
execute at @a[scores={random=855}] run give @p jungle_planks
execute at @a[scores={random=856}] run give @p jungle_pressure_plate
execute at @a[scores={random=857}] run give @p jungle_sapling
execute at @a[scores={random=858}] run give @p jungle_sign
execute at @a[scores={random=859}] run give @p jungle_slab
execute at @a[scores={random=860}] run give @p jungle_stairs
execute at @a[scores={random=862}] run give @p jungle_trapdoor
execute at @a[scores={random=864}] run give @p jungle_wood