execute at @a[scores={random=866}] run give @p ladder
execute at @a[scores={random=867}] run give @p lantern
execute at @a[scores={random=868}] run give @p lapis_block
execute at @a[scores={random=869}] run give @p lapis_lazuli
execute at @a[scores={random=870}] run give @p lapis_ore
execute at @a[scores={random=871}] run give @p large_amethyst_bud
execute at @a[scores={random=872}] run give @p large_fern
execute at @a[scores={random=873}] run give @p lever
execute at @a[scores={random=874}] run give @p lava_bucket
execute at @a[scores={random=875}] run give @p lead
execute at @a[scores={random=876}] run give @p leather
execute at @a[scores={random=877}] run give @p leather_boots
execute at @a[scores={random=878}] run give @p leather_chestplate
execute at @a[scores={random=879}] run give @p leather_helmet
execute at @a[scores={random=880}] run give @p leather_horse_armor
execute at @a[scores={random=881}] run give @p leather_leggings
execute at @a[scores={random=882}] run give @p light_blue_candle
execute at @a[scores={random=883}] run give @p lectern
execute at @a[scores={random=884}] run give @p light_blue_carpet
execute at @a[scores={random=885}] run give @p light_blue_concrete
execute at @a[scores={random=886}] run give @p light_blue_concrete_powder
execute at @a[scores={random=887}] run give @p light_blue_dye
execute at @a[scores={random=888}] run give @p light_blue_glazed_terracotta
execute at @a[scores={random=889}] run give @p light_blue_shulker_box
execute at @a[scores={random=890}] run give @p light_blue_stained_glass
execute at @a[scores={random=891}] run give @p light_blue_stained_glass_pane
execute at @a[scores={random=892}] run give @p light_blue_terracotta
execute at @a[scores={random=893}] run give @p light_blue_wool
execute at @a[scores={random=894}] run give @p light_gray_candle
execute at @a[scores={random=896}] run give @p light_gray_carpet
execute at @a[scores={random=897}] run give @p light_gray_concrete
execute at @a[scores={random=898}] run give @p light_gray_concrete_powder
execute at @a[scores={random=899}] run give @p light_gray_dye
execute at @a[scores={random=900}] run give @p light_gray_shulker_box
execute at @a[scores={random=901}] run give @p light_gray_stained_glass
execute at @a[scores={random=902}] run give @p light_gray_stained_glass_pane
execute at @a[scores={random=903}] run give @p light_gray_terracotta
execute at @a[scores={random=904}] run give @p light_gray_wool
execute at @a[scores={random=905}] run give @p light_weighted_pressure_plate
execute at @a[scores={random=906}] run give @p lightning_rod
execute at @a[scores={random=907}] run give @p lilac
execute at @a[scores={random=908}] run give @p lily_of_the_valley
execute at @a[scores={random=909}] run give @p lime_candle
execute at @a[scores={random=911}] run give @p lime_carpet
execute at @a[scores={random=912}] run give @p lime_concrete
execute at @a[scores={random=913}] run give @p lime_concrete_powder
execute at @a[scores={random=914}] run give @p lime_dye
execute at @a[scores={random=915}] run give @p lime_glazed_terracotta
execute at @a[scores={random=916}] run give @p lime_shulker_box
execute at @a[scores={random=917}] run give @p lime_stained_glass
execute at @a[scores={random=918}] run give @p lime_stained_glass_pane
execute at @a[scores={random=919}] run give @p lime_terracotta
execute at @a[scores={random=920}] run give @p lime_wool
execute at @a[scores={random=921}] run give @p lingering_potion
execute at @a[scores={random=925}] run give @p lit_pumpkin
execute at @a[scores={random=929}] run give @p llama_spawn_egg
execute at @a[scores={random=930}] run give @p lodestone
execute at @a[scores={random=931}] run give @p lodestone_compass
execute at @a[scores={random=932}] run give @p loom