execute at @a[scores={random=933}] run give @p mace
execute at @a[scores={random=934}] run give @p magenta_candle
execute at @a[scores={random=936}] run give @p magenta_carpet
execute at @a[scores={random=937}] run give @p magenta_concrete
execute at @a[scores={random=938}] run give @p magenta_concrete_powder
execute at @a[scores={random=939}] run give @p magenta_dye
execute at @a[scores={random=940}] run give @p magenta_glazed_terracotta
execute at @a[scores={random=941}] run give @p magenta_shulker_box
execute at @a[scores={random=942}] run give @p magenta_stained_glass
execute at @a[scores={random=943}] run give @p magenta_stained_glass_pane
execute at @a[scores={random=944}] run give @p magenta_terracotta
execute at @a[scores={random=945}] run give @p magenta_wool
execute at @a[scores={random=946}] run give @p magma
execute at @a[scores={random=947}] run give @p magma_cream
execute at @a[scores={random=948}] run give @p magma_cube_spawn_egg
execute at @a[scores={random=949}] run give @p mangrove_boat
execute at @a[scores={random=950}] run give @p mangrove_button
execute at @a[scores={random=951}] run give @p mangrove_chest_boat
execute at @a[scores={random=952}] run give @p mangrove_door
execute at @a[scores={random=954}] run give @p mangrove_fence
execute at @a[scores={random=955}] run give @p mangrove_fence_gate
execute at @a[scores={random=956}] run give @p mangrove_hanging_sign
execute at @a[scores={random=957}] run give @p mangrove_leaves
execute at @a[scores={random=958}] run give @p mangrove_log
execute at @a[scores={random=959}] run give @p mangrove_planks
execute at @a[scores={random=960}] run give @p mangrove_pressure_plate
execute at @a[scores={random=961}] run give @p mangrove_propagule
execute at @a[scores={random=962}] run give @p mangrove_roots
execute at @a[scores={random=963}] run give @p mangrove_sign
execute at @a[scores={random=964}] run give @p mangrove_slab
execute at @a[scores={random=965}] run give @p mangrove_stairs
execute at @a[scores={random=967}] run give @p mangrove_trapdoor
execute at @a[scores={random=969}] run give @p mangrove_wood
execute at @a[scores={random=1578}] run give @p mycelium
execute at @a[scores={random=970}] run give @p medium_amethyst_bud
execute at @a[scores={random=971}] run give @p melon_block
execute at @a[scores={random=972}] run give @p melon_seeds
execute at @a[scores={random=973}] run give @p melon_slice
execute at @a[scores={random=975}] run give @p milk_bucket
execute at @a[scores={random=976}] run give @p minecart
execute at @a[scores={random=1579}] run give @p mutton
execute at @a[scores={random=1580}] run give @p music_disc_ward
execute at @a[scores={random=1581}] run give @p music_disc_wait
execute at @a[scores={random=1582}] run give @p music_disc_strad
execute at @a[scores={random=1583}] run give @p music_disc_stal
execute at @a[scores={random=1584}] run give @p music_disc_relic
execute at @a[scores={random=1585}] run give @p music_disc_precipice
execute at @a[scores={random=1586}] run give @p music_disc_pigstep
execute at @a[scores={random=1587}] run give @p music_disc_otherside
execute at @a[scores={random=1588}] run give @p music_disc_mellohi
execute at @a[scores={random=1589}] run give @p music_disc_mall
execute at @a[scores={random=1590}] run give @p music_disc_far
execute at @a[scores={random=1591}] run give @p music_disc_creator_music_box
execute at @a[scores={random=1592}] run give @p music_disc_creator
execute at @a[scores={random=1593}] run give @p music_disc_chirp
execute at @a[scores={random=1594}] run give @p music_disc_cat
execute at @a[scores={random=1595}] run give @p music_disc_blocks
execute at @a[scores={random=1596}] run give @p music_disc_5
execute at @a[scores={random=1597}] run give @p music_disc_13
execute at @a[scores={random=1598}] run give @p music_disc_11
execute at @a[scores={random=1599}] run give @p mushroom_stew
execute at @a[scores={random=1600}] run give @p mule_spawn_egg
execute at @a[scores={random=1601}] run give @p muddy_mangrove_roots
execute at @a[scores={random=1602}] run give @p mud_bricks
execute at @a[scores={random=1603}] run give @p mud_brick_wall
execute at @a[scores={random=1604}] run give @p mud_brick_stairs
execute at @a[scores={random=1605}] run give @p mud_brick_slab
execute at @a[scores={random=1607}] run give @p mud
execute at @a[scores={random=1608}] run give @p mourner_pottery_sherd
execute at @a[scores={random=1610}] run give @p mossy_stone_brick_stairs
execute at @a[scores={random=1612}] run give @p mossy_cobblestone_stairs
execute at @a[scores={random=1614}] run give @p mossy_cobblestone
execute at @a[scores={random=1615}] run give @p moss_carpet
execute at @a[scores={random=1616}] run give @p moss_block
execute at @a[scores={random=1617}] run give @p mooshroom_spawn_egg
execute at @a[scores={random=1618}] run give @p monster_egg
execute at @a[scores={random=1619}] run give @p mojang_banner_pattern
execute at @a[scores={random=1620}] run give @p mob_spawner
execute at @a[scores={random=1621}] run give @p miner_pottery_sherd