execute at @a[scores={random=1550}] run give @p noteblock
execute at @a[scores={random=1551}] run give @p normal_stone_stairs
execute at @a[scores={random=1552}] run give @p netherrack
execute at @a[scores={random=1553}] run give @p netherite_upgrade_smithing_template
execute at @a[scores={random=1554}] run give @p netherite_shovel
execute at @a[scores={random=1555}] run give @p netherite_scrap
execute at @a[scores={random=1556}] run give @p netherite_pickaxe
execute at @a[scores={random=1557}] run give @p netherite_leggings
execute at @a[scores={random=1558}] run give @p netherite_ingot
execute at @a[scores={random=1559}] run give @p netherite_hoe
execute at @a[scores={random=1560}] run give @p netherite_helmet
execute at @a[scores={random=1561}] run give @p netherite_chestplate
execute at @a[scores={random=1562}] run give @p netherite_boots
execute at @a[scores={random=1563}] run give @p netherite_block
execute at @a[scores={random=1564}] run give @p netherite_axe
execute at @a[scores={random=1565}] run give @p netherbrick
execute at @a[scores={random=1566}] run give @p nether_wart_block
execute at @a[scores={random=1567}] run give @p nether_wart
execute at @a[scores={random=1568}] run give @p nether_star
execute at @a[scores={random=1569}] run give @p nether_sprouts
execute at @a[scores={random=1570}] run give @p nether_gold_ore
execute at @a[scores={random=1571}] run give @p nether_brick_stairs
execute at @a[scores={random=1572}] run give @p nether_brick_slab
execute at @a[scores={random=1573}] run give @p nether_brick_fence
execute at @a[scores={random=1575}] run give @p nether_brick
execute at @a[scores={random=1576}] run give @p nautilus_shell
execute at @a[scores={random=1577}] run give @p name_tag