execute at @a[scores={random=1508}] run give @p oxidized_cut_copper_stairs
execute at @a[scores={random=1509}] run give @p oxidized_cut_copper_slab
execute at @a[scores={random=1510}] run give @p oxidized_cut_copper
execute at @a[scores={random=1511}] run give @p oxidized_copper_trapdoor
execute at @a[scores={random=1512}] run give @p oxidized_copper_grate
execute at @a[scores={random=1513}] run give @p oxidized_copper_door
execute at @a[scores={random=1514}] run give @p oxidized_copper_bulb
execute at @a[scores={random=1515}] run give @p oxidized_copper
execute at @a[scores={random=1516}] run give @p oxidized_chiseled_copper
execute at @a[scores={random=1517}] run give @p oxeye_daisy
execute at @a[scores={random=1518}] run give @p orange_wool
execute at @a[scores={random=1519}] run give @p orange_tulip
execute at @a[scores={random=1520}] run give @p orange_terracotta
execute at @a[scores={random=1521}] run give @p orange_stained_glass_pane
execute at @a[scores={random=1522}] run give @p orange_stained_glass
execute at @a[scores={random=1523}] run give @p orange_shulker_box
execute at @a[scores={random=1524}] run give @p orange_glazed_terracotta
execute at @a[scores={random=1525}] run give @p orange_dye
execute at @a[scores={random=1526}] run give @p orange_concrete_powder
execute at @a[scores={random=1527}] run give @p orange_concrete
execute at @a[scores={random=1528}] run give @p orange_carpet
execute at @a[scores={random=1529}] run give @p orange_candle
execute at @a[scores={random=1530}] run give @p ominous_trial_key
execute at @a[scores={random=1531}] run give @p ominous_bottle
execute at @a[scores={random=1532}] run give @p ochre_froglight
execute at @a[scores={random=1533}] run give @p ocelot_spawn_egg
execute at @a[scores={random=1534}] run give @p obsidian
execute at @a[scores={random=1535}] run give @p observer
execute at @a[scores={random=1536}] run give @p oak_wood
execute at @a[scores={random=1537}] run give @p oak_stairs
execute at @a[scores={random=1538}] run give @p oak_slab
execute at @a[scores={random=1539}] run give @p oak_sign
execute at @a[scores={random=1540}] run give @p oak_sapling
execute at @a[scores={random=1541}] run give @p oak_planks
execute at @a[scores={random=1542}] run give @p oak_log
execute at @a[scores={random=1543}] run give @p oak_leaves
execute at @a[scores={random=1544}] run give @p oak_hanging_sign
execute at @a[scores={random=1545}] run give @p oak_fence
execute at @a[scores={random=1547}] run give @p oak_chest_boat
execute at @a[scores={random=1548}] run give @p oak_boat