execute at @a[scores={random=1395}] run give @p purpur_stairs
execute at @a[scores={random=1398}] run give @p purpur_block
execute at @a[scores={random=1399}] run give @p purple_wool
execute at @a[scores={random=1400}] run give @p purple_terracotta
execute at @a[scores={random=1401}] run give @p purple_stained_glass_pane
execute at @a[scores={random=1402}] run give @p purple_stained_glass
execute at @a[scores={random=1403}] run give @p purple_shulker_box
execute at @a[scores={random=1404}] run give @p purple_glazed_terracotta
execute at @a[scores={random=1405}] run give @p purple_dye
execute at @a[scores={random=1406}] run give @p purple_concrete_powder
execute at @a[scores={random=1407}] run give @p purple_concrete
execute at @a[scores={random=1408}] run give @p purple_carpet
execute at @a[scores={random=1410}] run give @p purple_candle
execute at @a[scores={random=1411}] run give @p pumpkin_seeds
execute at @a[scores={random=1412}] run give @p pumpkin_pie
execute at @a[scores={random=1413}] run give @p pumpkin
execute at @a[scores={random=1414}] run give @p pufferfish_spawn_egg
execute at @a[scores={random=1415}] run give @p pufferfish_bucket
execute at @a[scores={random=1416}] run give @p pufferfish
execute at @a[scores={random=1417}] run give @p prize_pottery_sherd
execute at @a[scores={random=1418}] run give @p prismarine_stairs
execute at @a[scores={random=1420}] run give @p prismarine_shard
execute at @a[scores={random=1422}] run give @p prismarine_crystals
execute at @a[scores={random=1423}] run give @p prismarine_bricks_stairs
execute at @a[scores={random=1427}] run give @p prismarine
execute at @a[scores={random=1428}] run give @p powder_snow_bucket
execute at @a[scores={random=1429}] run give @p potion
execute at @a[scores={random=1430}] run give @p potato
execute at @a[scores={random=1431}] run give @p porkchop
execute at @a[scores={random=1432}] run give @p poppy
execute at @a[scores={random=1433}] run give @p popped_chorus_fruit
execute at @a[scores={random=1434}] run give @p polished_tuff_wall
execute at @a[scores={random=1435}] run give @p polished_tuff_stairs
execute at @a[scores={random=1436}] run give @p polished_tuff_slab
execute at @a[scores={random=1438}] run give @p polished_tuff
execute at @a[scores={random=1439}] run give @p polished_granite_stairs
execute at @a[scores={random=1442}] run give @p polished_granite
execute at @a[scores={random=1443}] run give @p polished_diorite_stairs
execute at @a[scores={random=1446}] run give @p polished_diorite
execute at @a[scores={random=1447}] run give @p polished_deepslate_wall
execute at @a[scores={random=1448}] run give @p polished_deepslate_stairs
execute at @a[scores={random=1449}] run give @p polished_deepslate_slab
execute at @a[scores={random=1451}] run give @p polished_deepslate
execute at @a[scores={random=1452}] run give @p polished_blackstone_wall
execute at @a[scores={random=1453}] run give @p polished_blackstone_stairs
execute at @a[scores={random=1454}] run give @p polished_blackstone_slab
execute at @a[scores={random=1455}] run give @p polished_blackstone_pressure_plate
execute at @a[scores={random=1457}] run give @p polished_blackstone_button
execute at @a[scores={random=1458}] run give @p polished_blackstone_bricks
execute at @a[scores={random=1459}] run give @p polished_blackstone_brick_wall
execute at @a[scores={random=1460}] run give @p polished_blackstone_brick_stairs
execute at @a[scores={random=1461}] run give @p polished_blackstone_brick_slab
execute at @a[scores={random=1463}] run give @p polished_blackstone
execute at @a[scores={random=1464}] run give @p polished_basalt
execute at @a[scores={random=1465}] run give @p polished_andesite_stairs
execute at @a[scores={random=1468}] run give @p polished_andesite
execute at @a[scores={random=1469}] run give @p polar_bear_spawn_egg
execute at @a[scores={random=1470}] run give @p poisonous_potato
execute at @a[scores={random=1471}] run give @p pointed_dripstone
execute at @a[scores={random=1472}] run give @p podzol
execute at @a[scores={random=1473}] run give @p plenty_pottery_sherd
execute at @a[scores={random=1474}] run give @p pitcher_pod
execute at @a[scores={random=1475}] run give @p pitcher_plant
execute at @a[scores={random=1476}] run give @p piston
execute at @a[scores={random=1477}] run give @p pink_wool
execute at @a[scores={random=1478}] run give @p pink_tulip
execute at @a[scores={random=1479}] run give @p pink_terracotta
execute at @a[scores={random=1480}] run give @p pink_stained_glass_pane
execute at @a[scores={random=1481}] run give @p pink_stained_glass
execute at @a[scores={random=1482}] run give @p pink_shulker_box
execute at @a[scores={random=1483}] run give @p pink_petals
execute at @a[scores={random=1484}] run give @p pink_glazed_terracotta
execute at @a[scores={random=1485}] run give @p pink_dye
execute at @a[scores={random=1486}] run give @p pink_concrete_powder
execute at @a[scores={random=1487}] run give @p pink_concrete
execute at @a[scores={random=1488}] run give @p pink_carpet
execute at @a[scores={random=1490}] run give @p pink_candle
execute at @a[scores={random=1491}] run give @p pillager_spawn_egg
execute at @a[scores={random=1492}] run give @p piglin_spawn_egg
execute at @a[scores={random=1493}] run give @p piglin_brute_spawn_egg
execute at @a[scores={random=1494}] run give @p piglin_banner_pattern
execute at @a[scores={random=1495}] run give @p pig_spawn_egg
execute at @a[scores={random=1496}] run give @p phantom_spawn_egg
execute at @a[scores={random=1497}] run give @p phantom_membrane
execute at @a[scores={random=1498}] run give @p petrified_oak_slab
execute at @a[scores={random=1499}] run give @p peony
execute at @a[scores={random=1500}] run give @p pearlescent_froglight
execute at @a[scores={random=1501}] run give @p parrot_spawn_egg
execute at @a[scores={random=1502}] run give @p paper
execute at @a[scores={random=1503}] run give @p panda_spawn_egg
execute at @a[scores={random=1504}] run give @p painting
execute at @a[scores={random=1505}] run give @p packed_mud
execute at @a[scores={random=1506}] run give @p packed_ice