execute at @a[scores={random=1333}] run give @p rotten_flesh
execute at @a[scores={random=1334}] run give @p rose_bush
execute at @a[scores={random=1335}] run give @p rib_armor_trim_smithing_template
execute at @a[scores={random=1336}] run give @p respawn_anchor
execute at @a[scores={random=1338}] run give @p repeater
execute at @a[scores={random=1339}] run give @p reinforced_deepslate
execute at @a[scores={random=1341}] run give @p redstone_torch
execute at @a[scores={random=1342}] run give @p redstone_ore
execute at @a[scores={random=1343}] run give @p redstone_lamp
execute at @a[scores={random=1344}] run give @p redstone_block
execute at @a[scores={random=1345}] run give @p redstone
execute at @a[scores={random=1346}] run give @p red_wool
execute at @a[scores={random=1347}] run give @p red_tulip
execute at @a[scores={random=1348}] run give @p red_terracotta
execute at @a[scores={random=1349}] run give @p red_stained_glass_pane
execute at @a[scores={random=1350}] run give @p red_stained_glass
execute at @a[scores={random=1351}] run give @p red_shulker_box
execute at @a[scores={random=1352}] run give @p red_sandstone_stairs
execute at @a[scores={random=1355}] run give @p red_sandstone
execute at @a[scores={random=1357}] run give @p red_nether_brick_stairs
execute at @a[scores={random=1360}] run give @p red_nether_brick
execute at @a[scores={random=1361}] run give @p red_mushroom_block
execute at @a[scores={random=1362}] run give @p red_mushroom
execute at @a[scores={random=1363}] run give @p red_glazed_terracotta
execute at @a[scores={random=1365}] run give @p red_dye
execute at @a[scores={random=1366}] run give @p red_concrete_powder
execute at @a[scores={random=1367}] run give @p red_concrete
execute at @a[scores={random=1368}] run give @p red_carpet
execute at @a[scores={random=1370}] run give @p red_candle
execute at @a[scores={random=1371}] run give @p recovery_compass
execute at @a[scores={random=1372}] run give @p raw_iron_block
execute at @a[scores={random=1373}] run give @p raw_iron
execute at @a[scores={random=1374}] run give @p raw_gold_block
execute at @a[scores={random=1375}] run give @p raw_gold
execute at @a[scores={random=1376}] run give @p raw_copper_block
execute at @a[scores={random=1377}] run give @p raw_copper
execute at @a[scores={random=1378}] run give @p ravager_spawn_egg
execute at @a[scores={random=1380}] run give @p raiser_armor_trim_smithing_template
execute at @a[scores={random=1381}] run give @p rail
execute at @a[scores={random=1382}] run give @p rabbit_stew
execute at @a[scores={random=1383}] run give @p rabbit_spawn_egg
execute at @a[scores={random=1384}] run give @p rabbit_hide
execute at @a[scores={random=1385}] run give @p rabbit_foot
execute at @a[scores={random=1386}] run give @p rabbit