execute at @a[scores={random=1168}] run give @p sweet_berries
execute at @a[scores={random=1169}] run give @p suspicious_stew
execute at @a[scores={random=1170}] run give @p suspicious_sand
execute at @a[scores={random=1171}] run give @p suspicious_gravel
execute at @a[scores={random=1172}] run give @p sunflower
execute at @a[scores={random=1173}] run give @p sugar_cane
execute at @a[scores={random=1174}] run give @p sugar
execute at @a[scores={random=1177}] run give @p stripped_warped_stem
execute at @a[scores={random=1178}] run give @p stripped_warped_hyphae
execute at @a[scores={random=1179}] run give @p stripped_spruce_wood
execute at @a[scores={random=1180}] run give @p stripped_spruce_log
execute at @a[scores={random=1181}] run give @p stripped_oak_wood
execute at @a[scores={random=1182}] run give @p stripped_oak_log
execute at @a[scores={random=1183}] run give @p stripped_mangrove_wood
execute at @a[scores={random=1184}] run give @p stripped_mangrove_log
execute at @a[scores={random=1185}] run give @p stripped_jungle_wood
execute at @a[scores={random=1186}] run give @p stripped_jungle_log
execute at @a[scores={random=1187}] run give @p stripped_dark_oak_wood
execute at @a[scores={random=1188}] run give @p stripped_dark_oak_log
execute at @a[scores={random=1189}] run give @p stripped_crimson_stem
execute at @a[scores={random=1190}] run give @p stripped_crimson_hyphae
execute at @a[scores={random=1191}] run give @p stripped_cherry_wood
execute at @a[scores={random=1192}] run give @p stripped_cherry_log
execute at @a[scores={random=1193}] run give @p stripped_birch_wood
execute at @a[scores={random=1194}] run give @p stripped_birch_log
execute at @a[scores={random=1195}] run give @p stripped_bamboo_block
execute at @a[scores={random=1196}] run give @p stripped_acacia_wood
execute at @a[scores={random=1197}] run give @p stripped_acacia_log
execute at @a[scores={random=1198}] run give @p string
execute at @a[scores={random=1199}] run give @p strider_spawn_egg
execute at @a[scores={random=1200}] run give @p stray_spawn_egg
execute at @a[scores={random=1201}] run give @p stonecutter_block
execute at @a[scores={random=1202}] run give @p stonebrick
execute at @a[scores={random=1203}] run give @p stone_sword
execute at @a[scores={random=1204}] run give @p stone_stairs
execute at @a[scores={random=1205}] run give @p stone_shovel
execute at @a[scores={random=1206}] run give @p stone_pressure_plate
execute at @a[scores={random=1207}] run give @p stone_pickaxe
execute at @a[scores={random=1208}] run give @p stone_hoe
execute at @a[scores={random=1209}] run give @p stone_button
execute at @a[scores={random=1211}] run give @p stone_brick_stairs
execute at @a[scores={random=1212}] run give @p stone_brick_slab
execute at @a[scores={random=1214}] run give @p stone_block_slab4
execute at @a[scores={random=1215}] run give @p stone_block_slab3
execute at @a[scores={random=1216}] run give @p stone_block_slab2
execute at @a[scores={random=1218}] run give @p stone_axe
execute at @a[scores={random=1219}] run give @p stone
execute at @a[scores={random=1221}] run give @p sticky_piston
execute at @a[scores={random=1222}] run give @p stick
execute at @a[scores={random=1226}] run give @p squid_spawn_egg
execute at @a[scores={random=1227}] run give @p spyglass
execute at @a[scores={random=1228}] run give @p spruce_wood
execute at @a[scores={random=1230}] run give @p spruce_trapdoor
execute at @a[scores={random=1232}] run give @p spruce_stairs
execute at @a[scores={random=1233}] run give @p spruce_slab
execute at @a[scores={random=1234}] run give @p spruce_sign
execute at @a[scores={random=1235}] run give @p spruce_sapling
execute at @a[scores={random=1236}] run give @p spruce_pressure_plate
execute at @a[scores={random=1237}] run give @p spruce_planks
execute at @a[scores={random=1238}] run give @p spruce_log
execute at @a[scores={random=1239}] run give @p spruce_leaves
execute at @a[scores={random=1240}] run give @p spruce_hanging_sign
execute at @a[scores={random=1241}] run give @p spruce_fence_gate
execute at @a[scores={random=1242}] run give @p spruce_fence
execute at @a[scores={random=1244}] run give @p spruce_door
execute at @a[scores={random=1245}] run give @p spruce_chest_boat
execute at @a[scores={random=1246}] run give @p spruce_button
execute at @a[scores={random=1247}] run give @p spruce_boat
execute at @a[scores={random=1248}] run give @p spore_blossom
execute at @a[scores={random=1249}] run give @p sponge
execute at @a[scores={random=1250}] run give @p splash_potion
execute at @a[scores={random=1251}] run give @p spire_armor_trim_smithing_template
execute at @a[scores={random=1252}] run give @p spider_spawn_egg
execute at @a[scores={random=1253}] run give @p spider_eye
execute at @a[scores={random=1256}] run give @p soul_torch
execute at @a[scores={random=1257}] run give @p soul_soil
execute at @a[scores={random=1258}] run give @p soul_sand
execute at @a[scores={random=1259}] run give @p soul_lantern
execute at @a[scores={random=1261}] run give @p soul_campfire
execute at @a[scores={random=1262}] run give @p snowball
execute at @a[scores={random=1263}] run give @p snow_layer
execute at @a[scores={random=1264}] run give @p snow_golem_spawn_egg
execute at @a[scores={random=1265}] run give @p snow
execute at @a[scores={random=1266}] run give @p snout_armor_trim_smithing_template
execute at @a[scores={random=1267}] run give @p snort_pottery_sherd
execute at @a[scores={random=1268}] run give @p sniffer_spawn_egg
execute at @a[scores={random=1269}] run give @p sniffer_egg
execute at @a[scores={random=1270}] run give @p smooth_stone_slab
execute at @a[scores={random=1271}] run give @p smooth_sandstone_stairs
execute at @a[scores={random=1272}] run give @p smooth_stone
execute at @a[scores={random=1273}] run give @p smooth_red_sandstone_stairs
execute at @a[scores={random=1284}] run give @p smooth_quartz_stairs
execute at @a[scores={random=1285}] run give @p smooth_basalt
execute at @a[scores={random=1286}] run give @p smoker
execute at @a[scores={random=1287}] run give @p smithing_table
execute at @a[scores={random=1288}] run give @p small_dripleaf_block
execute at @a[scores={random=1289}] run give @p small_amethyst_bud
execute at @a[scores={random=1290}] run give @p slime_spawn_egg
execute at @a[scores={random=1291}] run give @p slime_ball
execute at @a[scores={random=1292}] run give @p slime
execute at @a[scores={random=1293}] run give @p skull_pottery_sherd
execute at @a[scores={random=1294}] run give @p skull_banner_pattern
execute at @a[scores={random=1295}] run give @p skull
execute at @a[scores={random=1296}] run give @p skeleton_spawn_egg
execute at @a[scores={random=1297}] run give @p skeleton_horse_spawn_egg
execute at @a[scores={random=1298}] run give @p silverfish_spawn_egg
execute at @a[scores={random=1299}] run give @p silver_glazed_terracotta
execute at @a[scores={random=1300}] run give @p silence_armor_trim_smithing_template
execute at @a[scores={random=1301}] run give @p shulker_spawn_egg
execute at @a[scores={random=1302}] run give @p shulker_shell
execute at @a[scores={random=1304}] run give @p shroomlight
execute at @a[scores={random=1305}] run give @p short_grass
execute at @a[scores={random=1306}] run give @p shield
execute at @a[scores={random=1307}] run give @p shelter_pottery_sherd
execute at @a[scores={random=1308}] run give @p sheep_spawn_egg
execute at @a[scores={random=1309}] run give @p shears
execute at @a[scores={random=1310}] run give @p sheaf_pottery_sherd
execute at @a[scores={random=1311}] run give @p shaper_armor_trim_smithing_template
execute at @a[scores={random=1312}] run give @p sentry_armor_trim_smithing_template
execute at @a[scores={random=1313}] run give @p seagrass
execute at @a[scores={random=1314}] run give @p sea_pickle
execute at @a[scores={random=1315}] run give @p sea_lantern
execute at @a[scores={random=1316}] run give @p sculk_vein
execute at @a[scores={random=1317}] run give @p sculk_shrieker
execute at @a[scores={random=1318}] run give @p sculk_sensor
execute at @a[scores={random=1319}] run give @p sculk_catalyst
execute at @a[scores={random=1320}] run give @p sculk
execute at @a[scores={random=1321}] run give @p scrape_pottery_sherd
execute at @a[scores={random=1322}] run give @p scaffolding
execute at @a[scores={random=1324}] run give @p sandstone_stairs
execute at @a[scores={random=1325}] run give @p sandstone_slab
execute at @a[scores={random=1327}] run give @p sandstone
execute at @a[scores={random=1328}] run give @p sand
execute at @a[scores={random=1329}] run give @p salmon_spawn_egg
execute at @a[scores={random=1330}] run give @p salmon_bucket
execute at @a[scores={random=1331}] run give @p salmon
execute at @a[scores={random=1332}] run give @p saddle