execute at @a[scores={random=1124}] run give @p twisting_vines
execute at @a[scores={random=1125}] run give @p turtle_spawn_egg
execute at @a[scores={random=1126}] run give @p turtle_scute
execute at @a[scores={random=1127}] run give @p turtle_helmet
execute at @a[scores={random=1128}] run give @p turtle_egg
execute at @a[scores={random=1129}] run give @p tuff_wall
execute at @a[scores={random=1130}] run give @p tuff_stairs
execute at @a[scores={random=1131}] run give @p tuff_slab
execute at @a[scores={random=1133}] run give @p tuff_bricks
execute at @a[scores={random=1134}] run give @p tuff_brick_wall
execute at @a[scores={random=1135}] run give @p tuff_brick_stairs
execute at @a[scores={random=1136}] run give @p tuff_brick_slab
execute at @a[scores={random=1138}] run give @p tuff
execute at @a[scores={random=1140}] run give @p tube_coral_fan
execute at @a[scores={random=1141}] run give @p tube_coral_block
execute at @a[scores={random=1142}] run give @p tube_coral
execute at @a[scores={random=1143}] run give @p tropical_fish_spawn_egg
execute at @a[scores={random=1144}] run give @p tropical_fish_bucket
execute at @a[scores={random=1145}] run give @p tropical_fish
execute at @a[scores={random=1146}] run give @p tripwire_hook
execute at @a[scores={random=1148}] run give @p trident
execute at @a[scores={random=1149}] run give @p trial_spawner
execute at @a[scores={random=1150}] run give @p trial_key
execute at @a[scores={random=1151}] run give @p trapped_chest
execute at @a[scores={random=1152}] run give @p trapdoor
execute at @a[scores={random=1153}] run give @p trader_llama_spawn_egg
execute at @a[scores={random=1154}] run give @p totem_of_undying
execute at @a[scores={random=1155}] run give @p torchflower_seeds
execute at @a[scores={random=1157}] run give @p torchflower
execute at @a[scores={random=1158}] run give @p torch
execute at @a[scores={random=1159}] run give @p tnt_minecart
execute at @a[scores={random=1160}] run give @p tnt
execute at @a[scores={random=1161}] run give @p tinted_glass
execute at @a[scores={random=1162}] run give @p tide_armor_trim_smithing_template
execute at @a[scores={random=1163}] run give @p target
execute at @a[scores={random=1164}] run give @p tall_grass
execute at @a[scores={random=1165}] run give @p tadpole_spawn_egg
execute at @a[scores={random=1166}] run give @p tadpole_bucket