execute at @a[scores={random=995}] run give @p writable_book
execute at @a[scores={random=997}] run give @p wooden_sword
execute at @a[scores={random=998}] run give @p wooden_slab
execute at @a[scores={random=999}] run give @p wooden_shovel
execute at @a[scores={random=1000}] run give @p wooden_pressure_plate
execute at @a[scores={random=1001}] run give @p wooden_pickaxe
execute at @a[scores={random=1002}] run give @p wooden_hoe
execute at @a[scores={random=1003}] run give @p wooden_door
execute at @a[scores={random=1004}] run give @p wooden_button
execute at @a[scores={random=1005}] run give @p wooden_axe
execute at @a[scores={random=1007}] run give @p wolf_spawn_egg
execute at @a[scores={random=1008}] run give @p wolf_armor
execute at @a[scores={random=1009}] run give @p wither_spawn_egg
execute at @a[scores={random=1010}] run give @p wither_skeleton_spawn_egg
execute at @a[scores={random=1011}] run give @p wither_rose
execute at @a[scores={random=1012}] run give @p witch_spawn_egg
execute at @a[scores={random=1013}] run give @p wind_charge
execute at @a[scores={random=1014}] run give @p wild_armor_trim_smithing_template
execute at @a[scores={random=1015}] run give @p white_wool
execute at @a[scores={random=1016}] run give @p white_tulip
execute at @a[scores={random=1017}] run give @p white_terracotta
execute at @a[scores={random=1018}] run give @p white_stained_glass_pane
execute at @a[scores={random=1019}] run give @p white_stained_glass
execute at @a[scores={random=1020}] run give @p white_shulker_box
execute at @a[scores={random=1021}] run give @p white_glazed_terracotta
execute at @a[scores={random=1022}] run give @p white_dye
execute at @a[scores={random=1023}] run give @p white_concrete_powder
execute at @a[scores={random=1024}] run give @p white_concrete
execute at @a[scores={random=1025}] run give @p white_carpet
execute at @a[scores={random=1027}] run give @p white_candle
execute at @a[scores={random=1028}] run give @p wheat_seeds
execute at @a[scores={random=1029}] run give @p wheat
execute at @a[scores={random=1030}] run give @p weeping_vines
execute at @a[scores={random=1031}] run give @p web
execute at @a[scores={random=1033}] run give @p weathered_cut_copper_stairs
execute at @a[scores={random=1034}] run give @p weathered_cut_copper_slab
execute at @a[scores={random=1035}] run give @p weathered_cut_copper
execute at @a[scores={random=1036}] run give @p weathered_copper_trapdoor
execute at @a[scores={random=1037}] run give @p weathered_copper_grate
execute at @a[scores={random=1038}] run give @p weathered_copper_door
execute at @a[scores={random=1039}] run give @p weathered_copper_bulb
execute at @a[scores={random=1040}] run give @p weathered_copper
execute at @a[scores={random=1041}] run give @p weathered_chiseled_copper
execute at @a[scores={random=1042}] run give @p wayfinder_armor_trim_smithing_template
execute at @a[scores={random=1044}] run give @p waxed_weathered_cut_copper_stairs
execute at @a[scores={random=1045}] run give @p waxed_weathered_cut_copper_slab
execute at @a[scores={random=1046}] run give @p waxed_weathered_cut_copper
execute at @a[scores={random=1047}] run give @p waxed_weathered_copper_trapdoor
execute at @a[scores={random=1048}] run give @p waxed_weathered_copper_grate
execute at @a[scores={random=1049}] run give @p waxed_weathered_copper_door
execute at @a[scores={random=1050}] run give @p waxed_weathered_copper_bulb
execute at @a[scores={random=1051}] run give @p waxed_weathered_copper
execute at @a[scores={random=1052}] run give @p waxed_weathered_chiseled_copper
execute at @a[scores={random=1054}] run give @p waxed_oxidized_cut_copper_stairs
execute at @a[scores={random=1055}] run give @p waxed_oxidized_cut_copper_slab
execute at @a[scores={random=1056}] run give @p waxed_oxidized_cut_copper
execute at @a[scores={random=1057}] run give @p waxed_oxidized_copper_trapdoor
execute at @a[scores={random=1058}] run give @p waxed_oxidized_copper_grate
execute at @a[scores={random=1059}] run give @p waxed_oxidized_copper_door
execute at @a[scores={random=1060}] run give @p waxed_oxidized_copper_bulb
execute at @a[scores={random=1061}] run give @p waxed_oxidized_copper
execute at @a[scores={random=1062}] run give @p waxed_oxidized_chiseled_copper
execute at @a[scores={random=1064}] run give @p waxed_exposed_cut_copper_stairs
execute at @a[scores={random=1065}] run give @p waxed_exposed_cut_copper_slab
execute at @a[scores={random=1066}] run give @p waxed_exposed_cut_copper
execute at @a[scores={random=1067}] run give @p waxed_exposed_copper_trapdoor
execute at @a[scores={random=1068}] run give @p waxed_exposed_copper_grate
execute at @a[scores={random=1069}] run give @p waxed_exposed_copper_door
execute at @a[scores={random=1070}] run give @p waxed_exposed_copper_bulb
execute at @a[scores={random=1071}] run give @p waxed_exposed_copper
execute at @a[scores={random=1072}] run give @p waxed_exposed_chiseled_copper
execute at @a[scores={random=1074}] run give @p waxed_cut_copper_stairs
execute at @a[scores={random=1075}] run give @p waxed_cut_copper_slab
execute at @a[scores={random=1076}] run give @p waxed_cut_copper
execute at @a[scores={random=1077}] run give @p waxed_copper_trapdoor
execute at @a[scores={random=1078}] run give @p waxed_copper_grate
execute at @a[scores={random=1079}] run give @p waxed_copper_door
execute at @a[scores={random=1080}] run give @p waxed_copper_bulb
execute at @a[scores={random=1081}] run give @p waxed_copper
execute at @a[scores={random=1082}] run give @p waxed_chiseled_copper
execute at @a[scores={random=1083}] run give @p waterlily
execute at @a[scores={random=1084}] run give @p water_bucket
execute at @a[scores={random=1085}] run give @p warped_wart_block
execute at @a[scores={random=1087}] run give @p warped_trapdoor
execute at @a[scores={random=1088}] run give @p warped_stem
execute at @a[scores={random=1090}] run give @p warped_stairs
execute at @a[scores={random=1091}] run give @p warped_slab
execute at @a[scores={random=1092}] run give @p warped_sign
execute at @a[scores={random=1093}] run give @p warped_roots
execute at @a[scores={random=1094}] run give @p warped_pressure_plate
execute at @a[scores={random=1095}] run give @p warped_planks
execute at @a[scores={random=1096}] run give @p warped_nylium
execute at @a[scores={random=1097}] run give @p warped_hyphae
execute at @a[scores={random=1098}] run give @p warped_hanging_sign
execute at @a[scores={random=1099}] run give @p warped_fungus_on_a_stick
execute at @a[scores={random=1100}] run give @p warped_fungus
execute at @a[scores={random=1101}] run give @p warped_fence_gate
execute at @a[scores={random=1102}] run give @p warped_fence
execute at @a[scores={random=1104}] run give @p warped_door
execute at @a[scores={random=1105}] run give @p warped_button
execute at @a[scores={random=1106}] run give @p warden_spawn_egg
execute at @a[scores={random=1107}] run give @p ward_armor_trim_smithing_template
execute at @a[scores={random=1108}] run give @p wandering_trader_spawn_egg