execute at @a[scores={random=982}] run give @p yellow_wool
execute at @a[scores={random=983}] run give @p yellow_terracotta
execute at @a[scores={random=984}] run give @p yellow_stained_glass_pane
execute at @a[scores={random=985}] run give @p yellow_stained_glass
execute at @a[scores={random=986}] run give @p yellow_shulker_box
execute at @a[scores={random=987}] run give @p yellow_glazed_terracotta
execute at @a[scores={random=988}] run give @p yellow_dye
execute at @a[scores={random=989}] run give @p yellow_concrete_powder
execute at @a[scores={random=990}] run give @p yellow_concrete
execute at @a[scores={random=991}] run give @p yellow_carpet
execute at @a[scores={random=993}] run give @p yellow_candle