scoreboard players random @s random 1 138
execute at @s[scores={random=1}] run give @s potion 1 1
execute at @s[scores={random=2}] run give @s potion 1 2
execute at @s[scores={random=3}] run give @s potion 1 3
execute at @s[scores={random=4}] run give @s potion 1 4
execute at @s[scores={random=5}] run give @s potion 1 5
execute at @s[scores={random=6}] run give @s potion 1 6
execute at @s[scores={random=7}] run give @s potion 1 7
execute at @s[scores={random=8}] run give @s potion 1 8
execute at @s[scores={random=9}] run give @s potion 1 9
execute at @s[scores={random=10}] run give @s potion 1 10
execute at @s[scores={random=11}] run give @s potion 1 11
execute at @s[scores={random=12}] run give @s potion 1 12
execute at @s[scores={random=13}] run give @s potion 1 13
execute at @s[scores={random=14}] run give @s potion 1 14
execute at @s[scores={random=15}] run give @s potion 1 15
execute at @s[scores={random=16}] run give @s potion 1 16
execute at @s[scores={random=17}] run give @s potion 1 17
execute at @s[scores={random=18}] run give @s potion 1 18
execute at @s[scores={random=19}] run give @s potion 1 19
execute at @s[scores={random=20}] run give @s potion 1 20
execute at @s[scores={random=21}] run give @s potion 1 21
execute at @s[scores={random=22}] run give @s potion 1 22
execute at @s[scores={random=23}] run give @s potion 1 23
execute at @s[scores={random=24}] run give @s potion 1 24
execute at @s[scores={random=25}] run give @s potion 1 25
execute at @s[scores={random=26}] run give @s potion 1 26
execute at @s[scores={random=27}] run give @s potion 1 27
execute at @s[scores={random=28}] run give @s potion 1 28
execute at @s[scores={random=29}] run give @s potion 1 29
execute at @s[scores={random=30}] run give @s potion 1 30
execute at @s[scores={random=31}] run give @s potion 1 31
execute at @s[scores={random=32}] run give @s potion 1 32
execute at @s[scores={random=33}] run give @s potion 1 33
execute at @s[scores={random=34}] run give @s potion 1 34
execute at @s[scores={random=35}] run give @s potion 1 35
execute at @s[scores={random=36}] run give @s potion 1 36
execute at @s[scores={random=37}] run give @s potion 1 37
execute at @s[scores={random=38}] run give @s potion 1 38
execute at @s[scores={random=39}] run give @s potion 1 39
execute at @s[scores={random=40}] run give @s potion 1 40
execute at @s[scores={random=41}] run give @s potion 1 41
execute at @s[scores={random=42}] run give @s potion 1 42
execute at @s[scores={random=43}] run give @s potion 1 43
execute at @s[scores={random=44}] run give @s potion 1 44
execute at @s[scores={random=45}] run give @s potion 1 45
execute at @s[scores={random=46}] run give @s potion 1 46
execute at @s[scores={random=47}] run give @s splash_potion 1 1
execute at @s[scores={random=48}] run give @s splash_potion 1 2
execute at @s[scores={random=49}] run give @s splash_potion 1 3
execute at @s[scores={random=50}] run give @s splash_potion 1 4
execute at @s[scores={random=51}] run give @s splash_potion 1 5
execute at @s[scores={random=52}] run give @s splash_potion 1 6
execute at @s[scores={random=53}] run give @s splash_potion 1 7
execute at @s[scores={random=54}] run give @s splash_potion 1 8
execute at @s[scores={random=55}] run give @s splash_potion 1 9
execute at @s[scores={random=56}] run give @s splash_potion 1 10
execute at @s[scores={random=57}] run give @s splash_potion 1 11
execute at @s[scores={random=58}] run give @s splash_potion 1 12
execute at @s[scores={random=59}] run give @s splash_potion 1 13
execute at @s[scores={random=60}] run give @s splash_potion 1 14
execute at @s[scores={random=61}] run give @s splash_potion 1 15
execute at @s[scores={random=62}] run give @s splash_potion 1 16
execute at @s[scores={random=63}] run give @s splash_potion 1 17
execute at @s[scores={random=64}] run give @s splash_potion 1 18
execute at @s[scores={random=65}] run give @s splash_potion 1 19
execute at @s[scores={random=66}] run give @s splash_potion 1 20
execute at @s[scores={random=67}] run give @s splash_potion 1 21
execute at @s[scores={random=68}] run give @s splash_potion 1 22
execute at @s[scores={random=69}] run give @s splash_potion 1 23
execute at @s[scores={random=70}] run give @s splash_potion 1 24
execute at @s[scores={random=71}] run give @s splash_potion 1 25
execute at @s[scores={random=72}] run give @s splash_potion 1 26
execute at @s[scores={random=73}] run give @s splash_potion 1 27
execute at @s[scores={random=74}] run give @s splash_potion 1 28
execute at @s[scores={random=75}] run give @s splash_potion 1 29
execute at @s[scores={random=76}] run give @s splash_potion 1 30
execute at @s[scores={random=77}] run give @s splash_potion 1 31
execute at @s[scores={random=78}] run give @s splash_potion 1 32
execute at @s[scores={random=79}] run give @s splash_potion 1 33
execute at @s[scores={random=80}] run give @s splash_potion 1 34
execute at @s[scores={random=81}] run give @s splash_potion 1 35
execute at @s[scores={random=82}] run give @s splash_potion 1 36
execute at @s[scores={random=83}] run give @s splash_potion 1 37
execute at @s[scores={random=84}] run give @s splash_potion 1 38
execute at @s[scores={random=85}] run give @s splash_potion 1 39
execute at @s[scores={random=86}] run give @s splash_potion 1 40
execute at @s[scores={random=87}] run give @s splash_potion 1 41
execute at @s[scores={random=88}] run give @s splash_potion 1 42
execute at @s[scores={random=89}] run give @s splash_potion 1 43
execute at @s[scores={random=90}] run give @s splash_potion 1 44
execute at @s[scores={random=91}] run give @s splash_potion 1 45
execute at @s[scores={random=92}] run give @s splash_potion 1 46
execute at @s[scores={random=93}] run give @s lingering_potion 1 1
execute at @s[scores={random=94}] run give @s lingering_potion 1 2
execute at @s[scores={random=95}] run give @s lingering_potion 1 3
execute at @s[scores={random=96}] run give @s lingering_potion 1 4
execute at @s[scores={random=97}] run give @s lingering_potion 1 5
execute at @s[scores={random=98}] run give @s lingering_potion 1 6
execute at @s[scores={random=99}] run give @s lingering_potion 1 7
execute at @s[scores={random=100}] run give @s lingering_potion 1 8
execute at @s[scores={random=101}] run give @s lingering_potion 1 9
execute at @s[scores={random=102}] run give @s lingering_potion 1 10
execute at @s[scores={random=103}] run give @s lingering_potion 1 11
execute at @s[scores={random=104}] run give @s lingering_potion 1 12
execute at @s[scores={random=105}] run give @s lingering_potion 1 13
execute at @s[scores={random=106}] run give @s lingering_potion 1 14
execute at @s[scores={random=107}] run give @s lingering_potion 1 15
execute at @s[scores={random=108}] run give @s lingering_potion 1 16
execute at @s[scores={random=109}] run give @s lingering_potion 1 17
execute at @s[scores={random=110}] run give @s lingering_potion 1 18
execute at @s[scores={random=111}] run give @s lingering_potion 1 19
execute at @s[scores={random=112}] run give @s lingering_potion 1 20
execute at @s[scores={random=113}] run give @s lingering_potion 1 21
execute at @s[scores={random=114}] run give @s lingering_potion 1 22
execute at @s[scores={random=115}] run give @s lingering_potion 1 23
execute at @s[scores={random=116}] run give @s lingering_potion 1 24
execute at @s[scores={random=117}] run give @s lingering_potion 1 25
execute at @s[scores={random=118}] run give @s lingering_potion 1 26
execute at @s[scores={random=119}] run give @s lingering_potion 1 27
execute at @s[scores={random=120}] run give @s lingering_potion 1 28
execute at @s[scores={random=121}] run give @s lingering_potion 1 29
execute at @s[scores={random=122}] run give @s lingering_potion 1 30
execute at @s[scores={random=123}] run give @s lingering_potion 1 31
execute at @s[scores={random=124}] run give @s lingering_potion 1 32
execute at @s[scores={random=125}] run give @s lingering_potion 1 33
execute at @s[scores={random=126}] run give @s lingering_potion 1 34
execute at @s[scores={random=127}] run give @s lingering_potion 1 35
execute at @s[scores={random=128}] run give @s lingering_potion 1 36
execute at @s[scores={random=129}] run give @s lingering_potion 1 37
execute at @s[scores={random=130}] run give @s lingering_potion 1 38
execute at @s[scores={random=131}] run give @s lingering_potion 1 39
execute at @s[scores={random=132}] run give @s lingering_potion 1 40
execute at @s[scores={random=133}] run give @s lingering_potion 1 41
execute at @s[scores={random=134}] run give @s lingering_potion 1 42
execute at @s[scores={random=135}] run give @s lingering_potion 1 43
execute at @s[scores={random=136}] run give @s lingering_potion 1 44
execute at @s[scores={random=137}] run give @s lingering_potion 1 45
execute at @s[scores={random=138}] run give @s lingering_potion 1 46